### ISSUE TITLE
Make TQVaultAE portable

### ISSUE THREAD

**Issue by EtienneLamoureux** [EtienneLamoureux/TQVaultAE#10]
Make TQVaultAE only use of it's local folder for the database and config files by default (Vault Path in the options).

**Comment by Malgardian** [comment]
I have been looking into this. Apparently you can't set a custom location for the user.config file without ripping out the whole settings architecture of TQVault. Then again I might just be missing the obvious workaround that might or might not be possible.

**Comment by EtienneLamoureux** [comment]
So we might need a big refactor. I'm not too scared of it, but it depends how much unchangeable design decisions have been made previously.

**Comment by Malgardian** [comment]
I don't know if that would be worth it, really. We could leave it the way it is now, which is sort of portable. I couldn't really help with rewriting the settings system anyway, as it is probably beyond my abilities. If you do want to do it, go for it.

**Comment by epinter** [comment]
If in the future we decide to change, maybe we can use the ini file support introduced in https://github.com/EtienneLamoureux/TQVaultAE/pull/44 and https://github.com/EtienneLamoureux/TQVaultAE/pull/45, or something like that.
