### ISSUE TITLE
Fix rare error when opening vault file: "Expecting 'stackCount', Got 'end_block'"

### ISSUE THREAD

**Issue by Pwntheon** [EtienneLamoureux/TQVaultAE#102]
So, i got an error when opening a character (cannot reproduce as it fixed itself after i sorted stash and tried again later) which said something about failing to load an item because it found end of data instead of stack size when reading.

Despite the error everything went fine, so i transferred some items. When quitting to save, it turns out i lost the items i transferred to the stash of that character.

Maybe implement a lock to an inventory when an error is detected so items aren't lost?

**Comment by EtienneLamoureux** [comment]
If you manage to remember the item that caused the problem or if you can find and attach the problematic vault file itself, it would help a lot to find the root cause of the problem.

As for unforeseen errors will unfortunately always remain unforeseen, which is why TQVaultAE boasts an extensive [backup system](https://github.com/EtienneLamoureux/TQVaultAE#features) (look for "Character backups").

**Comment by Sennarrion** [comment]
This Vault file has that error.  For some reason these are all stored under "Titan Quest - Immortal Throne" even though this is Titan Quest - Anniversary Edition plus Ragnarok.

Error reading file " _GodKiller\winsys.dxb" at position 22248.  Expecting 'stackCount', Got 'end_block'
[_Godkiller.zip](https://github.com/EtienneLamoureux/TQVaultAE/files/2771389/_Godkiller.zip)

**Comment by EtienneLamoureux** [comment]
@Sennarrion Thanks a lot for the files, it'll help debug the issue a lot!

Don't worry about the folder name, it hasn't been renamed since the good old days :)

**Comment by hguy** [comment]
@EtienneLamoureux it looks like record corruption.

TQVault is still able to read most of the content despite the error.
Changing the position of an item inside will force TQVault to rewrite the file and resolve the error popup on opening.

This issue can be closed.

![image](https://user-images.githubusercontent.com/31834707/184997018-d58616b4-f2d1-4455-ab76-4364d23b6e5d.png)
