### ISSUE TITLE
Failed to start, can't open

### ISSUE THREAD

**Issue by XinXinkkk** [EtienneLamoureux/TQVaultAE#103]
---------------------------
Error Loading Resources
---------------------------
未将对象引用设置到对象的实例。

This may be caused by a bad language or game path setting.
Would you like to restart TQVault?
---------------------------
是(Y)   否(N)   
---------------------------

**Comment by XinXinkkk** [comment]
After editing the TQVaultAE.exe.config file, the program started without response.


`TQVaultAE.exe.config
<?xml version="1.0"?>
<configuration>
  <configSections>
    <sectionGroup name="userSettings" type="System.Configuration.UserSettingsGroup, System, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089">
      <section name="TQVaultAE.GUI.Properties.Settings" type="System.Configuration.ClientSettingsSection, System, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" allowExeDefinition="MachineToLocalUser" requirePermission="false"/>
      <section name="TQVault.Properties.Settings" type="System.Configuration.ClientSettingsSection, System, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" allowExeDefinition="MachineToLocalUser" requirePermission="false"/>
    </sectionGroup>
    <sectionGroup name="applicationSettings" type="System.Configuration.ApplicationSettingsGroup, System, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089">
      <section name="TQVaultAE.GUI.Properties.Settings" type="System.Configuration.ClientSettingsSection, System, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" requirePermission="false"/>
      <section name="TQVault.Properties.Settings" type="System.Configuration.ClientSettingsSection, System, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" requirePermission="false"/>
    </sectionGroup>
  </configSections>
  <userSettings>
    <TQVaultAE.GUI.Properties.Settings>
      <setting name="SkipTitle" serializeAs="String">
        <value>True</value>
      </setting>
      <setting name="LoadLastVault" serializeAs="String">
        <value>True</value>
      </setting>
      <setting name="LoadLastCharacter" serializeAs="String">
        <value>True</value>
      </setting>
      <setting name="LastVaultName" serializeAs="String">
        <value />
      </setting>
      <setting name="LastCharacterName" serializeAs="String">
        <value />
      </setting>
      <setting name="AutoDetectLanguage" serializeAs="String">
        <value>True</value>
      </setting>
      <setting name="AutoDetectGamePath" serializeAs="String">
        <value>True</value>
      </setting>
      <setting name="TQLanguage" serializeAs="String">
        <value />
      </setting>
      <setting name="VaultPath" serializeAs="String">
        <value />
      </setting>
      <setting name="LoadAllFiles" serializeAs="String">
        <value>True</value>
      </setting>
      <setting name="SuppressWarnings" serializeAs="String">
        <value>False</value>
      </setting>
      <setting name="CheckForNewVersions" serializeAs="String">
        <value>False</value>
      </setting>
      <setting name="AllowItemCopy" serializeAs="String">
        <value>False</value>
      </setting>
      <setting name="AllowItemEdit" serializeAs="String">
        <value>False</value>
      </setting>
    <setting name="TQITPath" serializeAs="String">
		<value>N:\TQAEV157</value>
		</setting>
	<setting name="TQPath" serializeAs="String">
    <value>N:\TQAEV157</value>
      <setting name="ModEnabled" serializeAs="String">
        <value>False</value>
      </setting>
      <setting name="CustomMap" serializeAs="String">
        <value />
      </setting>
      <setting name="Scale" serializeAs="String">
        <value>1</value>
      </setting>
      <setting name="LoadAllFilesCompleted" serializeAs="String">
        <value>True</value>
      </setting>
      <setting name="PlayerReadonly" serializeAs="String">
        <value>True</value>
      </setting>
    </TQVaultAE.GUI.Properties.Settings>
    <TQVault.Properties.Settings>
      <setting name="SkipTitle" serializeAs="String">
        <value>True</value>
      </setting>
      <setting name="FilterITChars" serializeAs="String">
        <value>False</value>
      </setting>
      <setting name="FilterTQChars" serializeAs="String">
        <value>False</value>
      </setting>
      <setting name="LoadLastVault" serializeAs="String">
        <value>True</value>
      </setting>
      <setting name="LoadLastCharacter" serializeAs="String">
        <value>True</value>
      </setting>
      <setting name="LastVaultName" serializeAs="String">
        <value/>
      </setting>
      <setting name="LastCharacterName" serializeAs="String">
        <value/>
      </setting>
      <setting name="AutoDetectLanguage" serializeAs="String">
        <value>True</value>
      </setting>
      <setting name="AutoDetectGamePath" serializeAs="String">
        <value>True</value>
      </setting>
      <setting name="TQLanguage" serializeAs="String">
        <value/>
      </setting>
      <setting name="VaultPath" serializeAs="String">
        <value/>
      </setting>
      <setting name="LoadAllFiles" serializeAs="String">
        <value>True</value>
      </setting>
      <setting name="SuppressWarnings" serializeAs="String">
        <value>False</value>
      </setting>
      <setting name="CheckForNewVersions" serializeAs="String">
        <value>True</value>
      </setting>
      <setting name="AllowItemCopy" serializeAs="String">
        <value>True</value>
      </setting>
      <setting name="AllowItemEdit" serializeAs="String">
        <value>True</value>
      </setting>
      <setting name="TQITPath" serializeAs="String">
        <value/>
      </setting>
      <setting name="TQPath" serializeAs="String">
        <value/>
      </setting>
      <setting name="ModEnabled" serializeAs="String">
        <value>False</value>
      </setting>
      <setting name="CustomMap" serializeAs="String">
        <value/>
      </setting>
      <setting name="Scale" serializeAs="String">
        <value>1</value>
      </setting>
      <setting name="LoadAllFilesCompleted" serializeAs="String">
        <value>True</value>
      </setting>
      <setting name="PlayerReadonly" serializeAs="String">
        <value>True</value>
      </setting>
    </TQVault.Properties.Settings>
  </userSettings>
  <applicationSettings>
    <TQVaultAE.GUI.Properties.Settings>
      <setting name="DebugEnabled" serializeAs="String">
        <value>False</value>
      </setting>
      <setting name="ARCFileDebugLevel" serializeAs="String">
        <value>0</value>
      </setting>
      <setting name="DatabaseDebugLevel" serializeAs="String">
        <value>0</value>
      </setting>
      <setting name="ItemDebugLevel" serializeAs="String">
        <value>0</value>
      </setting>
      <setting name="ItemAttributesDebugLevel" serializeAs="String">
        <value>0</value>
      </setting>
      <setting name="NoToolTipDelay" serializeAs="String">
        <value>False</value>
      </setting>
      <setting name="GameLanguages" serializeAs="String">
        <value>de,en,es,fr,it,pl,ru,cs,zh</value>
      </setting>
      <setting name="UILanguage" serializeAs="String">
        <value />
      </setting>
      <setting name="UpdateURL" serializeAs="String">
        <value>http://www.soulseekkor.com/apps/tqvault/</value>
      </setting>
      <setting name="ShowSkillLevel" serializeAs="String">
        <value>False</value>
      </setting>
      <setting name="FadeInInterval" serializeAs="String">
        <value>0.1</value>
      </setting>
      <setting name="FadeOutInterval" serializeAs="String">
        <value>0.2</value>
      </setting>
    </TQVaultAE.GUI.Properties.Settings>
    <TQVault.Properties.Settings>
      <setting name="DebugEnabled" serializeAs="String">
        <value>False</value>
      </setting>
      <setting name="ARCFileDebugLevel" serializeAs="String">
        <value>0</value>
      </setting>
      <setting name="DatabaseDebugLevel" serializeAs="String">
        <value>0</value>
      </setting>
      <setting name="ItemDebugLevel" serializeAs="String">
        <value>0</value>
      </setting>
      <setting name="ItemAttributesDebugLevel" serializeAs="String">
        <value>0</value>
      </setting>
      <setting name="NoToolTipDelay" serializeAs="String">
        <value>False</value>
      </setting>
      <setting name="GameLanguages" serializeAs="String">
        <value>de,en,es,fr,it,pl,ru,cs</value>
      </setting>
      <setting name="UILanguage" serializeAs="String">
        <value/>
      </setting>
      <setting name="UpdateURL" serializeAs="String">
        <value>http://www.soulseekkor.com/apps/tqvault/</value>
      </setting>
      <setting name="ShowSkillLevel" serializeAs="String">
        <value>False</value>
      </setting>
      <setting name="FadeInInterval" serializeAs="String">
        <value>0.1</value>
      </setting>
      <setting name="FadeOutInterval" serializeAs="String">
        <value>0.2</value>
      </setting>
    </TQVault.Properties.Settings>
  </applicationSettings>
  <startup>
    
  <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.6.1"/></startup>
</configuration>
`

**Comment by XinXinkkk** [comment]
An application error occurred.
Message : 配置系统未能初始化

Stack Trace:
   在 System.Configuration.ConfigurationManager.PrepareConfigSystem()
   在 System.Configuration.ConfigurationManager.RefreshSection(String sectionName)
   在 System.Configuration.ClientSettingsStore.ReadSettings(String sectionName, Boolean isUserScoped)
   在 System.Configuration.LocalFileSettingsProvider.GetPropertyValues(SettingsContext context, SettingsPropertyCollection properties)
   在 System.Configuration.SettingsBase.GetPropertiesFromProvider(SettingsProvider provider)
   在 System.Configuration.SettingsBase.GetPropertyValueByName(String propertyName)
   在 System.Configuration.SettingsBase.get_Item(String propertyName)
   在 System.Configuration.ApplicationSettingsBase.GetPropertyValue(String propertyName)
   在 System.Configuration.ApplicationSettingsBase.get_Item(String propertyName)
   在 TQVaultAE.GUI.Properties.Settings.get_UILanguage()
   在 TQVaultAE.GUI.MainForm.SetUILanguage()
   在 TQVaultAE.GUI.MainForm..ctor()
   在 TQVaultAE.GUI.Program.Main()

**Comment by Ninakoru** [comment]
Hi, I've seen this kind of error a lot before, maybe you just broke the config file!!

I recommend you to get the config file from the zip again and take special care when you edit it. 

you could also check one of this kind of sites to validate the file has the proper format, any un-expected character or a missing quote would break the file:

https://www.xmlvalidation.com/

**Comment by EtienneLamoureux** [comment]
It indeed seems configuration file related. If all else fails, download a new one here:
