### ISSUE TITLE
Support Atlantis

### ISSUE THREAD

**Issue by EtienneLamoureux** [EtienneLamoureux/TQVaultAE#107]
Titan Quest has a new expansion: [Atlantis](https://titanquestgame.com/titan-quest-atlantis-release/).
- [ ] Support the new `XPACK3` items
  - [ ] Using ARZExplorer, there seem to be another relic/charm similar the the Power of Nerthus. Make sure to support it.
- [ ] Support the new character file structure
  - As noted in #106, the character file structure changed, breaking the current release of TQVaultAE
- [x] ~~Support the new relics&charms/recipes/artifacts vault~~ (See #108)
- [ ] Check for backwards compatibility of existing vault files
- [ ] Update documentation

**Comment by EtienneLamoureux** [comment]
As noted in #106, the data structure of the files changed, breaking TQVault.

**Comment by Ninakoru** [comment]
Hi, I'll help fixing TQ Vault AE to support the new DLC.

I don't want to waste time redundant work.

Is someone working with the new character save file structure?

**Comment by HoggeL** [comment]
> Hi, I'll help fixing TQ Vault AE to support the new DLC.
> 
> I don't want to waste time redundant work.
> 
> Is someone working with the new character save file structure?

Hey Ninakoru, I've done some work so far to support our new save file structure. I'll reference some of our code, then get the fix into TQVaultAE as soon as possible

**Comment by EtienneLamoureux** [comment]
If items have 2 enchantment slots now, we could support is as part of another ticket. It entails menu changes and such.
It would allow us to release something that's not broken quicker.

**Comment by Ninakoru** [comment]
Yeah I'm going directly towards a quick version so people does not lose information moving around items.

So far:

Atlantis DLC Discovery, proper text resources loaded conditionally, proper GUI resources (DONE)

New item property RelicBonus2Id (this one will be long, as there are some item craft/GUI involved)

Until I get something that parses everything fully all info and doesn't lose it...

**Comment by Ninakoru** [comment]
Got it working, tomorrow I will do some extra testing to ensure no data is lost, and I'll make a proper fork -> pull request.

**Comment by epinter** [comment]
Yesterday I've sent a pull request with a initial support for the new save format.

**Comment by Ninakoru** [comment]
I have checked it out, part of the changes are very similar to mine, however I handled the conditional parsing for the new atlantis properties a bit different. Also you missed the new text resources. Anyways your edits should let the Vault work properly at first glance, don't know why they were not checked/approved.

**Comment by epinter** [comment]
The save format changed for everyone, not just for people with DLC.

**Comment by Ninakoru** [comment]
Even if all the characters were somewhat migrated/imported and backed up with the new patch, the characters I have that I did not open with the game updated still maintain the old save format.

**Comment by epinter** [comment]
Yes, agree. What I mean it's you don't need to have Atlantis dlc (xpack3 folders) to have a save with new fields (relicName2, etc). A user who dont own the dlc but have game in version 2.1, will have the save in new format.

**Comment by EtienneLamoureux** [comment]
Let's make the decision to only support the fully patched game: let's assume all characters are in the new format

**Comment by Ninakoru** [comment]
Waiting for epinter changes to be reflected on the main version, I have some extra goodies to add on top of his work for a more complete DLC support.

**Comment by EtienneLamoureux** [comment]
I merged just now

**Comment by Ninakoru** [comment]
Great, working on the tooltip for dual relic, the code for the tooltip generation is a bit of a mess... :)

**Comment by Ninakoru** [comment]
I've got ready, before commit, @EtienneLamoureux : Do you want me to upgrade the version on my pull request? I guess 2.7.0 should be fitting.

**Comment by EtienneLamoureux** [comment]
Since this is a breaking change and a big deal, I think I'd want it to go to v3.0.0

**Comment by Ninakoru** [comment]
Oh boy just seen it, just sent the pull request #113 .
Let me know if you want me to edit to and add the V3.0 upgrade, also there's a mess with resources due to how visual studio mess the resource items when you add one entry using their UI.

**Comment by hguy** [comment]
Anyone who can add save files from all versions to the repo for references during dev ?
I only have latest versions.

**Comment by EtienneLamoureux** [comment]
@hguy we'll see what we can do, but support should focus on the latest version only.

**Comment by EtienneLamoureux** [comment]
Thanks everyone, I created a new release with your changes!
