### ISSUE TITLE
Support the new relics&charms/recipes/artifacts vault

### ISSUE THREAD

**Issue by EtienneLamoureux** [EtienneLamoureux/TQVaultAE#108]
Atlantis introduced a new shared vault. Support it in the UI

**Comment by Ninakoru** [comment]
I'm working on it.

**Comment by Ninakoru** [comment]
This feature is done, and ready for a merge on #116 .

Attached a sample UI:
![relic_vault](https://user-images.githubusercontent.com/6901775/57800544-ee904780-7751-11e9-9b1e-148dac8d0af3.jpg)
