### ISSUE TITLE
Czech localization problem / font problem

### ISSUE THREAD

**Issue by Sir-Mac** [EtienneLamoureux/TQVaultAE#114]
Hi,

in the version 2.6.0 of TQVaultAE, the special characters, czech letters (**á é í ó ú ů ý ž š č ř ď ť ň ě** and **Á É Í Ó Ú Ů Ý Ž Š Č Ř Ď Ť Ň Ě**) ARE NOT FULLY SUPPORTED.

In the version 2.5.6 of TQVaultAE THOSE LETTERS WERE FULLY SUPPORTED. 

Could you, please, in any future release of the program, use the font, which was used in the version 2.5.6? I attach the screen of the version 2.6.0, so you can see, what am I talking about.

Thank you in advance,
Sir-Mac
![TQVaultAE260 problem](https://user-images.githubusercontent.com/50591247/57716689-d51bcc80-7679-11e9-9b19-69c2d6dad136.png)

**Comment by EtienneLamoureux** [comment]
There were some font fixes lately, we'll investgate what broke it.

**Comment by Sir-Mac** [comment]
I am using the version 3.0.0 alpha right now and in this version, the font is alright again. If it occurs (or anything else) in any of future versions, I will make a proper thread about it.

Thank you once again, Etienne Lamoureux

**Comment by EtienneLamoureux** [comment]
Glad to hear it! Although the credits go to our awesome contributors.
