### ISSUE TITLE
Release 3.0.0-alpha + Build and zip the build folder

### ISSUE THREAD

**Issue by EtienneLamoureux** [EtienneLamoureux/TQVaultAE#115]
@NorthFury @epinter 
Hello guys,
Could either of you build the latest source and send the zip my way?
I unfortunately can't build the source code right now, but I'll go through the busy work of the release with a zip archive.

**Comment by epinter** [comment]
[Release.zip](https://github.com/EtienneLamoureux/TQVaultAE/files/3182340/Release.zip)
