### ISSUE TITLE
Restore stash backup files?

### ISSUE THREAD

**Issue by thiagotw** [EtienneLamoureux/TQVaultAE#117]
By accident i move relics from relics stash to transfer stash with the game and the TQVault open and when i close the TQVault relics gone, trying to restore winsys.dxb and winsys.dxg but since it does't backup the relic stash i think i lose it forever right? 

The files that i should replace are locate in?                                                                                             My Games\Titan Quest - Immortal Throne\SaveData\Sys

**Comment by EtienneLamoureux** [comment]
You can check our documentation for where the backups are located. The configuration popup will tell you where your game data is being read from. I'm not certain the tranafer and relic stashes are backed-up at this moment. 

For future reference, TQVaultAE saves when you close it and doesn't live updare when the game runs. So, if you realize it's open while you run the game, the safest option is to kill it using the task manager.
