### ISSUE TITLE
Change version labels to 3.0.0

### ISSUE THREAD

**Issue by EtienneLamoureux** [EtienneLamoureux/TQVaultAE#119]
As stated in the title, the program still says 2.6 which confuses some users who are upgrading.

**Comment by Ninakoru** [comment]
Upgraded the assembly version to 3.1.0 on #116

**Comment by EtienneLamoureux** [comment]
Thanks, but we should stay on 3.0.0 since the released version was only "alpha". Iuse prereleases to let people know they should expect bugs.

**Comment by Ninakoru** [comment]
Ok, downgraded to 3.0.0
