### ISSUE TITLE
Programm doenst start

### ISSUE THREAD

**Issue by Sneakor** [EtienneLamoureux/TQVaultAE#121]
I downloaded the 3.0.0 and 2.6 Versions.

When i unzip these and i try to start the programm nothing happens.
Nothing in Task Manager or somewhere else. All drivers are Up to Date.
Stopped Anti Virus.

Can you help me maybe?

**Comment by EtienneLamoureux** [comment]
That will be hard to track down. Does the tool produce a debug file you could send us? It would be in the root folder of the tool.

**Comment by Marctiello** [comment]
> 
> 
> That will be hard to track down. Does the tool produce a debug file you could send us? It would be in the root folder of the tool.

Hello EtienneLamoureux, 

first thank you so much for the work you make in those updates.
I have the same issue, no error code pops up or anything , it just wont start at all.  Exe is allowed in my firewall.

**Comment by EtienneLamoureux** [comment]
Is the program [blacklisted on your machine](https://www.thewindowsclub.com/whitelist-program-windows-10)?

**Comment by Marctiello** [comment]
>
> 
> Is the program [blacklisted on your machine](https://www.thewindowsclub.com/whitelist-program-windows-10)?

No its not.

**Comment by EtienneLamoureux** [comment]
Did you try the solution from our F.A.Q.?

You can find it under *Q. After updating from an older version of TQVault (2.18 or older), the new program won't start.*

**Comment by Marctiello** [comment]
I did try it already , when i type regsvr /u VXPLib.dll i get an error message

**Comment by Marctiello** [comment]
Error loading module "VXPLib.dll".

Make sure that the binary file is stored at the specified path or debug the file to avoid problems with the binary file or dependent DLL files.

The specified module was not found


This is what i get.

**Comment by EtienneLamoureux** [comment]
Alright, so we ruled out the problem detailed in the F.A.Q.

**Comment by moststandarduser** [comment]
It may not be the issue in the FAQs, but it must be related to some file that is created somewhere on the computer outside the TQVault folder.

I tried every version of TQVault on this page, tried opening every one of them and they all create the same error. Because I delete everything before downloading another version, it must be something created elsewhere - is there any way I can check where TQVault creates files such as the VXPLib.dll?

**Comment by EtienneLamoureux** [comment]
You could try unregistering all the DLLs present in the installation folder.

**Comment by moststandarduser** [comment]
I get the same error for every single one of them:

Error loading module "[insert name]".

Make sure that the binary file is stored at the specified path or debug the file to avoid problems with the binary file or dependent DLL files.

The specified module was not found

**Comment by moststandarduser** [comment]
Do you have any other ideas? I appreciate that you can't really see and understand what has happened here, but maybe you can think of a general solution to undo whatever a faulty program paired with my stupidity could have done.
Other than unregistering DLLs, is there something else that can wipe my laptop clean from anything TQVault related?

**Comment by EtienneLamoureux** [comment]
I'll go over this again later in the day and try to suggest a few things.

**Comment by EtienneLamoureux** [comment]
You might want to try [the new release](https://github.com/EtienneLamoureux/TQVaultAE/releases/tag/3.1.0-alpha)

**Comment by Marctiello** [comment]
@EtienneLamoureux  Hello etienne now wer are getting closer i get another notice : When i click on the exe i get : Vault Path could not be found , the standard path was selected.

but the vault never opens up completely

**Comment by moststandarduser** [comment]
@Marctiello I have the same error. it looks like this is what is answered in the FAQ under _Q. Error Loading Resources. This may be caused by a bad language or game path setting._
You can try these steps and see if it works. 

@EtienneLamoureux My previous error is gone, and now I had the same error as Marctiello and followed the steps in the FAQ. The error disappeared, but TQVault still doesn't open.

**Comment by moststandarduser** [comment]
My previous error is gone. Now I am getting the same message:

_The vault path was not set.
Using the default setting.
Please verify the vault path with the configuration dialogue._

**Comment by moststandarduser** [comment]
Can you please help with this error? It looks a bit like the one that is described in the FAQs but that solution didn't do anything for me...
