### ISSUE TITLE
error in 3.0.0

### ISSUE THREAD

**Issue by barabon** [EtienneLamoureux/TQVaultAE#122]
Has anyone had this problem? my version is 3.0.0
![2019-05-17_20h56_55](https://user-images.githubusercontent.com/50750833/57947047-8161eb00-78e6-11e9-8a6a-12edafed0f2d.png)
p.s. sorry, my english is bad

**Comment by Ninakoru** [comment]
You can open that character in-game? if so please zip and send the player.chr file so we can check what happens when the program tries to load it.

**Comment by EtienneLamoureux** [comment]
Yes, please make sure to open all characters in the game at least once.

**Comment by barabon** [comment]
Thanks for the reply. Ok, I send file. And this problem on all character, on new too. Yes, I open characters and visit a caravan, but - 
![1](https://user-images.githubusercontent.com/50750833/57965964-6332d400-7954-11e9-8d0b-2cfd5c17bf95.png)
And character file
[SaveData.zip](https://github.com/EtienneLamoureux/TQVaultAE/files/3193765/SaveData.zip)
Thanks for your help

**Comment by barabon** [comment]
And maybe help identify the problem, when first start this errors
![2](https://user-images.githubusercontent.com/50750833/57966213-f3bee380-7957-11e9-8cb6-98b65e1cff78.png)
![3](https://user-images.githubusercontent.com/50750833/57966214-f7526a80-7957-11e9-8429-d1fc1ff71e68.png)

**Comment by barabon** [comment]
Up! 
This problem is gone, i writed not true path...fool
Sorry, and thanks
And the solution this problem, maybe anyone will need

Navigate the the installation folder of TQVaultAE
Open TQVaultAE.exe.config in a text editor (i.e. notepad, not Microsoft Word)
Replace the following sections:
<setting name="AutoDetectGamePath" serializeAs="String">
    <value>True</value>
</setting>
...
<setting name="TQITPath" serializeAs="String">
    <value />
</setting>
<setting name="TQPath" serializeAs="String">
    <value />
</setting>
by (replace the path to the correct one for your computer)

<setting name="AutoDetectGamePath" serializeAs="String">
    <value>False</value>
</setting>
...
<setting name="TQITPath" serializeAs="String">
    <value>C:\examplePath\Titan Quest Anniversary Edition</value>
</setting>
<setting name="TQPath" serializeAs="String">
    <value>C:\examplePath\Titan Quest Anniversary Edition</value>
</setting>

**Comment by Ninakoru** [comment]
Is great you got it solved.
