### ISSUE TITLE
 Does not start after updating Atlantis

### ISSUE THREAD

**Issue by ZeroToIerance** [EtienneLamoureux/TQVaultAE#124]
"Could not load Text DB. 

This may be caused by a bad language or game path setting.
Would you like to restart TQVault?"

If you click "yes", then this error will appear indefinitely. If you click "no", then TQVault simply closes. What exactly is the problem?

**Comment by barabon** [comment]
https://github.com/EtienneLamoureux/TQVaultAE

"Troubleshooting and F.A.Q." -> "Q. Error Loading Resources. This may be caused by a bad language or game path setting."
Read and go to steps this guid.
I bad speek in English, but hope you understand

**Comment by EtienneLamoureux** [comment]
Follow the steps in our F.A.Q. as barabon suggested.
