### ISSUE TITLE
Error loading character .chr files

### ISSUE THREAD

**Issue by Hirocker** [EtienneLamoureux/TQVaultAE#126]
I recently went back to TQAE (now vers 2.5) with TQVaultAE  vers 2.6.0, and I find that TQVAE can't read my character .chr files. I even created a new character in the game, and that can't be read either. Attached is the error message I received.
![error-loading](https://user-images.githubusercontent.com/19910017/58255976-255ef280-7d3c-11e9-8dd5-efbbee751119.png)

Thanks for any help; I really miss not being able to use TQVAE.

**Comment by Hirocker** [comment]
I just installed 3.0.0 alpha, and the files can now be read!

**Comment by EtienneLamoureux** [comment]
Glad you got it to work
