### ISSUE TITLE
Error loading in 3.0.0-alpha

### ISSUE THREAD

**Issue by DvornikovSergey** [EtienneLamoureux/TQVaultAE#127]
I get the following error when starting:
![image](https://user-images.githubusercontent.com/15032696/58272839-95f82480-7db9-11e9-8bfc-d9a09e08485c.png)
![image](https://user-images.githubusercontent.com/15032696/58272877-b4f6b680-7db9-11e9-955b-7b27b7b77bbb.png)

Character opened in Atlantis

Thanks

**Comment by Ninakoru** [comment]
Sure is the 3.0 version? That error only happens on old 2.6.

Still the current 3.0 version shows 2.6.0 at the stash window, but has support for this format.

**Comment by DvornikovSergey** [comment]
Hmm, yes, really, I was wrong with the version, thanks!
