### ISSUE TITLE
Adjust the space on the character panel for Ragnarok necklaces

### ISSUE THREAD

**Issue by Sir-Mac** [EtienneLamoureux/TQVaultAE#128]
Hi, Etienne Lamoureux,

as you know, with the Ragnarök expansion, some items, which occupy the slot for necklaces, occupy two spots in width. The screenshot demonstrates, what I am talking about. Could you, please, visually expand the slot for the necklace?

(And if necessary, could you center the one slot necklaces within the new space? So the one slot necklace won't be on left, on right, but on center ... ?)

Sir-Mac
![Necklace space](https://user-images.githubusercontent.com/50591247/58280564-2bd38580-7da1-11e9-87ab-123833d3787b.png)

**Comment by EtienneLamoureux** [comment]
Yes that's feasible

**Comment by EtienneLamoureux** [comment]
I believe Ragnarök necklaces are now only 1 unit wide, in line with other necklaces.

**Comment by Sir-Mac** [comment]
If you will visit any vendor in the North Act, I am sure, you will encounter necklaces 2 units wide .

**Comment by EtienneLamoureux** [comment]
Correct, I thought I saw a 1 cell torc, but they're not all like that.
