### ISSUE TITLE
Jewelry stats not listing correctly

### ISSUE THREAD

**Issue by Pax1sw** [EtienneLamoureux/TQVaultAE#131]
I noticed while moving Newbie jewelry with good stats that the actual in-game stats of the jewelry are greatly reduced when displayed by TQVaultAE. (Example: 10 Dexterity ring in-game displayed as only 5 Dexterity by TQVaultAE, this is true for all jewelry examined so far). Will this jewelry now permanently have the degraded stats when I place it in-game, or will the game read the true stats? Also, how am I supposed to choose jewelry for a character when TQVaultAE isn't displaying its actual in-game stats?

**Comment by Pax1sw** [comment]
Also noticed today, stats on some armor are not displaying properly. My son, who programs, said your program may be pulling base stats from TQ's generic items inventory, rather than reading each item's active game-altered stats.

**Comment by EtienneLamoureux** [comment]
Your second comment is correct, we don't know how the unique item seeds generate the delta on items stats. Be assured that using the vault will now alter the stats of the items.You can see our F.A.Q. for the details.

**Comment by Pax1sw** [comment]
You meant "will NOT alter the stats of the items," right?
