### ISSUE TITLE
Error Parsing 

### ISSUE THREAD

**Issue by barpendoza** [EtienneLamoureux/TQVaultAE#132]
Please Help me 
How to Fix this 

![image](https://user-images.githubusercontent.com/51045093/58379262-a384f880-7fcb-11e9-93f7-be924291d674.png)

![image](https://user-images.githubusercontent.com/51045093/58379257-8819ed80-7fcb-11e9-856d-a4a67141af1f.png)

**Comment by TheOne320** [comment]
You have to use version 3.0.0 because the save format was changed with Atlantis, even for everyone without Atlantis.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by barpendoza** [comment]
> You have to use version 3.0.0 because the save format was changed with Atlantis, even for everyone without Atlantis.
> 
> Sent with [GitHawk](http://githawk.com)

**Comment by barpendoza** [comment]
> You have to use version 3.0.0 because the save format was changed with Atlantis, even for everyone without Atlantis.
> 
> Sent with [GitHawk](http://githawk.com)

ahh ty bro , ill try download it
