### ISSUE TITLE
Remove "unsafe" code block

### ISSUE THREAD

**Issue by EtienneLamoureux** [EtienneLamoureux/TQVaultAE#136]
Unsafe code blocks prevents us from doing a clean "release" build of the project.

See [here](https://github.com/EtienneLamoureux/TQVaultAE/blob/a4270124c2b0cbe7aa50a66d86a1984fb0b74580/src/TQVaultAE.GUI/Program.cs#L139).

**Comment by hguy** [comment]
It's ok to have unsafe code block when it's handle properly.
The problem here is about csproj configuration.
Just check the "Allow unsafe code" property for release.
![UnsafeCodeOk](https://user-images.githubusercontent.com/31834707/59164005-03b98580-8b08-11e9-8208-b60416d4103e.jpg)

**Comment by hguy** [comment]
BTW the project seems to have other problems to make a proper "release build" my instinct tell me that it's related to the mixed C#/C++ references melting pot (Devil, Tooltip). Maybe the .NET Wrapper libs build type ? I'm not sure. I'm actually trying to look at pure .NET alternative for these DLL.

**Comment by EtienneLamoureux** [comment]
Alright then.

And yes, those libraries came from way back when. My search at the time I refactored the project didn't turn anything up, but maybe you'll have more luck.
