### ISSUE TITLE
Could not load Text DB

### ISSUE THREAD

**Issue by MockingBird28** [EtienneLamoureux/TQVaultAE#137]
I got the 3.0.0 Stable version and even with the Alpha i get the same Problem, searched trough the internet and could not find a solution.

**Comment by EtienneLamoureux** [comment]
Could you provide a screenshot of the error of the debug log file?

**Comment by MockingBird28** [comment]
I did a lot of ini editing and such stuff, but nothing helped.

Am Mo., 10. Juni 2019 um 05:09 Uhr schrieb Etienne Lamoureux <
notifications@github.com>:

**Comment by EtienneLamoureux** [comment]
Can you give us a screenshot of the error message?

**Comment by MockingBird28** [comment]
The only thing i can provide is the screen shot i added before

Etienne Lamoureux <notifications@github.com> schrieb am Mo., 10. Juni 2019,
17:52:

**Comment by EtienneLamoureux** [comment]
Ah, I think you may be replying by email. Attachments by email aren't shown in the issue discussion. Could yoy attach your screenshot in github directly?

**Comment by MockingBird28** [comment]
i look it up how, never been on github, that will take some time

Am Mo., 10. Juni 2019 um 18:37 Uhr schrieb Etienne Lamoureux <
notifications@github.com>:

**Comment by MockingBird28** [comment]
![vault text error](https://user-images.githubusercontent.com/51507613/59211212-a1b45b00-8baf-11e9-8f20-b4c6d2ba13e4.png)

i hope this works

**Comment by EtienneLamoureux** [comment]
Thanks

**Comment by EtienneLamoureux** [comment]
Do you play Titan Quest Anniversary Edition through Steam?

**Comment by EtienneLamoureux** [comment]
Also, did you follow the instructions in our F.A.Q. for that problem to the letter? https://github.com/EtienneLamoureux/TQVaultAE/blob/master/README.md#troubleshooting-and-faq

**Comment by MockingBird28** [comment]
Yeah, through steam

**Comment by MockingBird28** [comment]
yes i also followed those instruction but it didnt work.

**Comment by EtienneLamoureux** [comment]
Please try with the latest version.
