### ISSUE TITLE
Error when mouse over Ba'als Hand

### ISSUE THREAD

**Issue by graceoflives** [EtienneLamoureux/TQVaultAE#139]
Hi. I encounter an error when hovering that item. 

![image](https://user-images.githubusercontent.com/20889772/59214038-7138e500-8be0-11e9-8b8b-e2be0d5a57c0.png)

The name tab (under the vault) still show correct name.

**Comment by EtienneLamoureux** [comment]
https://tq-db.net/en/equipment/ba'als-hand

This is a new set item from Atlantis
