### ISSUE TITLE
Feature request: search for requirements

### ISSUE THREAD

**Issue by teodias** [EtienneLamoureux/TQVaultAE#141]
Hi dear developers!

I have multiple big vault files and would be glad to search for requirements like level, int, dex, strength.

Yours,
Teodias

**Comment by EtienneLamoureux** [comment]
Is that the real feature or do you actually want to see what a character can wear?

**Comment by teodias** [comment]
As I think it's quite complicated for the app to know what stats a character has to show what he can wear (if it's easy to implement it sounds great) searching manually for fitting items would be easier?

**Comment by EtienneLamoureux** [comment]
With the work from @s0da72, and if we do #138, it shouldn't be too bad at all.

As of now, I don't think the search supports much in terms of operators.

**Comment by EtienneLamoureux** [comment]
I will discard this in favour of #147
