### ISSUE TITLE
Feature request: sort orders

### ISSUE THREAD

**Issue by teodias** [EtienneLamoureux/TQVaultAE#143]
Hi dear developers,

it would help a lot in many big vault files if we could choose the sort order of the the items by name, level, int, dex, str.

Yours,
Teodias

**Comment by EtienneLamoureux** [comment]
The "sort" button is really more of a compact button. We can discuss what's possible.

**Comment by EtienneLamoureux** [comment]
Or was this request to add sorting options on the search result page?

**Comment by teodias** [comment]
The result table of searching allowed me already sorting by clicking the column headers.
Sorting by level would be fine for planning what to equip soon.

With [#147](https://github.com/EtienneLamoureux/TQVaultAE/issues/147) there might no need for more sort options.

**Comment by EtienneLamoureux** [comment]
Alright, we'll focus on #147 then.
