### ISSUE TITLE
Add item editing option: change prefix/affix

### ISSUE THREAD

**Issue by teodias** [EtienneLamoureux/TQVaultAE#144]
Hi dear developers,

i couldn't find any option/way to change prefixes or suffixes from my found items.
Would be very helpful.

Yours,
Teodias

**Comment by EtienneLamoureux** [comment]
This is something that's been on my radar too. Requirements to make it acceptable: 
- Can only change suffix/affix, not add any.
- Respects items limitation in terms of affix/suffix, i.e. hallowed only on helmets, etc.
- Is considered an item editing option in terms of cheat

**Comment by SergeyDvornikovSetronica** [comment]
Hi, all

Is there any hope that this feature will still be added?

**Comment by EtienneLamoureux** [comment]
It's still on the list. It all depends if someone wants to pick up the task!

**Comment by hguy** [comment]
@teodias @SergeyDvornikovSetronica 
Guys! The new release have it.

@EtienneLamoureux I think you can close this.

**Comment by SergeyDvornikovSetronica** [comment]
Very well. Thanks
