### ISSUE TITLE
item stats wrong

### ISSUE THREAD

**Issue by teodias** [EtienneLamoureux/TQVaultAE#148]
Hello Etienne,

there are sometimes differences in the stats of the items in TQVault and the game.

If I copy an item from Vault to character storage and run the game, the stats are slightly different even the suffix changed sometime.

Please tell me how I can investigate and report more infomration.

Yours,
Teodias

**Comment by EtienneLamoureux** [comment]
See our F.A.Q 

There's unfortunately not much to do about that.
