### ISSUE TITLE
3.0.0 bug, can't see the details of items in vault

### ISSUE THREAD

**Issue by mx8408** [EtienneLamoureux/TQVaultAE#150]
Hi Etienne,

I have used TQVault 2.11 & 2.17 before for Titan request Immortal throne.

Recently I got TQAE and try to use TQVaultAE 3.0.0.0 and I found this bug. When my mouse is over one item, all I can see is the name of this item. I cant see the details of this item, which really bothers me. Here is the screen shot.
![tqvae3 0 0 0 screen shot](https://user-images.githubusercontent.com/23130099/59647454-19463500-9130-11e9-8b49-9dee19f0a5c3.png)

Thank you and wish you a pleasant day.

**Comment by hguy** [comment]
Try the solution on F.A.Q related to "updating from an older version" (VXPLib.dll).

https://github.com/EtienneLamoureux/TQVaultAE#troubleshooting-and-faq

**Comment by EtienneLamoureux** [comment]
Did it fix your problem?

**Comment by Frank2201** [comment]
I was able to reproduce.
Version 3.1.0-alpha

Open TQVaultAE

Hoover the mouse cursor over any item, see the tooltip:
![001](https://user-images.githubusercontent.com/51999422/59969536-b26db500-954f-11e9-9392-1036ca4c03c3.png)

After approx. 50 seconds the tooltip fades away and doesn't reappear, even after hoovering over different items (unfortunately the screenshot didn't capture the mouse cursor):
![002](https://user-images.githubusercontent.com/51999422/59969545-e21cbd00-954f-11e9-8bff-248ddda39563.png)

However, there are some ways to remedy it. Minimize/Restore the window. Or clicking outside TQVault and then return to TQVault (you have to click, so it gets the focus back, **without focus no tooltip** either). 

Personally, I don't think it much of a problem, though. Just write a line somewhere and be done with it.
"TQVaultAE needs focus to show tooltip, after 50 secs tooltip vanishes."

**Comment by EtienneLamoureux** [comment]
@mx8408 Does the tooltip only disappear when you hover over an item for a minute? Did the fix suggested by hguy fix your problem?

**Comment by EtienneLamoureux** [comment]
I'll have to assume https://github.com/EtienneLamoureux/TQVaultAE/issues/150#issuecomment-504648051 fixed it.
