### ISSUE TITLE
TEX magic is invalid

### ISSUE THREAD

**Issue by Frank2201** [EtienneLamoureux/TQVaultAE#155]
With today's update (2.7) one or more charms and/or relics became incompatible with TQVaultAE 3.0.0.

Afte updating Titan Quest to 2.7 I tried to start TQVault 3.0.0 and got the the error message: 

TEX magic is invalid.
This may be caused by a bad language or game path setting.

So I restarted tQVault and disabled the preloading.

When I tried to open the charms & relics vault I got another error message:

Message: TEX magic is invalid.
Stack trace:
  at TQVaultData.BitmapCode.LoadFromTexMemory(Byte[] data, Int32 offset, Int32 count)...

I believe it's easier to just post a sceenshot:
![TEX magic](https://user-images.githubusercontent.com/51999422/59767251-33a02000-92a2-11e9-85bb-ac9e9e73348f.jpg)

FYI: my charms and relics vault contains every single charm and relic there is (all xpacks, all difficulties)

Thank you for your hard work,
wkr,
Frank

edit:
Removing the vault from the folder solves the problem. TQVault starts and preloads as usual.

edit2: found the perpetrator: eitr charm. It's missing its icon.... so that makes it a 2.7 patch issue. Not your fault, sorry for bothering you.

**Comment by Frank2201** [comment]
![Eitr](https://user-images.githubusercontent.com/51999422/59782658-ba62f600-92be-11e9-9f7d-e21188b26163.jpg)

extracted from Titan Quest Anniversary Edition\Resources\XPack2\items.arc. You can see from the filesize that the files are basically "empty" - that's why TQVault isn't able to get a icon from it.

**Comment by EtienneLamoureux** [comment]
We'll let them fix it then. Thanks for reporting.
