### ISSUE TITLE
The Pieces (Primrose Passage Hint Scroll) detail being on the name

### ISSUE THREAD

**Issue by graceoflives** [EtienneLamoureux/TQVaultAE#160]
![image](https://user-images.githubusercontent.com/20889772/59933437-b1675580-9473-11e9-9483-67cfbecbcb9a.png)

**Comment by hguy** [comment]
Is it possible to share a vault file with this item ?

**Comment by graceoflives** [comment]
[Sample.zip](https://github.com/EtienneLamoureux/TQVaultAE/files/3384425/Sample.zip)
