### ISSUE TITLE
3.1.0-alpha: Title bar, completion boni, Game Language

### ISSUE THREAD

**Issue by Frank2201** [EtienneLamoureux/TQVaultAE#161]
Hi,

it seems the option to change the completion boni of artifacts, charms and relics went missing.
edit: editing features are manually enabled, as stated in the readme, of course.

ah, and the title bar still says TQVaultAE 3.0.0.0

And one more: although my game language is set to English, when leaving the the auto option on, TQVaultAE always uses German (my system language). I have to manually select English and leave the auto option off to make it work. However, this dates way back and probably has been previously reported. 

Thank you for your hard work,
wkr,
Frank

**Comment by EtienneLamoureux** [comment]
Downloading a new version resets your local configuration. If you have your old installation, copy the `` file from it to the new folder. If not, open the configuration menu and re-configure the tool.

For the cheats, see [our F.A.Q.](https://github.com/EtienneLamoureux/TQVaultAE#troubleshooting-and-faq), "Q. How to activate TQVaultAE "edition features"? (character edit, copy item, edit item)"

**Comment by Frank2201** [comment]
Well I checked before, and now checked again: 
everything you wrote I did beforehand... as I wrote. I can copy items as usual, I can change the itemseed, too. But I cannot change the completion bonus. That feature seems to gone missing.

**Comment by Frank2201** [comment]
One more thing:
I also copied the former config file over to 3.1.0-alpha, as you suggested, after which TQVaultAE wouldn't even start anymore. 

Instead of starting this line were added to the logfile:
2019-06-22 02:25:58,949 [1] INFO  TQVaultAE.GUI.MainForm [(null)] - TQVaultAE Initialization !

I would assume the config files of previous version are no longer compatible with the most recent one.

**Comment by EtienneLamoureux** [comment]
Ok, thanks for reporting. Re-opening.

**Comment by hguy** [comment]
We cannot reproduce.
Can you try with a brand new installation in a new directory without copying anything from the previous installation ?

**Comment by Frank2201** [comment]
I did...

I extracted the files into a seperate folder. Changed the config file to show item editing features. Enabled the editing features in configuration.

I'll show you... in 3.0.0 with item editing features enabled, you can right-click any artifact, charm or relic... looks like this:
![completion bonus old](https://user-images.githubusercontent.com/51999422/59963822-d225be80-94f8-11e9-8fd0-05846d83317b.png)

in 3.10. with editing features enables, this one feature is missing:
![completion bonus new](https://user-images.githubusercontent.com/51999422/59963836-e964ac00-94f8-11e9-91e1-bb192ae73941.png)
