### ISSUE TITLE
Winforms error or anything

### ISSUE THREAD

**Issue by icefreeze88** [EtienneLamoureux/TQVaultAE#164]
I use TQVaultAE 3.1.0 alpha normally the 1st time. But when i use it next it show this error, and even choose Retry it can use TQVAult right :(
![TQVautAE_3 1 0 Alpha_Error](https://user-images.githubusercontent.com/52094936/59959924-3b520580-94ea-11e9-897c-3afd8adbd42f.png)
![TQVautAE_3 1 0 Alpha_Error](https://user-images.githubusercontent.com/52094936/59959927-46a53100-94ea-11e9-8a57-5d029a2b665f.png)

**Comment by EtienneLamoureux** [comment]
Thanks for reporting. Will be fixed in the next release.
