### ISSUE TITLE
TQVaultAE 3.1.0: Warning about Equipment Block on my character

### ISSUE THREAD

**Issue by Frank2201** [EtienneLamoureux/TQVaultAE#166]
Split from #158
Follow these steps:
1.) start TQVaultAE and disable the preloading in the configuration:
![equipmentblock01](https://user-images.githubusercontent.com/51999422/59968465-a6c3c380-953a-11e9-91b6-90735dacc7de.png)

2.) Exit and restart TQVault

3.) Try to open one of your characters. You'll get this error:
![equipmentblock02](https://user-images.githubusercontent.com/51999422/59968480-c955dc80-953a-11e9-8dca-e94bc46c737f.png)

4.) Click ok. The equipment slots and the hero display both are empty.
![equipmentblock03](https://user-images.githubusercontent.com/51999422/59968485-df639d00-953a-11e9-9457-15d1ee88600b.png)

5.) From here on out your character will not be saved by TQVaultAE, no matter how many items you add or remove from it. (Which is a good thing, this way the error does not find a way into the game)

**Comment by EtienneLamoureux** [comment]
Thanks for the detailed report.
