### ISSUE TITLE
Prepare release 3.1.0

### ISSUE THREAD

**Issue by EtienneLamoureux** [EtienneLamoureux/TQVaultAE#170]
- [x] Update changelog
- [x] Update readme
  - Contributor section
  - "Stable release" badge
  - Screen capture
  - Features: new cheats
- [x] Cut the release, build, prepare the tag and link archives
- [x] Advertise release
  - Reddit
  - Steam page
  - Discord

**Comment by Trejanus** [comment]
When I start TQVaultae 3.1.0 a message appears:
"Could not load Text DB". 
![obraz](https://user-images.githubusercontent.com/52220165/60134029-e559b800-979e-11e9-8346-145b3432b37a.png)
I have TQAE Atlamntis v.2.7 - current version on Steam.

What is the answer? Why do you publish the wrong version with the description that it allegedly works with TQAE Atlantis 2.7?
