### ISSUE TITLE
How do I configure TQVaultAE to avoid "Could not load Text DB"?

### ISSUE THREAD

**Issue by EtienneLamoureux** [EtienneLamoureux/TQVaultAE#172]
When I start TQVaultae 3.1.0 a message appears:
"Could not load Text DB". 
![obraz](https://user-images.githubusercontent.com/52220165/60134029-e559b800-979e-11e9-8346-145b3432b37a.png)
I have TQAE Atlamntis v.2.7 - current version on Steam.

What is the answer? Why do you publish the wrong version with the description that it allegedly works with TQAE Atlantis 2.7?

_Originally posted by @Trejanus in https://github.com/EtienneLamoureux/TQVaultAE/issues/170#issuecomment-505625469_

**Comment by EtienneLamoureux** [comment]
Hello, thanks for reporting your problem.

Please note that the TQVaultAE community of volunteer developers do not claim anything, as [per the licence of this product](https://github.com/EtienneLamoureux/TQVaultAE/blob/master/LICENSE#L15). The current release of the product is an alpha release, which may contain known bugs, as [per our disclaimer](https://github.com/EtienneLamoureux/TQVaultAE#installation) in the installation section.

Kindly wait for the upcoming release for a fix.

**Comment by Trejanus** [comment]
It is obvious. I only reported a problem. I do not think I'm the first to face this problem. I am waiting for a solution and I thank the authors for their work so far :-)

**Comment by Frank2201** [comment]
You can reproduce the error by manually entering an invalid game path. However, that's not a bug, but simply a wrong config. Solution: reinstall TQVaultAE (or manually edit the config, I guess)
![Unbenannt](https://user-images.githubusercontent.com/51999422/60167039-934a7e00-9802-11e9-96c0-4a45df50531f.png)


Unless, of course, that message is used for other errors as well.

**Comment by EtienneLamoureux** [comment]
Check if the fix documented in [our FAQ](https://github.com/EtienneLamoureux/TQVaultAE/blob/master/README.md#troubleshooting-and-faq) under "Q. Error Loading Resources. This may be caused by a bad language or game path setting." fixes your problem.
