### ISSUE TITLE
Crashed when I switched to another character in 3.1.0alpha

### ISSUE THREAD

**Issue by doomsdayer** [EtienneLamoureux/TQVaultAE#173]
as the title describes
![aaa](https://user-images.githubusercontent.com/3272795/60271828-9ee29580-9925-11e9-853b-675148f03e54.png)

**Comment by EtienneLamoureux** [comment]
Has that character selected a mastery yet?

**Comment by doomsdayer** [comment]
> Has that character selected a mastery yet? If not, do it to fix the problem. We'll have a fix for it in the new release.
> 
> Duplicate of #164

Yes that's it. It was a vault charactor.
