### ISSUE TITLE
Fix rare error when searching with complex query and "load all" set to false

### ISSUE THREAD

**Issue by icefreeze88** [EtienneLamoureux/TQVaultAE#175]
Hello guys!
First of all, thank you for your work since the first TQVault to now.

I just download TQVaultAE 3.1.0 ( .zip version) and extracted, config both .config.dll and .exe file then use TQVault. After search and get a results, this error notice box displayed:
![TQVaultAE_3 1 0_Error](https://user-images.githubusercontent.com/52094936/60309253-18ef3a80-9977-11e9-8f34-6033a0942c3e.png)

And did you change the location of tqvault data files? Because i must copy all my tqvault data file (which in the location of tqvault data files from all previous tqvault versions, "C:\Users\Admin\Documents\My Games\Titan Quest\TQVaultData") into the TQVaultAE 3.1.0 folder to make it use my vaults before.

**Comment by EtienneLamoureux** [comment]
1. What was your search query?
2. You can configure the vault files location on the top left of the configuration panel.

**Comment by icefreeze88** [comment]
> 1. What was your search query?
> 2. You can configure the vault files location on the top left of the configuration panel.

1. The search query in the screenshot is "venomous serpent spear of the tinkerer".
Sometime it happen the same issue with several search querries.
2. I already config there, but that's seem vault location, not vaut data files location because just with this 3.1.0 version, i must copy all vault file into it instead let tqvault using vault file in old vault file location.

**Comment by hguy** [comment]
> I just download TQVaultAE 3.1.0 ( .zip version) and extracted, config both .config.dll and .exe file then use TQVault. After search and get a results, this error notice box displayed:

Why are you doing a partial extraction ?
By looking at your picture your lucky that the vault just launch.
Make a proper full installation in a new directory and adjust the settings if the default values need adjustment to your vault files location.

**Comment by icefreeze88** [comment]
> > I just download TQVaultAE 3.1.0 ( .zip version) and extracted, config both .config.dll and .exe file then use TQVault. After search and get a results, this error notice box displayed:
> 
> Why are you doing a partial extraction ?
> By looking at your picture your lucky that the vault just launch.
> Make a proper full installation in a new directory and change the settings if the default values need adjustment to your vault files location.

I always using .zip version with previous TQVaultAE version and its all work well.
I change the setting in config file before i using TQVault.

**Comment by EtienneLamoureux** [comment]
Can you try on a full fresh install of the latest version? We did some work around dependencies and solution setup.

**Comment by icefreeze88** [comment]
> Can you try on a full fresh install of the latest version? We did some work around dependencies and solution setup.

The .exe file?
I just installed it and config to recognize game and vault path. TQVault can recognize the vault data file in the default vault data location ( in My Documents/..... ), but still no help with search function.
- When Disable "Preload all vault,...", TQVault search can't work like before with the same querries i used to use to search (like " @armor | $rare | #all skill | #recharge", i use this querries to search my Hallow..Rumination).
- If i check the "Preload all vault..", this error notice display:
![image](https://user-images.githubusercontent.com/52094936/60482362-5b887e00-9cbb-11e9-80e5-31758f452146.png)

**Comment by hguy** [comment]
> 
> 
> > > I just download TQVaultAE 3.1.0 ( .zip version) and extracted, config both .config.dll and .exe file then use TQVault. After search and get a results, this error notice box displayed:
> > 
> > 
> > Why are you doing a partial extraction ?
> > By looking at your picture your lucky that the vault just launch.
> > Make a proper full installation in a new directory and change the settings if the default values need adjustment to your vault files location.
> 
> I always using .zip version with previous TQVaultAE version and its all work well.
> I change the setting in config file before i using TQVault.
> And of course, i try to using installed version before i make this report.

1. It's not about the zip, it's about extracting the **full content** (not some file) of the zip into a **new empty directory** and running the program from here.
2. Can you zip your /logging/ subdirectory and join it here ?
3. Your last picture display an OutOfMemory on resource file reading (extracting pictures from it). Is your system memory overload ?

The last picture

**Comment by icefreeze88** [comment]
> > > > I just download TQVaultAE 3.1.0 ( .zip version) and extracted, config both .config.dll and .exe file then use TQVault. After search and get a results, this error notice box displayed:
> > > 
> > > 
> > > Why are you doing a partial extraction ?
> > > By looking at your picture your lucky that the vault just launch.
> > > Make a proper full installation in a new directory and change the settings if the default values need adjustment to your vault files location.
> > 
> > 
> > I always using .zip version with previous TQVaultAE version and its all work well.
> > I change the setting in config file before i using TQVault.
> > And of course, i try to using installed version before i make this report.
> 
> 1. It's not about the zip, it's about extracting the **full content** (not some file) of the zip into a **new empty directory** and running the program from here.
> 2. Can you zip your /logging/ subdirectory and join it here ?
> 3. Your last picture display an OutOfMemory on resource file reading (extracting pictures from it). Is your system memory overload ?

1. I always extract all it to new folder. Why do i just extract some of them but not all?
2. What subdirectory? TQVaultAE folder? As i said above.
3. My system Ram is 12GB, i always run webs with game, tqvault the same time at it just use like 5x% ram maximum. Its never have any issue from previous Atlantis tqvault.

**Comment by hguy** [comment]
Do you have .NET Framework 4.7.2 installed ?
https://support.microsoft.com/fr-fr/help/4054530/microsoft-net-framework-4-7-2-offline-installer-for-windows

**Comment by icefreeze88** [comment]
My system already installed it ( Windows 10 x64 v1903).

**Comment by zelo86** [comment]
I'd like to say that the same happens to me too.
TQ Vault works fine for me except the search function. When I try to use it, I get an error message (see image attached)
I'm on Win 10 Pro 1903 x64.
It only happened when I upgraded to TQ Vault AE 3.3.0 from 3.2.1 where the search worked fine..
![Immagine](https://user-images.githubusercontent.com/56092244/66076704-aa65de00-e55e-11e9-8a38-78ab40e2a7c4.jpg)

I'll wait patiently for a fix, because this tool let me enjoy the game 2 times more!

**Comment by EtienneLamoureux** [comment]
Hi @zelo86, his is actually #233 

Thanks for reporting!
