### ISSUE TITLE
How do I enable Character Edit/Copy item?

### ISSUE THREAD

**Issue by CyberNinja04** [EtienneLamoureux/TQVaultAE#176]
I changed the TQVault.Config.dll XML file like shown in the tutorial to make those values true but even then it still loads and you cannot character edit or copy items anymore, How do you get it to work or is this just a big thatll get fixed soon?

**Comment by EtienneLamoureux** [comment]
1. Edit the config file as described.in our FAQ 
2. Save and close the config file
3. Open TQVaultAE 
4. Open the configuration menu using the top left button
5. Enable the cheats you want
   - If the cheat options don't appear in the configuration menu, it means the config file was not edited correctly.

**Comment by CyberNinja04** [comment]
> 1. Edit the config file as described in our FAQ (the AllowCheats key)
> 2. Save and close the config file
> 3. Open TQVaultAE
> 4. Open the configuration menu using the top left button
> 5. Enable the cheats you want
>    
>    * If the cheat options don't appear in the configuration menu, it means the config file was not edited correctly.

That FAQ is missing out on one key part, you need to edit TQVaultAE as well as TQVaultAE.config then itll show, so its fixed now, got it to work

**Comment by EtienneLamoureux** [comment]
Glad you got it working. 

I'll review the documentation.
