### ISSUE TITLE
Fix cyrillic symbols support in the drop-down menus

### ISSUE THREAD

**Issue by Rewerson** [EtienneLamoureux/TQVaultAE#177]
Works fine in 3.0.0, but broken in newer versions.
![cyr](https://user-images.githubusercontent.com/5984863/60380929-e49e7b80-9a55-11e9-9fec-2862f0de70c7.png)

**Comment by EtienneLamoureux** [comment]
Thanks for reporting

**Comment by EtienneLamoureux** [comment]
@hguy @epinter I remember some of the recent refactoring impacting font support.

**Comment by hguy** [comment]
@Rewerson Can you zip some of your vault files and  join it here ?

**Comment by hguy** [comment]
@Rewerson can you create a new vault file with cyrilic chars and check if the problem persist for that new file ?

**Comment by Rewerson** [comment]
@hguy yes, I can upload in a couple of hours. But probles is not in the vaults. In right drop-down phrase "Выберите персонажа", which in English is "Select character" although shows incorrect in list.
Fonts of items in selector and of selected item are different, it may help you.

**Comment by hguy** [comment]
The fact is, in the code the vault combobox font is well defined and that part is unchange.
I have to look at data level and reproduce the problem on my PC (filename encoding, etc...)

**Comment by Rewerson** [comment]
@hguy here is sample of vault in the attached archive. And on the new screen is that vault from the archive selected. As I said before, when selected, item name is readable. Although, please notice right drop-down, first item is "Выберите персонажа" (Select character), which on my first screen seems normal, when is selected. And that item of list is not connected with any filename, it's part of program itself.
![123](https://user-images.githubusercontent.com/5984863/60451495-dbb7d080-9c34-11e9-8453-f4b30873f911.png)

[TQVaultData.zip](https://github.com/EtienneLamoureux/TQVaultAE/files/3346534/TQVaultData.zip)
