### ISSUE TITLE
Render all stash's tabs labels in the same font size

### ISSUE THREAD

**Issue by graceoflives** [EtienneLamoureux/TQVaultAE#179]
![image](https://user-images.githubusercontent.com/20889772/60381596-753e8100-9a81-11e9-9a6d-1027ebeb6be4.png)
Label Character uses default font instead of the font for select
![image](https://user-images.githubusercontent.com/20889772/60381606-8a1b1480-9a81-11e9-942b-41c081afd1b5.png)
"Transfer Area" and "Storage Area" use different font with the other two.

**Comment by EtienneLamoureux** [comment]
I believe this is an issue with text length and padding.

**Comment by hguy** [comment]
@EtienneLamoureux You may be right but i think it's middle ground decision when multi language support have been added.
Depending language, text length may change a lot.

**Comment by EtienneLamoureux** [comment]
Fair enough. It's purely cosmetic anyway. We'll drop it as recalculating font size per language is not worth the effort.

**Comment by hguy** [comment]
@EtienneLamoureux Alternatively the solution could be to use explicit icons instead of text and put translated text when hovering in the notification placeholder. That technique could solve all the problems of UI multi-language text length.
We just need a bit of pixel search, work and smartness that satisfy the look & feel of TQVault.

**Comment by hguy** [comment]
We already have chest icons for "Vault" label "Transfer Area" and "Storage Area" (using pictures from splash screen or mainform header).
We can use custom icon made of Relic & Charm game icons for the relic stash.
The label for player combobox could be a pretty game Helmet icon.
A bit of code and that's it !

**Comment by EtienneLamoureux** [comment]
True, we could log it as a low priority refactor.
