### ISSUE TITLE
.net compatibility?

### ISSUE THREAD

**Issue by DoomSquirter** [EtienneLamoureux/TQVaultAE#181]
I'll assume answer is no, but I'll ask regardless.

any way to make this backwards compat with older .net versions?  I haven't updated my win10 in a long while and have avoided all the milestone releases.  Figure I will anyways but need to back everything up first after last year's fiasco with the october(?) milestone.

**Comment by EtienneLamoureux** [comment]
We recently spent considerable efforts, spear headed by @hguy to port TQVaultAE tovtge newest SDK.

**Comment by DoomSquirter** [comment]
ah ok, well I guess I'll wait to update my machine then.  I find it pretty silly that .net availability is directly linked to some milestone upgrade.  I appreciate you replying tho.  thanks very much.

**Comment by hguy** [comment]
@DoomSquirter You need .NET Framework 4.7.2+

**Comment by DoomSquirter** [comment]
yeah, I'm aware.  it's why I created the issue here.  I literally haven't installed a milestone since original install.  my hate for win10 goes deep and is even worse after this whole thing.

**Comment by hguy** [comment]
the problem here is "win10 deep hating" is not a bug :)

**Comment by DoomSquirter** [comment]
nope, it's a feature :)
