### ISSUE TITLE
Is changing character's name possible?

### ISSUE THREAD

**Issue by Pannathrax** [EtienneLamoureux/TQVaultAE#182]
I have enable the cheat in the configuration, in the character edit function i am able to change the stats, is it possible to add a function to change character's name? Or is it already available and need to edit other entry in the config?

**Comment by EtienneLamoureux** [comment]
Not possible at the moment

**Comment by EtienneLamoureux** [comment]
What you can do though is use @epinter's https://github.com/epinter/tqrespec and use the "Save as..." button to copy your character under a new name, and delete the old one.
