### ISSUE TITLE
Fix missing items in search results

### ISSUE THREAD

**Issue by icefreeze88** [EtienneLamoureux/TQVaultAE#183]
Hello guy!
I just notice the issue when search some querries, TQVaultAE v3.1.0 doesn't show all the results, just show some of that result which equipped or in stash of some character, other results items which fit the search querries but store in TQVault doesn't show in search results box.

P/s: And now search function can't find the items that i used to find by it with previous version before.

**Comment by EtienneLamoureux** [comment]
Do you have the "load all characters" option unchecked

**Comment by icefreeze88** [comment]
> Do you have the "load all characters" option unchecked?

Yes, it unchecked. If i checked that option, it will appear the "Winforms error" and some other error notice box that i reported you in previous issue reported.

**Comment by hguy** [comment]
@EtienneLamoureux the search feature has been totally rewritten from the ground up since then. It's not relevant to keep this isssue opened.
