### ISSUE TITLE
TQVAULTAE 3.1.0 - how does the ITEM EDIT function work? (cheat)

### ISSUE THREAD

**Issue by DZeg1** [EtienneLamoureux/TQVaultAE#184]
Hey, thank you for all the effort you've done in creating the TQ Vault!

One thing that bothers me, is that when I change the values in both "TQVaultAE.exe.config" and "TQVaultAE.Config.dll.config" (in the AllowCheat section - from False to True), I don't see any change within the program.

Is changing the Item Seed - one an only option to edit an item? Or you can actually alter the characters withing the Suffixes/Prefixes - e.g. Changing the element (Ice/Fire/Thunder) and the Numeric Values? If so, then how is that achieved.

Read the forum thoroughly, still it's a no-go for me.
Sorry for bothering and best of luck!

**Comment by EtienneLamoureux** [comment]
Once the AllowCheats has been set to true in the XML, you can open the configuration menu using the button on the top and activate the cheats.you want.

Our documentation is all [here](https://github.com/EtienneLamoureux/TQVaultAE/blob/master/README.md#features).
