### ISSUE TITLE
New interface language: chinese

### ISSUE THREAD

**Issue by doomsdayer** [EtienneLamoureux/TQVaultAE#185]
We are looking forward for it~

**Comment by EtienneLamoureux** [comment]
All we'd need is some translation done by somebody fluent in the language. We have some language files that we could setup for someone willing to help.

Of course the item names and descriptions would only be in Chinese if the original game supports it to, I haven't verified myself.

**Comment by doomsdayer** [comment]
> All we'd need is some translation done by somebody fluent in the language. We have some language files that we could setup for someone willing to help.
> 
> ~Of course the item names and descriptions would only be in Chinese if the original game supports it to, I haven't verified myself.~ Apparently they do have it. So we'd just need a volunteer!

As a Chinese TQ zealot player who can speak fluent English, I think I am the most suitable guy😀
Will my work be translating the words of interface to Chinese?

**Comment by EtienneLamoureux** [comment]
If you'd like to help, yes! It's not that bad, I'll put something together this week to guide you through, but the amount will be similar to [this](https://github.com/EtienneLamoureux/TQVaultAE/blob/41c190be6152a5ff3cea8b38864a189f2f1a29bb/src/TQVaultAE.Presentation/Resources.fr.resx).

**Comment by doomsdayer** [comment]
I've got it. I suppose I will complete a Resources.cn.resx this weekend and create a pr~

**Comment by Klauhs** [comment]
How do I translate? What programs to use? I would like to translate it into Brazilian Portuguese.
Thank you.

**Comment by rawhostel** [comment]
Love to help too, if still needed.

**Comment by EtienneLamoureux** [comment]
@rawhostel Of course! Instructions are detailed [here](https://github.com/EtienneLamoureux/TQVaultAE/issues/346#issuecomment-647145849).

**Comment by rawhostel** [comment]
[Resources.cn.zip](https://github.com/EtienneLamoureux/TQVaultAE/files/5215515/Resources.cn.zip)
Finish translating and hope it satisfied the requirement. Please let me know if you have trouble accessing the content of this file or there is any missing translation. Happy to make any further changes as needed. 

Can't wait to use TQVaultAE in Chinese version!

**Comment by EtienneLamoureux** [comment]
I'll start integrating the new resource file for the next release. Hopefully there won't be too many issues with the fonts.

**Comment by AirsQ** [comment]
@rawhostel，你好，我现在也在做TQV的汉化处理，我已经有了成果，打算给作者提交一版。但是我的英语不是特别好，UI翻译的时候用了很多机器翻译，我能用一下你翻译的资源文件吗
Hello, I'm also doing Chinese localization of TQV now. I've made achievements and plan to submit a version to the author. But my English is not very good. I use a lot of machine translation in UI translation. Can I use the resource files you translated？
![1647085238(1)](https://user-images.githubusercontent.com/30925614/158043220-d85408c4-5625-4841-8844-75980926eae7.jpg)
？
![1647085268(1)](https://user-images.githubusercontent.com/30925614/158043222-41a0abdc-6a0d-46da-8370-983ebc0d02dc.jpg)
![1647085301(1)](https://user-images.githubusercontent.com/30925614/158043223-d4f0568d-4138-41ec-9f53-26f400258303.jpg)
![1647085215(1)](https://user-images.githubusercontent.com/30925614/158043224-a2b7e73e-23bb-4b23-aedf-ea2c88422313.jpg)

**Comment by AirsQ** [comment]
> [Resources.cn.zip](https://github.com/EtienneLamoureux/TQVaultAE/files/5215515/Resources.cn.zip) Finish translating and hope it satisfied the requirement. Please let me know if you have trouble accessing the content of this file or there is any missing translation. Happy to make any further changes as needed.
> 
> Can't wait to use TQVaultAE in Chinese version!

@rawhostel，你好，我现在也在做TQV的汉化处理，我已经有了成果，打算给作者提交一版。但是我的英语不是特别好，翻译UI的时候用了很多机器翻译，我能用一下你翻译的资源文件吗？
Hello, I'm also doing Chinese localization of TQV now. I've made achievements and plan to submit a version to the author. But my English is not very good. I use a lot of machine translation in UI translation. Can I use the resource files you translated？
![1647085301(1)](https://user-images.githubusercontent.com/30925614/158043737-19ee3fae-9264-4306-9e82-46039c510d47.jpg)
![1647085238(1)](https://user-images.githubusercontent.com/30925614/158043739-0c591105-147f-43b1-b601-90e3d0fa29df.jpg)
![1647085268(1)](https://user-images.githubusercontent.com/30925614/158043740-3f704ec8-e9f4-4ef5-8eb1-7107917c9e36.jpg)
![1647077917(1)](https://user-images.githubusercontent.com/30925614/158043741-89d6cee2-a86d-4739-bcc5-22253805efaa.jpg)

**Comment by EtienneLamoureux** [comment]
@AirsQ Contributions to this project are open-source: Feel free to use them and submit a pull request!

**Comment by AirsQ** [comment]
> @AirsQ Contributions to this project are open-source: Feel free to use them and submit a pull request!

I understand.
