### ISSUE TITLE
Allow mastery respec

### ISSUE THREAD

**Issue by CyberNinja04** [EtienneLamoureux/TQVaultAE#188]
Would it be possible to allow Mastery/Skill respecs  in the next iteration of the Vault? like just being able to Reset First mastery and reset second mastery and put back all the skill points you've earned over levels and quests for u to do ingame , just a simple respec so you only reset only what skill points you have

**Comment by epinter** [comment]
I'm about to release TQRespec with this feature.

**Comment by CyberNinja04** [comment]
> I'm about to release TQRespec with this feature.

Well I hope EtienneLamoureux can put it in the TQ Vault cuz TQ Respec isnt usable/accessible to everyone but TQ Vault is usable to everyone

**Comment by epinter** [comment]
> > I'm about to release TQRespec with this feature.
> 
> Well I hope EtienneLamoureux can put it in the TQ Vault cuz TQ Respec isnt usable/accessible to everyone but TQ Vault is usable to everyone

Disrespectiful people like you don't deserve the attention you received from me days ago (two times, here and on other project's issue). 

Please stop spamming with useless and non sense comments. Questions, opinions and any other information about projects not related to TQVaultAE should only be posted here if helps other users or developers. Don't make others waste time like you have done to me, limit yourself to contribute to the project, like you have done when you opened this issue.

Thanks.

**Comment by EtienneLamoureux** [comment]
Alright, first of all I'm far from the only one contributing to this project (quite the opposite lately), and all the members of the TQ modding and tooling community have my thanks for keeping this project alive.

The feature request is genuine, but please keep in mind that TQVaultAe is primary a storage tool and as such, storage and search feature might be prioritized over character edition features.

**Comment by EtienneLamoureux** [comment]
This feature is implemented by [another maintained community tool](https://github.com/epinter/tqrespec)
