### ISSUE TITLE
Error(S) using TQ Vault

### ISSUE THREAD

**Issue by Knopy** [EtienneLamoureux/TQVaultAE#189]
Hello,

first of all thanks for your work!

TQ vault worked fine for a while. Somewhere in Ragnaroc dlc i got these messages, they wont stop.
Regarding the second screenshot, it only opens, when i ignore the program and exit from the loading screen. it would infinitload otherwise.

If i remember correctly it started with an epic item, kind of red ish. wasnt able to hover over it. It may or may not be the Baáls hand thing, im not sure. 

![tq1](https://user-images.githubusercontent.com/52590266/60751262-04342780-9fb3-11e9-9bf8-60b9d6397ab9.PNG)
![tq2](https://user-images.githubusercontent.com/52590266/60751263-05655480-9fb3-11e9-92bd-2b2b8caac721.PNG)
![tq3](https://user-images.githubusercontent.com/52590266/60751264-06968180-9fb3-11e9-991e-325fea48a9d3.PNG)
![tq4](https://user-images.githubusercontent.com/52590266/60751265-07c7ae80-9fb3-11e9-87d8-f6ee7703b37f.PNG)

**Comment by hguy** [comment]
Theses are old bugs. Download the last release.

**Comment by EtienneLamoureux** [comment]
[Please update](https://github.com/EtienneLamoureux/TQVaultAE/releases/tag/3.1.0) to fix your problem.
