### ISSUE TITLE
Vault path was not found

### ISSUE THREAD

**Issue by Zeruke** [EtienneLamoureux/TQVaultAE#196]
Upon attempting to launch the program it fails providing the following 

![](http://puu.sh/DS53j/7454a516df.png)

after which it opens this dialog box 

![](http://puu.sh/DS52a/6dde46fd96.png)
Then it attempts to open the microsoft registry server. i have been declining this dialog until i know more about the issue. any ideas about what might cause this to happen? i haven't found any similar issues in the issue area or in the F.A.Q

**Comment by EtienneLamoureux** [comment]
Can you try with the latest release please? 3.1.1

**Comment by Zeruke** [comment]
This was with the latest release. i just joined the tq community and have installed this for the first time ever on my system. Here is a screenshot of the downloads as proof.

![](http://puu.sh/DS6I3/aa87fd592c.png)

**Comment by hguy** [comment]
The stacktrace tells us that the exception occur in the TTLib constructors.
It's a VXPLib registering problem.
Looks like the VXPLib registering procedure didn't work properly.
Can you try FAQ solution `After updating from an older version of TQVault (2.18 or older), the new program won't start.` ?

**Comment by Zeruke** [comment]
That seems to have fixed it. Thank you very much everyone!
