### ISSUE TITLE
Wrath of Jǫrmungandr inconsistence font

### ISSUE THREAD

**Issue by graceoflives** [EtienneLamoureux/TQVaultAE#197]
![image](https://user-images.githubusercontent.com/20889772/61168468-da619e80-a578-11e9-96c6-b9e1a5a80a08.png)

**Comment by EtienneLamoureux** [comment]
We'll be adding new font options in 3.2.0. You'll be able to pick and chose which one renders better for the language and items you use the most. It's very hard to find fonts that have proper support for everything, considering the game now has items with foreign characters.

**Comment by EtienneLamoureux** [comment]
Fixed by #194
