### ISSUE TITLE
Fix the missing text for "Master Mind" in "Tiresias' Guide" description

### ISSUE THREAD

**Issue by graceoflives** [EtienneLamoureux/TQVaultAE#198]
TQVault display:
![image](https://user-images.githubusercontent.com/20889772/61168494-34fafa80-a579-11e9-9f58-dfbd636756b7.png)
In-game:
![image](https://user-images.githubusercontent.com/20889772/61168520-860aee80-a579-11e9-9dc3-e2349d4587d2.png)

**Comment by EtienneLamoureux** [comment]
Most likely a missing string in the resource file.

**Comment by hguy** [comment]
@EtienneLamoureux this should be closed
