### ISSUE TITLE
Fix the displayed description of "Falcon Cape"

### ISSUE THREAD

**Issue by graceoflives** [EtienneLamoureux/TQVaultAE#200]
TQVault:
![image](https://user-images.githubusercontent.com/20889772/61168558-37118900-a57a-11e9-9132-923bae75bfcf.png)
In-game:
![image](https://user-images.githubusercontent.com/20889772/61168572-73dd8000-a57a-11e9-9c03-a7cb61d0d62a.png)

**Comment by hguy** [comment]
@graceoflives can you share the item ?
