### ISSUE TITLE
Show the name of character with certain issues

### ISSUE THREAD

**Issue by o0oGnas** [EtienneLamoureux/TQVaultAE#201]
It would be much more helpful to show the name of the character when there's an issue with said character. For example 
![image](https://user-images.githubusercontent.com/43918999/61173361-92e80c00-a592-11e9-82a9-c3b138a09e75.png)

**Comment by EtienneLamoureux** [comment]
For custom maps/workshop maps characters correct?

**Comment by xNinjaRose** [comment]
Its not so much an issue/error, I've gotten that exact Cannot find Stash file and it was when it tried to load a new character who I haven't touched storage yet(thus no data in my save for it) , plus it should be the active character chosen in TQ Vault, which caused the popup to show up

**Comment by EtienneLamoureux** [comment]
Yeah, this isn't a bug per say, but knowing which characters cause popups would be useful.

**Comment by Klauhs** [comment]
Hello
Were you able to solve this problem?
I have this problem.
