### ISSUE TITLE
Invalidate tooltip cache when editing an item

### ISSUE THREAD

**Issue by vandeath** [EtienneLamoureux/TQVaultAE#202]
Worked with the 3.1.0 but not any more with 3.2.0
When I change the completion bonus for a charm, the result does not appear. I have to close and run again the application to see the changement.

I like this application, good job !

**Comment by hguy** [comment]
Looks like cache persistence.
We should invalidate the tooltip cache and item data cache for this specific item when item edition actions occurs.
