### ISSUE TITLE
Tooltip description not the same that in game

### ISSUE THREAD

**Issue by vandeath** [EtienneLamoureux/TQVaultAE#203]
Hello,
Look at the joined captured images :
![2019-07-17 12_04_04-TQVaultAE 3 2 0 0](https://user-images.githubusercontent.com/52935776/61377435-7eae5280-a8a3-11e9-9987-3a9f0a2d638d.png)
![2019-07-17 12_07_55-Titan Quest Anniversary Edition Enhanced](https://user-images.githubusercontent.com/52935776/61377444-82da7000-a8a3-11e9-9d11-c0c7838c6cde.png)
I have got 2 others shields called "Vengeance...", same problem.

**Comment by hguy** [comment]
This is because Prefix/Suffix/Quality/Style have been added to the item name in the tooltype.
Is it a problem ?

**Comment by vandeath** [comment]
No it's not the problem about the item name.
There are some other differences about tooltip informations in game :
- "Block recovery" not present in TQVault
- +xx Intelligence : 25 in TQVault --> 26 in game
- "15.0% Chance of xx Fire Retaliation" : 35 in TQVault --> 30 in game
But TQVault gives better information like the time of Recharge, not present in game.

This is not a big problem.

**Comment by hguy** [comment]
An alternative could be to display the full qualified name on "detailed view mode" only (Left-Alt)

**Comment by vandeath** [comment]
No it's not the problem about the item name.
There are some other differences about tooltip informations in game :
- "Block recovery" not present in TQVault
- +xx Intelligence : 25 in TQVault --> 26 in game
- "15.0% Chance of xx Fire Retaliation" : 35 in TQVault --> 30 in game
But TQVault gives better information like the time of Recharge, not present in game.

This is not a big problem. 

> 
> 
> An alternative could be to display the full qualified name on "detailed view mode" only (Left-Alt)

**Comment by vandeath** [comment]
> 
> 
> An alternative could be to display the full qualified name on "detailed view mode" only (Left-Alt)

**Comment by hguy** [comment]
Hi @QStormDS ,

This is because TQVault display the "base value" of the attribute.
In game, that "base value" is pseudo-randomized from the "Item-seed" value.
TQVault doesn't know that pseudo-random logic, therefore it can't compute back the exact same value.
