### ISSUE TITLE
Tooltips flickering

### ISSUE THREAD

**Issue by teodias** [EtienneLamoureux/TQVaultAE#205]
Hi,

the tooltips in 3.2.0 are flickering several seconds until they show the popup.

Cheers,
Teodias

**Comment by hguy** [comment]
The tooltip can flicker when the mouse pointer in at the edge of bag buttons or items.
moving the cursor back to the center of the surface fix it.

**Comment by hguy** [comment]
the only other known case scenario for tooltip flickering is for bloated relic stash **when you have a second screen with different resolution**.
The tooltip try to display on the right side of the button but for some reason it's positioning in the middle so it flicker.
_The actual workaround is to move the main form a bit on the left to give more space on the right side of the button._
