### ISSUE TITLE
Artifact recipes icon missing

### ISSUE THREAD

**Issue by lvlvy** [EtienneLamoureux/TQVaultAE#208]
Good day,

I am having a problem with artifacts and their recipes icons. Also when I am trying to make an artifact I get this:
![image](https://user-images.githubusercontent.com/33087111/61892212-f0c20f80-af13-11e9-9096-414e23941271.png)

And recipes/artifacts look like:
![TQVaultAE 3 2 0 0 2019-07-25 19_43_32](https://user-images.githubusercontent.com/33087111/61892558-b73dd400-af14-11e9-814d-08259c24cdab.png)

**Comment by hguy** [comment]
Is this a fresh install from an empty directory ?

**Comment by lvlvy** [comment]
I reinstalled windows. After that I installed titan quest and pasted my saves - "My games" folder from previous windows and installed TQvault

**Comment by hguy** [comment]
What is your installed game version  (TQ, TQIT or TQAE) ?

**Comment by lvlvy** [comment]
TQAE with all dlcs

**Comment by hguy** [comment]
can you share a zip of your TQVault directory ?

**Comment by lvlvy** [comment]
Sure
[TQVaultData.zip](https://github.com/EtienneLamoureux/TQVaultAE/files/3438045/TQVaultData.zip)

**Comment by lvlvy** [comment]
I'm adding some interesting things (found an item with no icon either)
![TQVaultAE 3 2 0 0 2019-07-27 13_15_11](https://user-images.githubusercontent.com/33087111/61993211-1f093180-b071-11e9-85b9-e6a5329d82cb.png)

Letters too?
![TQVaultAE 3 2 0 0 2019-07-27 13_16_41](https://user-images.githubusercontent.com/33087111/61993347-47922b00-b073-11e9-9404-45d54409582e.png)

**Comment by hguy** [comment]
> 
> 
> Sure
> [TQVaultData.zip](https://github.com/EtienneLamoureux/TQVaultAE/files/3438045/TQVaultData.zip)

@lvlvy : Is this still a problem ?
I can't reproduce it using the last TQvaultAE build. Everything looks ok on my system using your vault file. Can you validate your TQAE files (steam feature) ?

**Comment by lvlvy** [comment]
Problem solved. 

Where is no solution really, but I did this:
1. Put somewhere else "My games" folder (C:\Users\(your pc name)\Documents\My Games)
2. Lauch game and then exit it
3. Then put your characters back to new "my games folder"
You may lose tqvault saved data, but this brings back all icons
