### ISSUE TITLE
Windows usability options (scaling) deforms the UI

### ISSUE THREAD

**Issue by EtienneLamoureux** [EtienneLamoureux/TQVaultAE#21]
Any scaling option on Windows that's not the default 100% deforms the UI
- The spacing between elements is off
- The labels are too large compared to everything else (maybe everything else is off sized)

Investigate if it's possible to simply resize the window to accommodate.

See http://www.titanquest.net/tq-forum/threads/55703-BETA-TQVault-2-3-1-4-AE/page14?p=521441&viewfull=1#post521441

**Comment by epinter** [comment]
The UI is deformed while the UI is scaled, but after restart, the previously selected scale is used and everything is perfect. Didn't find a solution. Seems to be a problem with the scaling itself when changing the size of child elements.

I think if we want to keep ui scaling, we need to accept the bug, or to find a way to completely restart the ui after a resize.

**Comment by NorthFury** [comment]
I think the inconvenience is small enough that it doesn't matter. I guess we should put it in a FAQ.

**Comment by epinter** [comment]
@EtienneLamoureux what you think ?

**Comment by KenAlin** [comment]
Unfortunately, it is now impossible (for me, at least) to move between character and stash. That's a huge usability issue. Here is how TQ Vault looks like after a restart.

![image](https://user-images.githubusercontent.com/12164749/34483720-a8a1ccb8-efc0-11e7-9440-7d666ab28978.png)

**Comment by NorthFury** [comment]
Can you try to scale it a bit and then restart it? No matter how I scale it, for me it is always usable after restart.

**Comment by epinter** [comment]
I tried, but didn't manage to reproduce yet. What resolution and font scale (in Windows) you are using ?

**Comment by KenAlin** [comment]
Resolution is 1366*768, font scale default 100%. The screenshot was taken after a restart, with the latest released build (2.5.3).
I'll see if I can fix, but I'm not too skilled with UI in C#.

**Comment by epinter** [comment]
I'm still trying to reproduce the problem in KenAlin's screenshots, didn't found a way yet.

@KenAlin the problem occured with a standard 96dpi display ?

**Comment by epinter** [comment]
Everything seems to be better now with scaling on startup.

**Comment by Pequals** [comment]
[https://media.discordapp.net/attachments/393370750930649088/580491047587807232/5165651651.JPG?width=821&height=551](url)

Hi, I'm using 1280*1024 resolution and before updating to the latest version everything was ok, I used v.2.4 I think. But last one looks really messy. I hope there is a solution for this.

P.s.: thank you very much for all your work, amazing app

**Comment by Ara-tq** [comment]
this is imho still not fixed.
This is how it looks at 2560x1440 at Medium (125%) scaling:
![image](https://user-images.githubusercontent.com/93734646/140609450-4d800212-0724-4525-bbe3-a50dec7604a5.png)
The lower right isn't dragable. If I use the lower left corner and drag it a bit bigger it looks normal on next startup. But without changing anything, on the next startup it's back to being cut off again.
