### ISSUE TITLE
add "load all vaults and characters" button to search dialog

### ISSUE THREAD

**Issue by afjback** [EtienneLamoureux/TQVaultAE#211]
Usually I work with one character and vault sack, so I unchecked "Pre-load all vault and character files" for launch speedup.
But sometimes I need to look for item on another vaults (don't remember exactly which one), so for full search thru search dialog I need either to pick all vaults one by one to load, or change setting above and relaunch.
For such cases it will be better to add "load all vault and characters" button to search dialog.

**Comment by EtienneLamoureux** [comment]
I'm not too keen on reworking the loading logic as it's part of the loading sequence. 
The workaround is to relaunch with "load all" enabled.
