### ISSUE TITLE
Ability to disable bag preview

### ISSUE THREAD

**Issue by Armp4** [EtienneLamoureux/TQVaultAE#214]
Please make a way to disable bag previews. When bags are full they take half of my screen, and pop up constantly when I just try to switch between bags. Very uncomfortable. A simple checkbox to tick them off would be perfect

![Screenshot_3](https://user-images.githubusercontent.com/47891221/62521542-8cb71980-b838-11e9-95af-903e12eb7f0c.png)

P.S. Russian translation is incorrect in some places. I would gladly fix it if you send me localization files

**Comment by hguy** [comment]
Thank you for reporting and for your help.
The Russian localization file is [here](https://github.com/EtienneLamoureux/TQVaultAE/blob/master/src/TQVaultAE.Presentation/Resources.ru.resx).

**Comment by Armp4** [comment]
Done. The fixed file is suggested. Thank you for responsiveness!

**Comment by EtienneLamoureux** [comment]
@Armp4 If you attach/email me the fixed translation file, I'll include it in the next release.

**Comment by Armp4** [comment]
@EtienneLamoureux [here](https://raw.githubusercontent.com/EtienneLamoureux/TQVaultAE/8344e3aae08bc9d437636cb120e5214bb7d8d455/src/TQVaultAE.Presentation/Resources.ru.resx) it is
