### ISSUE TITLE
Saving the last window size

### ISSUE THREAD

**Issue by ryksa92** [EtienneLamoureux/TQVaultAE#215]
Would it be possible to save the TQVault's window size of the last session on exit? Right now, the window size is the only thing, which can change the font size, so it would be cool to have this feature. Thanks. :)

**Comment by hguy** [comment]
Have you try to change font in settings window ? It may help readability in some cases.

**Comment by hguy** [comment]
@EtienneLamoureux : this should be closed

**Comment by EtienneLamoureux** [comment]
@hguy That's on your fork. Do we have the commit on the main release?

**Comment by hguy** [comment]
@EtienneLamoureux Yes it has been merged with https://github.com/EtienneLamoureux/TQVaultAE/pull/217
