### ISSUE TITLE
Better Searching & Sorting

### ISSUE THREAD

**Issue by nerdnosyd** [EtienneLamoureux/TQVaultAE#22]
Additional search options like specific stats (e.g. "Cooldown Reduction" "Reduction to Enemy's Health" "Total Speed")

On the search result page, more columns to sort by (e.g. armor slot, level requirement, stat requirements)

**Comment by NorthFury** [comment]
I would also like to add that sorting doesn't work as expected. the list is sorted but the tooltip is for the item that was at that position before sorting. I tried to do it by using a BindingSource but I'm no C# guy. Maybe it's easy and I don't see it. I just had to give up after I invested way to much time. The simplistic fix for sorting is in my fork.
