### ISSUE TITLE
Allow to copy/duplicate сharacter equipment if "Player equipment Readonly" is set

### ISSUE THREAD

**Issue by afjback** [EtienneLamoureux/TQVaultAE#220]
In this case player equipment keeps untouched, you cannot change it, but permitted to copy/duplicate items to vaults,

**Comment by afjback** [comment]
"read-only" items context menu have to contain non-destructive commands: Copy, Duplicate, Properties.

**Comment by afjback** [comment]
Unfortunately version 3.4.0 rewrites "readonly" character profile file on exit if item was copied from it.
This makes useless the whole intention to keep file untouched.
also https://github.com/EtienneLamoureux/TQVaultAE/issues/267

**Comment by EtienneLamoureux** [comment]
I'll close this and expand #267
