### ISSUE TITLE
Fix displayed stats for "over time" effects

### ISSUE THREAD

**Issue by afjback** [EtienneLamoureux/TQVaultAE#222]
Ingame:
![bsp-ra-ingame](https://user-images.githubusercontent.com/53652815/62823964-11d76100-bba0-11e9-9cb6-7b4bbeb07552.jpg)
displays 318 reduced armor for 3 seconds (scheme: `effect , duration`)

Vault:
![bsp-ra-vault](https://user-images.githubusercontent.com/53652815/62823995-53680c00-bba0-11e9-9cad-79d77f589953.png)
displays 1080 (three times more) reduced armor for 3 seconds, which is wrong.
Seems like vault gets these stats:
`offensiveSlowDefensiveReductionDurationMin,3.000000,
offensiveSlowDefensiveReductionMin,360.000000,`
and multiply them for some reason (scheme: `effect*duration , duration`). For this case 360 RA for 3 seconds doesn't mean 1080 in whole.

**Comment by ejfudd** [comment]
Just looking at the screen grabs, it actually appears that there are two different effects.  Looking at the wording of the format string the behavior may be correct for that particular format.
To fix this we would need to look at a few "over time" items from both the base game and expansions to verify the tags and change the attribute parsing accordingly.

**Comment by Ninakoru** [comment]
Well, it happens I fixed this one while resolving other tooltip issues:

https://github.com/Ninakoru/TQVaultAE/releases/tag/3.8.8-TEST3
