### ISSUE TITLE
How do I edit the game paths in the XML config?

### ISSUE THREAD

**Issue by thienma217** [EtienneLamoureux/TQVaultAE#226]
I am running windows 10 and have Atlantis from Steam. I downloaded newest verson of TQVault but it didn't working. To start the application, I clicked on  TQVaultAE.exe but nothing happen. Looking at the task manager it shows it launching and then says suspended and it closes. I tried to follow the instruction in #91 but it still not working.

**Comment by lvlvy** [comment]
Have you tried to change game path manually?
![image](https://user-images.githubusercontent.com/33087111/63231505-552b7280-c225-11e9-9c03-5f7c6c349fc6.png)

**Comment by thienma217** [comment]
> 
> 
> Have you tried to change game path manually?
> ![image](https://user-images.githubusercontent.com/33087111/63231505-552b7280-c225-11e9-9c03-5f7c6c349fc6.png)

I did it. But it not working.

**Comment by VMSebastopol1942** [comment]
What does the log file says (it's in the logging folder) ?

**Comment by thienma217** [comment]
[TQVaultAE_2019.08.29.txt](https://github.com/EtienneLamoureux/TQVaultAE/files/3555275/TQVaultAE_2019.08.29.txt)
I attached the log file here. Pls take a look.

**Comment by VMSebastopol1942** [comment]
According to your log file, it's a problem with the wirting of the config file, like one i a xlm file: it doesn't respect the criteria.To be more precise, in this case, a character is missing or misprinted at the line 56 so the start and the end don't match and the programm doesn't understand so it crahses. Here's my config file (I'm currently on the latest version of TQVault). You'll need 1): to restore the name of the file (Git Hub doesn't support the .config format)and then to overwrite your file
2) to make sure that EVERY path is correct. ONLY  the paths of 1) the vault location,  2) TQIT, 3) TQ, 4) the forced path (at the line "Force Game Path") at the bottom and nothing else. (It's in the order)
Do not delete any > or < 

[TQVaultAE.exe.(config).txt](https://github.com/EtienneLamoureux/TQVaultAE/files/3555350/TQVaultAE.exe.config.txt)

**Comment by EtienneLamoureux** [comment]
VMSebastopol1942 is correct: there is a problem with your config file. You should get a fresh one and carefully replace the paths. 
- You can get a fresh config file [int he latest release](https://github.com/EtienneLamoureux/TQVaultAE/releases/download/3.2.1/TQVaultAE_3.2.1.zip)
- You can check if your config file has error using [this website](https://www.xmlvalidation.com/)

**Comment by VMSebastopol1942** [comment]
Hi Etienne Lamoureux (french or Quebecois, isn't),
Thanks for your work: building a vault was an incredible idea.
Regarding the problem, i think the file i just provided will be fine because he made the same error as me: just a writing error. In the file i've uploaded he just need to change the path so he doesn't risk to make another mistake.
Anyway, thanks for your job

**Comment by thienma217** [comment]
> 
> 
> According to your log file, it's a problem with the writing of the config file, like
> a XML file: it doesn't respect the writing criteria. To be more precise, in this case, a character is missing or misprinted at the line 56 so the start and the end don't match and the program doesn't understand so it crashes. Here's my config file (I'm currently on the latest version of TQVault). You'll need
> 
>     1. to restore the name of the file (Git Hub doesn't support the .config format)and then to overwrite your file
> 
>     2. to make sure that EVERY path is correct. ONLY  the paths of 1) the vault location,  2) TQIT, 3) TQ, 4) the forced path (at the line "Force Game Path") at the bottom and nothing else. (It's in the order). **Do not delete any > or <**
> 
> 
> [TQVaultAE.exe.(config).txt](https://github.com/EtienneLamoureux/TQVaultAE/files/3555350/TQVaultAE.exe.config.txt)

Thank you very much! It has worked normally

**Comment by VMSebastopol1942** [comment]
You're welcome. Go kick some ass

**Comment by EtienneLamoureux** [comment]
Glad everything got sorted out!
