### ISSUE TITLE
Missing set

### ISSUE THREAD

**Issue by lvlvy** [EtienneLamoureux/TQVaultAE#227]
Can not create this set parts or do anything else with it. I think it is not in tqvault database.

Some pictures of item:
![image](https://user-images.githubusercontent.com/33087111/63231396-d7b33280-c223-11e9-9507-e2eb7ad6e315.png)

This happens after right mouse click:
![image](https://user-images.githubusercontent.com/33087111/63231413-206aeb80-c224-11e9-8db3-681b1c7e51dd.png)

**Comment by afjback** [comment]
Well, this is not totally Vault's mistake. These items seems still under construction.
And there are mistakes in game db related to `Priest of Ba'al Hammon`: 
- torso has link to set, while set definition doesn't have link to torso.
- set has link to greaves while greaves don't exist in given path, actually for some reason greaves are in `out` folder

**Comment by EtienneLamoureux** [comment]
We'll let the THQ people fix the item data before looking at this.
