### ISSUE TITLE
Can TQVault produce equipments，or modify the prefix and suffix of an item?

### ISSUE THREAD

**Issue by doomsdayer** [EtienneLamoureux/TQVaultAE#228]
Some equipments are very hard to drop.....
Could the software produce some equipment for players?

**Comment by EtienneLamoureux** [comment]
Aside from creating missing set items, **no**, the tool cannot create items from nothing. Please check out custom maps from the workshop such as ITEMUS or ShopMI.

As for affix editing, we do have #144
