### ISSUE TITLE
Fix Ctrl+f keyboard shortcut to invoke Search dialog

### ISSUE THREAD

**Issue by afjback** [EtienneLamoureux/TQVaultAE#229]
subj.

**Comment by afjback** [comment]
UPD: ctrl+f shortcut doesn't work unless you click app window somewhere, or hover item to invoke item stats popup.

**Comment by EtienneLamoureux** [comment]
The windows does have to have focus to be able to recognize keyboard shortcuts.

**Comment by afjback** [comment]
Tried to drill ctrl+f for latest release 3.3.1
Doesn't work until you hover (not click) any sack panel or item

**Comment by ejfudd** [comment]
Found that the Main Form was not processing keys and it was only the child controls.
The property KeyPreview needs to be set on the Main Form.
