### ISSUE TITLE
Character stats labels extend out of the panel for some languages

### ISSUE THREAD

**Issue by afjback** [EtienneLamoureux/TQVaultAE#232]
![text-overlap-or8](https://user-images.githubusercontent.com/53652815/65860779-a45fd980-e373-11e9-8649-5db04b27ad1b.png)

**Comment by EtienneLamoureux** [comment]
As a note: French translations have the same problem for this particular window pane.

**Comment by afjback** [comment]
looks even worse for now
![info-wrap-worse-or8](https://user-images.githubusercontent.com/53652815/69918937-8ce2c100-1488-11ea-9d4b-29faee317d36.png)
Some words are missing (not displayed), whole list is cutted at bottom.

**Comment by hguy** [comment]
> 
> 
> looks even worse for now
> Some words are missing (not displayed), whole list is cutted at bottom.
@afjback Is there a way to shorten labels without loosing meaning (rewrite) ?
Making it fit in 2 rows instead of 3 ?

**Comment by hguy** [comment]
> 
> 
> > looks even worse for now
> > Some words are missing (not displayed), whole list is cutted at bottom.

@afjback Is there a way to shorten labels without loosing meaning (rewrite) ?
Making it fit in 2 rows instead of 3 ?

**Comment by afjback** [comment]
The problem is main english translation uses a lot of settled shortenings - XP instead of experience, Int, Recv, and so on.
Russian labels are short enough for common language. To shorten even more, one needs to use game slang, which generally is not so settled as in English.

There s a lot of free space to the right of player stats panel. I think, widening it to the right window boundary and limiting line feeds to 2 lines will cover the most cases.

**Comment by afjback** [comment]
Btw English translation says "Base Mana", although game designers use "Energy" instead (although internally it is still called mana)
![mana-energy-or8](https://user-images.githubusercontent.com/53652815/70533342-f4c09800-1b69-11ea-8eaf-a051d9a3a1f0.png)
