### ISSUE TITLE
Panels are out of position when using a non-100% Windows display scaling value

### ISSUE THREAD

**Issue by Vazirazi** [EtienneLamoureux/TQVaultAE#235]
There is something wrong with display in recent version. Ho can I fix this?

![Przechwytywanie](https://user-images.githubusercontent.com/23178479/66219168-f46bd280-e6ca-11e9-8093-6639460cd0a3.PNG)

**Comment by EtienneLamoureux** [comment]
Are you using a non-100% [Windows display scaling](https://www.lifewire.com/using-windows-10-display-scaling-4587328) value?

**Comment by Vazirazi** [comment]
Yes, I am using windows 10 dpi fix. After turning it off TQvaultAE seems to be working fine. Thanks very much!

**Comment by EtienneLamoureux** [comment]
Alright. You can try [CTRL]+[+]/[-] to try to fix it with the DPI fix.
Otherwise, that is unfortunately a limitation of you graphical library.
