### ISSUE TITLE
CustomMaps Support

### ISSUE THREAD

**Issue by Cristi80** [EtienneLamoureux/TQVaultAE#241]
First of all I wish to say hi and thank you for this great mod which is a huge adition to the game absurdly low storage space but i have a problem. Im currently running TQ AE Atlantis v2.8 and TQVaultAE v3.3.1 and i was trying to use a mod ( Legacy: rng_overhaul ) and it seems TQVaultAE doesnt work with CutomMaps. I mention that i followed the correct steps for both TQ AE and TQVaultAE. ( For example: Go town iteract with caravan driver to create the necessary files save exit and setup TQVaultAE ). Now TQVaultAE works as intended with CustomMaps if i manually copy: "SaveData\Sys\rng_overhaul" to "CustomMaps\rng_overhaul" but i need to repeat the process every time i exit the game to update any changes. And one more tiny little thing: Necklace slot doesnt display correctly in TQ AE it needs a bit of attention.
![1](https://user-images.githubusercontent.com/47424326/66428774-57d56780-ea1f-11e9-9e29-91430112b5a6.png)
![2](https://user-images.githubusercontent.com/47424326/66428796-64f25680-ea1f-11e9-8b69-a2818d08478b.png)
![3](https://user-images.githubusercontent.com/47424326/66428805-691e7400-ea1f-11e9-87a9-2327ab7509f3.png)
![4](https://user-images.githubusercontent.com/47424326/66428827-720f4580-ea1f-11e9-8879-7dbd010e3403.png)
![5](https://user-images.githubusercontent.com/47424326/66428834-763b6300-ea1f-11e9-9f3e-6e85a20c1358.png)
![6](https://user-images.githubusercontent.com/47424326/66428838-789dbd00-ea1f-11e9-82e7-02865dfab4ee.png)
![7](https://user-images.githubusercontent.com/47424326/66428851-7dfb0780-ea1f-11e9-8f96-d0ebcb278995.png)
![8](https://user-images.githubusercontent.com/47424326/66428864-85baac00-ea1f-11e9-82f9-dd37c5570a1a.png)

**Comment by EtienneLamoureux** [comment]
Thanks for the kind words.

If that's alright with you, we'll track these issues in their respective threads: 
- #212 Complete support of custom maps and characters
- #128 Adjust the space on the character panel for Ragnarok necklaces

**Comment by EtienneLamoureux** [comment]
Just for reference: is this mod from the Steam Workshop?

**Comment by Cristi80** [comment]
> Just for reference: is this mod from the Steam Workshop?

No it is from Nexus Mods:
https://www.nexusmods.com/titanquestanniversaryedition/mods/7

**Comment by Cristi80** [comment]
> Thanks for the kind words.
> If that's alright with you, we'll track these issues in their respective threads:
> 
> #212 Complete support of custom maps and characters
> #128 Adjust the space on the character panel for Ragnarok necklaces

Np sir thank you your time.
