### ISSUE TITLE
Render description text for relics completion bonus colloquially

### ISSUE THREAD

**Issue by afjback** [EtienneLamoureux/TQVaultAE#242]
[relics-CB-text.zip](https://github.com/EtienneLamoureux/TQVaultAE/files/3705455/relics-CB-text.zip)
![relics-statusbar1-or8](https://user-images.githubusercontent.com/53652815/66449279-31362180-ea5d-11e9-9efd-7938626f3b1a.png)
![relics-statusbar2-or8](https://user-images.githubusercontent.com/53652815/66449291-38f5c600-ea5d-11e9-8e17-3d3e1975b676.png)

**Comment by hguy** [comment]
This happen for completed relic previous to 3.2.1 i guess.
You can get rid of it by changing completion bonus to another and changing back (item edition feature).

**Comment by afjback** [comment]
There is version 3.3.1 on screenshot.

Tried to change CB to another and back. It fixes status line text, but DOES NOT fix bag preview text.

**Comment by hguy** [comment]
I can't reproduce.
the procedure did work for me.
![image](https://user-images.githubusercontent.com/31834707/66952305-a9ec3d80-f05c-11e9-8623-32b2208b3ae5.png)
