### ISSUE TITLE
A thanks and a silly request

### ISSUE THREAD

**Issue by Cristi80** [EtienneLamoureux/TQVaultAE#244]
Hello Etienne! I cant help my self from saying thank you again for TQVaultAE it made my life mutch more easy and the game experience mutch more enjoyable. Now i have a silly request and if you can take it seriously would be very mutch appreciated. Can you make a similar tool for Grim Dawn? :D

**Comment by EtienneLamoureux** [comment]
Unfortunately I'm only maintaining this project at the moment with the help of the other open-source contributors, but I'm happy you enjoy the tool!

I believe something like this might exist for GD, you could look at [this forum thread](https://steamcommunity.com/app/219990/discussions/0/405693392927335247/) as a starting point!
