### ISSUE TITLE
Fix display of negative bonuses when listing item stats

### ISSUE THREAD

**Issue by afjback** [EtienneLamoureux/TQVaultAE#246]
[negative.zip](https://github.com/EtienneLamoureux/TQVaultAE/files/3764272/negative.zip)
![neg1-or8](https://user-images.githubusercontent.com/53652815/67430285-9efc5480-f5ea-11e9-83b6-2cf36d55a910.png)
![neg2-or8](https://user-images.githubusercontent.com/53652815/67430298-a4f23580-f5ea-11e9-98ef-f392a432ae3b.png)

**Comment by hguy** [comment]
this should be fixed by #248

**Comment by afjback** [comment]
still there :(
![negative-again-or8](https://user-images.githubusercontent.com/53652815/69918691-4ee49d80-1486-11ea-8aa7-1208f2c59f02.png)

**Comment by hguy** [comment]
I spot that too ! 
Last fix works for negative values having positive format string, it should be fix also for positive value having negative format string.
