### ISSUE TITLE
Equipping/Un-equipping items from the Vault corrupts the character

### ISSUE THREAD

**Issue by EtienneLamoureux** [EtienneLamoureux/TQVaultAE#25]
There is a chance when equipping/UN-equipping items from a character's equipment panel directly into the vault that the character becomes corrupted. The following corruption can occur:
- One of the ring will become duplicated and equipped as the artifact
- The second weapon set will overwrite (and delete) the first weapon set
- The artifact will be equipped as the second weapon set

**Comment by Graagh** [comment]
I don't believe this actually deletes the first weapon set. It equips them "under" or "over" other existing equip locations, such as the helmet or amulet slots. They can be recovered, at least in my case, by removing the character's equipment in-game and re-equipping.  Once the top item in a slot is removed, the item underneath is revealed and can also be removed, if wrongly placed.  The invalid equipment can't be accessed within TQVault itself, however. Unequipping must be done within the game.  Seems like an equip slot indexing problem.

**Comment by EtienneLamoureux** [comment]
The problem should be alleviated by the fixes merged in with https://github.com/EtienneLamoureux/TQVaultAE/pull/27 : a new option, which defaults to true, allows to interact with the equipped items in a read-only fashion.
