### ISSUE TITLE
question: how debug levels are supposed to work?

### ISSUE THREAD

**Issue by afjback** [EtienneLamoureux/TQVaultAE#252]
I want to investigate Vault bootstrap procedure.

tried to modify TQVaultAE.exe.config:
DebugEnabled True
ARCFileDebugLevel 3
DatabaseDebugLevel 3
ItemDebugLevel 3
ItemAttributesDebugLevel 3

But tqdebug.txt file is missing, and log file still contains only string
2019-10-29 02:57:55,113 [1] INFO  TQVaultAE.GUI.MainForm [(null)] - TQVaultAE Initialization !

**Comment by afjback** [comment]
So it is impossible for builds downloaded from "release" section?
Can I download debug build or I need to compile it myself?

**Comment by hguy** [comment]
The DebugEnable option is for "debuging".
It's purpose is to facilitate code behavior tracking by programmers during code tuning of specific parts. It's not meant to be an end user option.
There is no debug build to download but you can easily make a debug build locally by cloning the repository. You will have to compile it yourself.

**Comment by EtienneLamoureux** [comment]
As discussed, releases are compiled in release mode to help with performance. This also disables the debug hooks. Feel free to clone and compile the solution yourself.
