### ISSUE TITLE
Improve window resize performance when video card is busy

### ISSUE THREAD

**Issue by afjback** [EtienneLamoureux/TQVaultAE#260]
I use hashcat to load my videocard. Workflow goes fine more or less. But Vault resize behaves like these:
https://streamable.com/prw9f
I cannot record startup procedure because Vault starts minimized, and I cannot bring it to the front until it fully renders itself. But trust me, warm startup takes about 20 seconds with almost empty sacks and preloadAll=off. Normally warm startup takes 1-2 secs.

**Comment by hguy** [comment]
I admit it's kind of slow! But labeling this as a "bug" look extreme.
IMHO "enhancement", "refactor" or "optimization" would be more faithful.

**Comment by ejfudd** [comment]
PR #335 may have fixed this issue.
