### ISSUE TITLE
Fix game files lookup in ARZExplorer

### ISSUE THREAD

**Issue by afjback** [EtienneLamoureux/TQVaultAE#261]
Tried to fix ARZExplorer
1. added search for GOG installation. This at least works for me. I do not have steam's TQ, so cannot check steam installation logic anyway. Also I do not want to copy-paste installation find procedure from GamePathServiceWin, as it is bugged if you have neither steam nor gog installation.
2. fixed exception if user cancels save file dialog.
[MainForm.zip](https://github.com/EtienneLamoureux/TQVaultAE/files/3827507/MainForm.zip)

**Comment by hguy** [comment]
Hello! Thanks for your help.

`GamePathServiceWin.ResolveTQ` and `GamePathServiceWin.ResolveTQIT` are checking for GOG, Steam and "old disk" installation path.
If it find none of these path, it throw an exception meaning you have no game installed on your machine.
It's not a bug. It's a requirement. TQVaulAE have no purpose on a machine without TQ installed on it.
You need at least the game files even without a proper installation and adjust the `ForceGamePath` in the app setting file.

If you only add the GOG discovery code you could have use `GamePathServiceWin` as it try to find GOG first.

But a bit of refactor is needed for that and the temptation of copy-paste is strong.
We should make a `TQVaultAE.Services.Win32` project (.NETFramwork) to contain what's in `TQVaultAE.GUI.Services` and doing so adding a reference to it from ARZExplorer.

**Comment by afjback** [comment]
So GamePathServiceWin.ResolveTQ is intended to find gog, then steam, then disc, then to throw exception "do it manually".
Lets run Vault on computer with TQ installed thru Discord (discontinued tho) or Origin:
- gog registry fails
- steam regisry fails
- then it tries to read steam's `libraryfolders.vdf` without checking whether this file exists, and with exception falls back to parent procedure. So disc checking and further code is actually unreachable, and user don't know what to do.

I think Vault should not limit itself with gog-steam-disc options so hard. If these fail, it will be better to show standard options dialog to set paths manually instead of exception.

**Comment by hguy** [comment]
Thanks for your observations. 

I just push a fix on #262.
