### ISSUE TITLE
Fix game path auto-detection of 32-bit GOG installation on Win64

### ISSUE THREAD

**Issue by afjback** [EtienneLamoureux/TQVaultAE#269]
previous Vault versions used 32-bit registry virtualization and were redirected to
HKLM\SOFTWARE\Wow6432Node\GOG.com
where native 32-bit applications reside on 64-bit OS

New version checks 64-bit only
HKLM\SOFTWARE\GOG.com
and fails to find game installation

**Comment by hguy** [comment]
Looks like compilation target "Any CPU/x64" change registry reading behavior

**Comment by EtienneLamoureux** [comment]
I did have to fiddle with the build this time around.

As a workaround, you can set the game path manually following the instructions [here](https://github.com/EtienneLamoureux/TQVaultAE#troubleshooting-and-faq), under "Q. I have this game as a stand-alone (i.e. not through Steam or GOG). How can I make TQVaultAE work?"

**Comment by hguy** [comment]
@afjback is the interactive folder selection defined here did popup ? https://github.com/EtienneLamoureux/TQVaultAE/pull/262#issuecomment-552194070

**Comment by afjback** [comment]
manual path selection popup works fine
