### ISSUE TITLE
White relics bag tooltip color.

### ISSUE THREAD

**Issue by afjback** [EtienneLamoureux/TQVaultAE#273]
![tooltip1-or8](https://user-images.githubusercontent.com/53652815/71115429-ee25c680-21e2-11ea-88c9-610450c58f92.png)
![tooltip2-or8](https://user-images.githubusercontent.com/53652815/71115436-f0882080-21e2-11ea-8ef1-c272037c7e04.png)
While charms bag tooltip respects their orange color.

**Comment by hguy** [comment]
Yes i did this to add more contrast to the bagtooltip content and differentiate easily between Relics and Charms.
Having a tooltip full of orange text was boring and hard to read.
