### ISSUE TITLE
Is the any opportunity to compare two equal items ?

### ISSUE THREAD

**Issue by Cloxy777** [EtienneLamoureux/TQVaultAE#275]
Sometimes I'm getting the already existing item but with better affixes. Is there any opportunity to compare them via TQ Vault?
The only difference is the «itemSeed» number.
Thank you.

**Comment by EtienneLamoureux** [comment]
Unfortunately no, not currently. We still [don't understand how the item seed impacts the rolls](https://github.com/EtienneLamoureux/TQVaultAE#troubleshooting-and-faq) on an item stats:
>**Q. Does TQVaultAE modify my items? The stats I see are not the same as the ones ingame.**
>*A. No, unless you specifically use the cheats, TQVaultAE doesn't alter items in any way. The difference you see is simply due to the way stats are generated in Titan Quest: each item has base stats and a unique seed that modifies those stats. TQVaultAE only displays the base stats (and not the modifications due to the RNG).*
