### ISSUE TITLE
Fix error when scrolling in the search results pop-up

### ISSUE THREAD

**Issue by zelo86** [EtienneLamoureux/TQVaultAE#276]
Dear EtienneLamoureux,
first of all thanks for the work you put on updating and enhancing TQ Vault AE! It's really an useful tool!
Then I'd like to write that I found an error when I use the search function.
When the search is done and the window with the results appears, if I click on "level" tab to sort results by level requirement, after a little mouse scrolling this error occur. I'll put an Image.
If I only watch the results as they appear, nothing happens.
![Immagine](https://user-images.githubusercontent.com/56092244/72081422-bea83c80-32fe-11ea-860a-2736df98a6b2.png)
I'm on Win 10 Pro x64 1909, 16GB Ram, I use the *.zip of 3.4.0 TQ Vault AE, not the installer one.
Thanks again for the effort

**Comment by EtienneLamoureux** [comment]
First of all, I'll redirect the thanks to our [amazing contributors](https://github.com/EtienneLamoureux/TQVaultAE/graphs/contributors), as they're the one doing the bulk of the work!

Thanks for reporting the error, it's now tracked as a TO DO item.

**Comment by ejfudd** [comment]
This error occurs when you run a search and do not have any characters loaded.  Once you mouse over an item that is in a character's stash, this error will show as TQVault attempts to highlight the item without an actual stash present.

**Comment by zelo86** [comment]
Ok, I understand.. Thanks a lot!!!

**Comment by ejfudd** [comment]
I have actually proposed a fix for this issue.
A simple workaround would be to always load a character prior to using the search.  It will still do some strange selecting of items in the player panel but it should not throw an exception.

**Comment by zelo86** [comment]
I tried your workaround and it works, no error message. It was simple..
Because of the fact that I don't have informatic knowledge, I couldn't understand the error..
Thanks for finding a solution and letting me know.
