### ISSUE TITLE
Add new option to disable Relic, Charm & Potion stacking

### ISSUE THREAD

**Issue by NANI-ship-it** [EtienneLamoureux/TQVaultAE#278]
Please consider adding an option to disable Relic and Charm stacking and completion, and Potion stacking, for a "purist" way of using TQVaultAE only for muling. Currently it's easy to accidentally stack Relics, Charms and Potions when the intention is to just move them around.

Especially the Relic - and probably Charm too, didn't test that - completion bothers me slightly, because the Completion Bonus works in a bit different way in-game. More info below.

P.S. Also, I did a quick test on how Relic Seed affects the Completion Bonus. I had 3 pieces (piece = 1/3rd of a Relic) of a Relic each with a different Seed, let's call this a set. Then I Duplicated the set multiple times, so that I could repeat the combining of the Relic pieces, doing it always in the same order, e.g. Set 1 = Seed 1 -> 2 -> 3; Set 2 = Seed 1 -> 2 -> 3; etc.

Combining the Relics this way in TQVaultAE seems to randomize the completion bonus according to the Completion Bonus weightings, which seems logical and how it should work. But, in-game, the Completion Bonus was always the same for each set, because the Seeds of the pieces were identical in each set.

Of course in practice that doesn't really make much of a difference, because the Relics' Seeds are going to be random anyway, but the bottom line is that there is a difference in how the Completion bonuses are handled in TQVaultAE compared to the game.

Anyway, these are minor things and the tool itself is great. Thanks to all involved in creating it!

**Comment by EtienneLamoureux** [comment]
Thanks for the contribution.
Also interesting experiment you ran. Unfortunately, anything that has to do with seeds is a black-box on our end, so there will be no foreseeable change on that front.

**Comment by hguy** [comment]
@NANI-ship-it this feature is coming soon.
