### ISSUE TITLE
Enable saving the modified stashes without closing the tool

### ISSUE THREAD

**Issue by hguy** [EtienneLamoureux/TQVaultAE#283]
without the need to close the app.

- [ ] relic stash,
- [ ] shared stash,
- [ ] private stash,
- [ ] inventory,
- [ ] bags.

**Comment by EtienneLamoureux** [comment]
Related to #282, with the same concerns. I'm not quite clear when the game reloads/saves its data currently.

**Comment by afjback** [comment]
I also wanted to suggest such functionality.

The game handles two types of storages: one directly inside player's file (game uses it all the time while playing), and those from Caravan Driver: private, shared, relic, which are used by game when you chatting to Driver. I think it would be better to start with the second ones.
Anyway if there are any early bugs, these bugs related to Driver's storages will be less destructive, than to character's.

**Comment by hguy** [comment]
@EtienneLamoureux This is implemented and enabled with the "hot reload" config setting.
