### ISSUE TITLE
The Forge : Add support for "Item Crafting" 

### ISSUE THREAD

**Issue by hguy** [EtienneLamoureux/TQVaultAE#284]
Ability to craft an item from up to 3 existing items of the same type. Each chosen item carrying one of the three categories (BaseItem, Prefix, Suffix).

- [ ] Purist mode : Feature deactivated.
- [ ] Veteran mode : Source items are destroyed during the process (For in between non cheating mentality).
- [ ] Elite mode  : Source items are not destroyed during the process.

Forge Modes : combobox in config settings.

**Question :** Does having an item with Prefix/Suffix picked up outside of it's regular loottable make the game explode?

**Comment by afjback** [comment]
Crafting items on demand is very slippery way, but I think it is better to try, than not to try at all.

"Regular lootables" is a fiction :( TQ lootables  are bugged as hell. There are magical boots drop slapped with melee torso affiixes. There are whole Atlantis staves drop with axe ("mass-generated" by description) affixes.

In addiction we have limited list of legendary items which can be dropped with affixes. They have their own loottables, and affixes are more powerful compared to regular loottables. But in contrast, unlike all other tables, these items can have either prefix, or suffix, but not both. Combining such items will get one which cannot be obtained legitimately.

**Comment by afjback** [comment]
The other problem is stat values. Affixes do not have their seeds, but relies on the seed of the item they are currently on.
So user can transfer an affix from item with "lucky" seed to target item. And target seed may be unlucky enough ("where are my precious stats?") to ruin the whole build.

**Comment by EtienneLamoureux** [comment]
Related to https://github.com/EtienneLamoureux/TQVaultAE/issues/144

**Comment by EtienneLamoureux** [comment]
There are affixes that are supposed to only go with some items, as seen [here](https://tq-db.net/en/affix/prefixes). We should try to respect the data.

**Comment by EtienneLamoureux** [comment]
I'd rather see this implemented as #144
