### ISSUE TITLE
Can TQVaultAE run on Windows 8?

### ISSUE THREAD

**Issue by Nomado-Coyote** [EtienneLamoureux/TQVaultAE#286]
I can't get TQVault to work because it asks me to install a .net framework 4.7.2 precisely.
and I haven't found a single way to install it on windows 8. is it even possible to run it on win8?

**Comment by EtienneLamoureux** [comment]
That's a good question, as we had quite a rework of the dependencies lately. @hguy might be better suited to answer this.

If this is a blocking issue for you, you could try using an older version of the tool in the meantime. There's a chance it might work.

**Comment by Nomado-Coyote** [comment]
Sorry, how does it work, will he probably come cause you tagged him or do I need to write him personally somehow? I don't use github frequently

**Comment by hguy** [comment]
it should be compatible.
- https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/versions-and-dependencies#net-framework-472

Apply latest windows updates. Upgrade to Windows 8.1.

Try installing using Offline installer
https://dotnet.microsoft.com/download/dotnet-framework/thank-you/net472-offline-installer

**Comment by Nomado-Coyote** [comment]
Thank you hguy.
I see, so there's no way to do it without upgrading to 8.1
That's the point I chose not to update to 8.1 for years for several reasons and finally I find that one reason haha. Maybe I will, eh. It's a shame that I can't use TQ Vault on 8.0
