### ISSUE TITLE
How to transfer items from a vault to a character?

### ISSUE THREAD

**Issue by Titatotu** [EtienneLamoureux/TQVaultAE#288]
Tqvault does not transfer items from a safe to a character with the steam anniversary edition.
When i put an item in my vault and retransfer it on another character, it doesn't work at all : my character still doesn't have the item.

**Comment by EtienneLamoureux** [comment]
Is the game open while doing the operation? Is so, this is not supported (see the answer to ["Q. Can I use TQVaultAE while playing the game?"](https://github.com/EtienneLamoureux/TQVaultAE#troubleshooting-and-faq)): close the game before opening the tool (and vice-versa). Closing the vault is when the inventories are saved.
