### ISSUE TITLE
Item transfer issues

### ISSUE THREAD

**Issue by yoninno** [EtienneLamoureux/TQVaultAE#290]
Hello,

My apologies for coming to you with an issue which may or may not be serious, but I have trouble using this tool for my TQ Anniversary Edition. I have the steam version of the game with the Ragnarok expansion. It was installed first. The TQ Vault 3.4.0 was downloaded later and used to save some items. The thing is, the items transferred to the vault are saved without problems. However, the inventory of my character is not modified. Also, when trying to transfer items back to any of the characters doesn't work either. The inventory is not modified and the items disappear from the vault.

Any help would be appreciated.

**Comment by hguy** [comment]
Hello,
It's because in order to make changes persistent you must close TQVaultAE (game files are altered when the tool is closing).
There is other restrictions, 
- You can't alter the current in game character (bags, equipment).
- The only way to interact with current in game character is by using caravan (Stash, Shared Stash, Relic Stash) and only when the in game caravan window is closed.

You can interact with off line character without restrictions (still need to close the tool for saving changes).

**Comment by ejfudd** [comment]
Most likely you have Steam Cloud enabled for Titan Quest AE and the cloud saves are being downloaded and overwriting your changes from TQVaultAE.  Please disable Steam Cloud synchronization either globally or for Titan Quest AE in the steam app.

**Comment by yoninno** [comment]
> Hello,
> It's because in order to make changes persistent you must close TQVaultAE (game files are altered when the tool is closing).
> There is other restrictions,
> 
>     * You can't alter the current in game character (bags, equipment).
> 
>     * The only way to interact with current in game character is by using caravan (Stash, Shared Stash, Relic Stash) and only when the in game caravan window is closed.
> 
> 
> You can interact with off line character without restrictions (still need to close the tool for saving changes).

Hi there,

Thank you for the suggestion. I have tried that as far as I can remember. I had some potions in the character inventory. To test, I closed the game. Transferred the potions from the character inventory to TQ Vault, closed it. Then I got into the game again and the potions were still there (and in the vault, too). I'll try again to make sure.

Thank you for the suggestion.

**Comment by yoninno** [comment]
> Most likely you have Steam Cloud enabled for Titan Quest AE and the cloud saves are being downloaded and overwriting your changes from TQVaultAE. Please disable Steam Cloud synchronization either globally or for Titan Quest AE in the steam app.

You're right about the cloud save. I mean, I never think about it in general so it must be enabled. Regardless, I thought that TQ Vault would overwrite that before it got uploaded to the cloud storage.
I'll try disabling it and then transferring the items. Thank you for the suggestion.

Regards.

**Comment by EtienneLamoureux** [comment]
The tool is meant for "offline" inventory management. See the answer to [Q. Can I use TQVaultAE while playing the game?](https://github.com/EtienneLamoureux/TQVaultAE#troubleshooting-and-faq) in our F.A.Q. section.

If you lot anything of value: no problem, see our [backup documentation](https://github.com/EtienneLamoureux/TQVaultAE/blob/master/README.md#features).
