### ISSUE TITLE
How to backup the Transfer Area & Relic Vault?

### ISSUE THREAD

**Issue by Hawawark** [EtienneLamoureux/TQVaultAE#294]
Dear all, 
First of all, a massive thank you for developing and maintaing this awesome tool for our beloved Titan Quest ! I hope everyone is ok in this difficult period. 

I've had issues with my Steam Cloud sync recently, as it reactivated itself and messed up with my save files.. I managed to backup my vault using the "Backup" files in TQVault folder. 

However, I'm not sure how to backup my Transfer Area and Relic Vault, They are in the backup files, but they are .dxb and I don't know how to manage these. I lost several items since this Steam Cloud incident, and I would love to back them up :-) 

Thanks in advance for any help !!

**Comment by afjback** [comment]
Transfer area backups (if any) saved as
**Transfer Stash** - Immortal Throne-winsys-20200330-223114-0278324-000.dxb
note1: bold part is localized, it depends on current TQVault language
note2: one need both dxb and dxg files
To restore rename files to winsys.* and move to savedata\sys.

Relic vault backup is broken for version 3.4, it saves dxb file only, but restoring only one file seems works ingame.

**Comment by Hawawark** [comment]
Thanks a lot, it worked !!  
I succeeded to use the "winsys" files to recover my old Transfer Stash, and the "miscsys" ones for the Relic Vault. 
Thanks a million, it feels so good to get my items back !!
