### ISSUE TITLE
System.IO.FileLoadException ERROR

### ISSUE THREAD

**Issue by Bogdand13** [EtienneLamoureux/TQVaultAE#295]
Hello,

Found a closed case without any further answers from user.

I have exact same issue:

Hello, 

I am 100% sure that I am using the 3.4 version.

![image](https://user-images.githubusercontent.com/63311426/78701033-fbd89680-790e-11ea-8a6c-01490b4617f9.png)

![image](https://user-images.githubusercontent.com/63311426/78701084-114dc080-790f-11ea-973d-5261c50dfdd3.png)

Thank you

**Comment by EtienneLamoureux** [comment]
Thanks for reporting, I've reopened https://github.com/EtienneLamoureux/TQVaultAE/issues/287
