### ISSUE TITLE
Fix creating the rest of the set from Ba'als Heart item

### ISSUE THREAD

**Issue by alexchevrier** [EtienneLamoureux/TQVaultAE#301]
Hi, got Ba'als Heart, trying to create the rest of the set returns an error.
I'll attach error and my vault
![image](https://user-images.githubusercontent.com/63609757/79149157-b72c7f80-7d94-11ea-9f4b-a1af51a47532.png)

[Main Vault.zip](https://github.com/EtienneLamoureux/TQVaultAE/files/4471194/Main.Vault.zip)

**Comment by ejfudd** [comment]
This looks like an issue with the DBRecord in the game.  The set datrabse record  `records\xpack3\items\set\x3set(09).dbr` references the following set items:
Armband
Greaves
Helm
Ring
The Greaves do not exist and your Torso item is not listed.  I would guess that they changed the greaves to a torso at some point and didn't update the set record.

**Comment by EtienneLamoureux** [comment]
There's not much we can do if the database is corrupted. At most we can replace the error dialog for something less intimidating, but that's most likely it.

**Comment by alexchevrier** [comment]
if I manage to get all the other items in a vault, would that help ?

**Comment by EtienneLamoureux** [comment]
Unfortunately no: the problem is in the game's data. The devs need to fix the game's data, then the vault will pick it up and work as expected.

**Comment by ejfudd** [comment]
I have created issue [#41430](https://redmine.thqnordic.com/issues/41430) on the developer site for this.
