### ISSUE TITLE
Rearrange classic tooltip so that base properties display first

### ISSUE THREAD

**Issue by ejfudd** [EtienneLamoureux/TQVaultAE#312]
This sounds like a duplicate of #296 but splits the issue into two parts.
This covers the simple part of just showing the base properties first without any extra sorting. 

This would require a change to the order of the classic display in `ItemToolTip.FillToolTip()`
as follows:
```
foreach (var str in Data.BaseAttributes) AddRow(str);
foreach (var str in Data.PrefixAttributes) AddRow(str);
foreach (var str in Data.SuffixAttributes) AddRow(str);
```

**Comment by EtienneLamoureux** [comment]
Thanks for that. Splitting the effort for a fix is fine, but I'll still track it as a simple ticket.
