### ISSUE TITLE
Player file corrupted when items placed in stash.

### ISSUE THREAD

**Issue by ejfudd** [EtienneLamoureux/TQVaultAE#317]
You are no longer able to load the player file after placing an item into the player stash or one of the stash bags.  It appears that the value for `itemPositionsSavedAsGridCoords` in the player file is not getting its value saved.  At this point TQVault can no longer load the file though the game still does load the character.  In game all of the inventory items will disappear and the extra bags will be gone.

**Comment by hguy** [comment]
Bug explained in #316

**Comment by ejfudd** [comment]
Duplicate of #316
