### ISSUE TITLE
Can't use any version of TQVault [System.IO.IOExceptions]

### ISSUE THREAD

**Issue by Fagnerk** [EtienneLamoureux/TQVaultAE#32]
I got this errors everytime i make any changes and click the exit button.
Windows 10 and TQAE: Ragnarock (Steam)

https://imgur.com/a/REX93

**Comment by EtienneLamoureux** [comment]
Does the character have Ragnarök items?

**Comment by Fagnerk** [comment]
No. I  didn't reach act 5 yet.
I made some tests last night. If I make changes in vaults I created  everything is ok. The error happens just when i make changes in the characters bag.

**Comment by KenAlin** [comment]
Hi,
It seems there is an "old" backup directory in your game data.

Go to `C:\Users\<username>\Documents\My Games\Titan Quest - Immortal Throne\SaveData\Main\<character name>`

You'll find a directory named `Backup-moved by TQVault`. Rename it : add "_old" at the end, for example.
I'm unsure if it's safe to delete it.

**Comment by EtienneLamoureux** [comment]
There's a logical issue in `TQData.BackupStupidPlayerBackupFolder`. I should be able to fix this.

**Comment by NorthFury** [comment]
It is safe to delete all backup folders.

**Comment by epinter** [comment]
Seems to be the same problem as this issue: https://github.com/EtienneLamoureux/TQVaultAE/issues/35

The Directory.Delete exception can be caused by a antivirus, read-only folder, antiransomware or anything blocking a folder deletion.

I could stop moving the backup, or add a try-catch.

**Comment by EtienneLamoureux** [comment]
Deleting the folder could probably stay, but crashing the whole thing just sounds like bad error handling.
We'll just have to verify that not being able to move that folder doesn't cause any other problems.

**Comment by epinter** [comment]
Changed the BackupStupidPlayerBackupFolder method, maybe this helps with the problem: https://github.com/EtienneLamoureux/TQVaultAE/pull/52. Test build: 
[TQVaultAE-testbuild-20180101.zip](https://github.com/EtienneLamoureux/TQVaultAE/files/1596201/TQVaultAE-testbuild-20180101.zip)

**Comment by epinter** [comment]
Solved with PR https://github.com/EtienneLamoureux/TQVaultAE/pull/52
