### ISSUE TITLE
Bug or trick? Infinite resource

### ISSUE THREAD

**Issue by darkforce01** [EtienneLamoureux/TQVaultAE#330]
So, after i downloaded TQvault, i found this very cool to saving time farming relic or essence. First open your TQ game and put item you need in your inventory. Next, open your TQ vault, put item you want to duplicate from your inventory to your vault. Next, close TQvault, then go to TQ game and press Inventory(I) button, the items you just moved to TQvault should be in your inventory still. Then open TQvault again. BAAAM, you got 2 of them(one in your TQvault and one in your inventory), after that you close both TQvault and relogin the game. Im using this to get right charm or essence bonus, see if this work to you guys.

**Comment by hguy** [comment]
It's not a bug.
TQVault cannot change the inventory of the "current in game character". It can read it only.
By the way, TQVault allow item duplication. So you can farm everything you already own.

![image](https://user-images.githubusercontent.com/31834707/80189949-c40e6600-8613-11ea-92d4-329d95ed7418.png)

**Comment by EtienneLamoureux** [comment]
Glad you're enjoying the tool! I do not recommend having both the tool and the game open at the same time: a wrong manipulation could cause you to lose progress. Fortunately, item duplication is a built-in feature of the tool!

You can check out these sections of [our F.A.Q.](https://github.com/EtienneLamoureux/TQVaultAE#troubleshooting-and-faq):
- Q. Can I use TQVaultAE while playing the game?
- Q. How to enable/disable the cheats (character edition, item edition, item copy)?

**Comment by darkforce01** [comment]
thanks, i really enjoy TQvault, best for item collector like me. but personally im still looking a short cut for fast transfer item(like the right click in-game when you move item from inventory to stash), theres no problem with the current version (or i think so)but moving item using right-click and click move seem pretty...slow and sometime annoying me. but hey again thanks for the feedback, love it.    Vào 20:16:43 GMT+7, Thứ Sáu, 24 tháng 4, 2020, Etienne Lamoureux <notifications@github.com> đã viết:  
 
 


Closed #330.

**Comment by EtienneLamoureux** [comment]
Other options for bulk-transfer are also available:
- <kbd>CTRL</kbd>+<kbd>A</kbd> to select everything in the current vault
- <kbd>CTRL</kbd>+<kbd>click</kbd> on multiple items to select them all
then you can right-click --> move to...
