### ISSUE TITLE
What's the difference between Copy and Duplicate?

### ISSUE THREAD

**Issue by renbear67** [EtienneLamoureux/TQVaultAE#331]
The menus feature both "copy" and "duplicate" actions, but no explanation is given. Please consider adding something in the project's README.md explaining the difference. Thanks in advance!

**Comment by EtienneLamoureux** [comment]
- Copy: copying an item will create an exact copy of the item, including the prefix, suffix, slotted relic/charm. However, the rolled stats will be different.
- Duplicate: duplicating an item will create an exact copy of the item, including the prefix, suffix, slotted relic/charm *and seed*. This means that the rolled stats will be identical.
