### ISSUE TITLE
TQVaultAE does not start

### ISSUE THREAD

**Issue by vd59** [EtienneLamoureux/TQVaultAE#337]
Version 3.6.0 does not start. Nothing helps!!! And 3.4.0 works without problems !!! STIM not installed

**Comment by EtienneLamoureux** [comment]
Is there an error message of any kind?

**Comment by vd59** [comment]
моя игра:
D:\1. Installed games\Titan Quest - Anniversary Edition  и ничего не помогает!!!!!!!!

  
>Пятница, 1 мая 2020, 17:58 +05:00 от Etienne Lamoureux <notifications@github.com>:
> 
> 
>Is there an error message of any kind?
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
Виталий Данильченко

**Comment by vd59** [comment]
Вот что!!! Не помогает!!!!!

  
>Пятница, 1 мая 2020, 17:58 +05:00 от Etienne Lamoureux <notifications@github.com>:
> 
> 
>Is there an error message of any kind?
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
Виталий Данильченко

**Comment by vd59** [comment]
`[
![Screenshot_1](https://user-images.githubusercontent.com/34639562/80807743-6495f480-8bd7-11ea-9577-adeaf9dc804d.png)
](url)`

**Comment by vd59** [comment]
>Пятница, 1 мая 2020, 17:58 +05:00 от Etienne Lamoureux <notifications@github.com>:
> 
> 
>Is there an error message of any kind?
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
Виталий Данильченко

**Comment by EtienneLamoureux** [comment]
Ok, so it says:
|Russian|English|
|--|--|
|моя игра|my game|
|и ничего не помогает|and nothing helps|
|Вот что!!! Не помогает!!!!!|That's what!!! Does not help!!!!!|

And the screenshot provided is 
![screenshot](https://user-images.githubusercontent.com/34639562/80807743-6495f480-8bd7-11ea-9577-adeaf9dc804d.png)

I see your problem: the XML is not correct. Please use the following: 
Я вижу вашу проблему: XML не является правильным. Пожалуйста, используйте следующее:
```xml
<setting name="TQITPath" serializeAs="String">
    <value>D:\1. Installed games\Titan Quest - Anniversary Edition</value>
</setting>
<setting name="TQPath" serializeAs="String">
    <value>D:\1. Installed games\Titan Quest - Anniversary Edition</value>
</setting>
```

**Comment by vd59** [comment]
I do not know what to do!!!! Nothing helps !!! ???

  
>Пятница, 1 мая 2020, 19:17 +05:00 от Etienne Lamoureux <notifications@github.com>:
> 
> 
>Reopened  #337 .
>—
>You are receiving this because you modified the open/close state.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
Виталий Данильченко

**Comment by EtienneLamoureux** [comment]
XML не является правильным. Пожалуйста, используйте следующее:

<setting name="TQITPath" serializeAs="String">
    <value>D:\1. Installed games\Titan Quest - Anniversary Edition</value>
</setting>
<setting name="TQPath" serializeAs="String">
    <value>D:\1. Installed games\Titan Quest - Anniversary Edition</value>
</setting>

Файл должен пройти этот тест:
https://www.xmlvalidation.com/

**Comment by EtienneLamoureux** [comment]
Я исправил ваш файл. Используйте этот файл конфигурации.

[config file.zip](https://github.com/EtienneLamoureux/TQVaultAE/files/4564748/config.file.zip)

**Comment by vd59** [comment]
Make a normal TQVault, such as 3.4.0 and ALL !!!!

  
>Пятница, 1 мая 2020, 19:42 +05:00 от Etienne Lamoureux <notifications@github.com>:
> 
> 
>Я исправил ваш файл. Используйте этот файл конфигурации.
>config file.zip
>—
>You are receiving this because you modified the open/close state.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
Виталий Данильченко

**Comment by vd59** [comment]
Works!!!!!!!!!!!!!!!!!!!!!!!!!! Thank!!!!!!!!!!!!!!!!!!!!

  
>Пятница, 1 мая 2020, 19:43 +05:00 от Виталий Данильченко <vd59@bk.ru>:
> 
>Make a normal TQVault, such as 3.4.0 and ALL !!!!
>
> 
>>Пятница, 1 мая 2020, 19:42 +05:00 от Etienne Lamoureux < notifications@github.com >:
>> 
>> 
>>Я исправил ваш файл. Используйте этот файл конфигурации.
>>config file.zip
>>—
>>You are receiving this because you modified the open/close state.
>>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
> 
> 
>--
>Виталий Данильченко
>  
 
 
--
Виталий Данильченко

**Comment by vd59** [comment]
ok!!!!!

  
>Пятница, 1 мая 2020, 20:00 +05:00 от Etienne Lamoureux <notifications@github.com>:
> 
> 
>Closed  #337 .
>—
>You are receiving this because you modified the open/close state.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
Виталий Данильченко

**Comment by vd59** [comment]
I installed a new Win 10 LTSC and Vault again does not work !!!!!! 3.8.0. On the old Win 10 LTSC works!

**Comment by vd59** [comment]
[
![Screenshot_1](https://user-images.githubusercontent.com/34639562/124960772-19c30880-e036-11eb-939b-1cafff19aa78.png)
](url)
