### ISSUE TITLE
Fix the Strength requirement for "Tachylite Kopis"

### ISSUE THREAD

**Issue by afjback** [EtienneLamoureux/TQVaultAE#342]
Vault says 383 strength
![kopis-vault-or8](https://user-images.githubusercontent.com/53652815/82106743-8771ee00-972b-11ea-8299-e65fb6c02d18.png)
While game displays only 1
![kopis-game-or8](https://user-images.githubusercontent.com/53652815/82106745-8c36a200-972b-11ea-8a70-d5d9ab96eec5.png)
[kopis.zip](https://github.com/EtienneLamoureux/TQVaultAE/files/4637628/kopis.zip)

**Comment by EtienneLamoureux** [comment]
Is your character using any "-% to requirements", or the [run mastery](https://titanquest.fandom.com/wiki/Runeword:_Feather)?

**Comment by afjback** [comment]
No, just retested with new lv1 character
![screenshot07](https://user-images.githubusercontent.com/53652815/82374237-6fe67e00-9a27-11ea-9e85-bd5e120a4eb8.jpg)
Interesting thing that internally the item has reqs: 450 int and 1 str. I have no idea where 450 dex and 383 str come from. 

augmentMasteryLevel1,1,
augmentMasteryName1,records\skills\earth\earthmastery.dbr,
augmentSkillLevel1,3,
augmentSkillName1,records\xpack3\skills\allmasteries\earth_firenova.dbr,
bitmap,XPack3\items\equipmentweapon\sword\uibitmaps\u_sword01.tex,
castsShadows,1,
characterBaseAttackSpeed,0.450000,
characterBaseAttackSpeedTag,CharacterAttackSpeedVeryFast,
characterLifeRegen,10.000000,
characterManaRegen,10.000000,
Class,WeaponMelee_Sword,
defensiveCold,-50.000000,
defensiveFire,80.000000,
dropSound,Records\Sounds\SoundPak\Items\SwordDropPak.dbr,
dropSound3D,Records\Sounds\SoundPak\Items\SwordDrop3DPak.dbr,
dropSoundWater,Records\Sounds\SoundPak\Items\WaterMdDropPak.dbr,
FileDescription,1,
hidePrefixName,1,
hideSuffixName,1,
hitSound,Records\Sounds\SoundPak\Weapons\SwordHitPak.dbr,
**intelligenceRequirement,450,**
itemClassification,Legendary,
itemCostName,records\game\itemcost_uniquelegendary_primary.dbr,
itemLevel,72,
itemNameTag,x3tagU_Sword01,
itemSkillAutoController,records\xpack3\skills\item skills\ai controllers\onanyhitself02.dbr,
itemSkillLevel,3,
itemSkillName,records\xpack3\skills\allmasteries\earth_firenova.dbr,
maxTransparency,0.500000,
mesh,XPack3\items\equipmentweapon\sword\u_sword01.msh,
offensiveBaseFireMin,160.000000,
offensiveFireModifier,60.000000,
offensiveFumbleDurationMin,3.000000,
offensiveFumbleGlobal,1,
offensiveFumbleMin,20.000000,
offensiveGlobalChance,25.000000,
offensivePhysicalMax,28.000000,
offensivePhysicalMin,18.000000,
offensivePierceRatioMin,10.000000,
offensiveProjectileFumbleDurationMin,3.000000,
offensiveProjectileFumbleGlobal,1,
offensiveProjectileFumbleMin,40.000000,
offensiveSlowFireDurationMin,3.000000,
offensiveSlowFireGlobal,1,
offensiveSlowFireMin,20.000000,
offensiveSlowFireModifier,60.000000,
retaliationFireChance,33.000000,
retaliationFireMin,120.000000,
scale,1.200000,
shadowBias,0.010000,
**strengthRequirement,1,**
swipeSound,Records\Sounds\SoundPak\Weapons\SwordSwipePak.dbr,
templateName,database\Templates\Weapon_Sword.tpl,
weaponTrail,Records\Effects\weapontrail\Default_Sword.dbr,

**Comment by ejfudd** [comment]
Basically all items have a set of requirements based on their item level which can be found in records\game\itemcost.dbr.  There are also some requirements that can come from the individual item's database record.  In TQVault, it appears that the calculated requirements are overwriting the requirements that come from the database record.

A simple fix would be to prioritize the item record values over the calculated values.
In `ItemProvider.GetDynamicRequirementsFromRecord()` starting at line 1031.
change
```
if (requirements.ContainsKey(key))
{
	if (string.Compare(value, ((Variable)requirements[key]).ToStringValue(),StringComparison.OrdinalIgnoreCase) <= 0)
		return;

	requirements.Remove(key);
}
```

to this:
```
if (requirements.ContainsKey(key))
	continue;
```

I'm not exactly sure why that string comparison is in there as it would abort the remaining requirement calculations if the calculated value was lower than the value from the item record.  Otherwise it just blindly removes the existing value.
