### ISSUE TITLE
Fix displayed stats in the tool to better reflect the in-game values

### ISSUE THREAD

**Issue by mumu-cat** [EtienneLamoureux/TQVaultAE#344]
Number of armor is wrong

TQV
+2.5
+50%
GAME
+3.5
+57%
![2020-05-23_202201](https://user-images.githubusercontent.com/65813374/82729828-414bfa00-9cea-11ea-9d70-6a619e26dbfa.png)

**Comment by EtienneLamoureux** [comment]
Please see [our F.A.Q.](https://github.com/EtienneLamoureux/TQVaultAE#troubleshooting-and-faq): Q. Does TQVaultAE modify my items? The stats I see are not the same as the ones ingame.
