### ISSUE TITLE
New interface language: brazilian portuguese

### ISSUE THREAD

**Issue by Klauhs** [EtienneLamoureux/TQVaultAE#346]
How do I translate? What programs to use? I would like to translate it into Brazilian Portuguese.
Thank you.

**Comment by EtienneLamoureux** [comment]
Hi,

First of all, thank you for your interest in the project!
You can download the base translation file [here](https://github.com/EtienneLamoureux/TQVaultAE/blob/master/src/TQVaultAE.Presentation/Resources.resx). You simply need to open it and replace all the text between value tags (`<value>...</value>`) by the appropriate phrase in Brazilian Portuguese.

Programs you could use:
- Microsoft Visual Studio 2019 (Community Edition)
  - It's a big download just for editing a translation file, but it has the better looking editor.
- Notepad++
  - It can open XML files without problems, and supports the structure very well
  - If you only plan on translating, I would suggest this one

**Comment by Klauhs** [comment]
Hello
Thank you for giving the file for translation. I translated using the program "AutoResxTranslator.v2.1". But I would like to ask you, if possible to make the file "Resources.resx" available in Spanish as well; because it would be easier for me to revise and correct the translation. I opened the file "TQVaultAE.Presentation.resources.dll" in Spanish to facilitate the corrections of the translation but there it complicated kkkk. I repeat, with "Resources.resx" in Spanish it would make it easier.
Another question is: How to replace the "TQVaultAE" files for testing the translation. Or should I just translate "Resources.resx" and modify it on the download page "https://github.com/EtienneLamoureux/TQVaultAE/blob/master/src/TQVaultAE.Presentation/Resources.resx" so that you can include it in the next update.
Thank you

**Comment by EtienneLamoureux** [comment]
Fantastic!

It would be hard to test the file without building the solution on your local computer. I can bundle it in the next release and if you notice any mistakes, we can always patch later. You can give it to me by zipping it (in a `.zip` file) and drag-drop it in here.

Finally, here is the [Spanish translation file](https://github.com/EtienneLamoureux/TQVaultAE/blob/master/src/TQVaultAE.Presentation/Resources.es.resx) (there might be some missing strings towards the end).

**Comment by Klauhs** [comment]
Bonjour EtienneLamoureux
J'ai terminé la correction et j'envoie le fichier avec un bref résumé. J'attends avec impatience votre approbation et mise à jour de TQVaulAE. Je vous remercie.
[Resources and readme.zip](https://github.com/EtienneLamoureux/TQVaultAE/files/4858771/Resources.and.readme.zip)

Hello EtienneLamoureux
I finished the correction and am sending the file with a short summary. I look forward to your approval and update of TQVaulAE. Thank you

**Comment by Klauhs** [comment]
THANK YOU THANK YOU

**Comment by Klauhs** [comment]
Hello
  I would like to know if you have already updated Resources.resx, in PT, BR so that I can make improvements in the translation. Now that I already have TQVaultAE 3.7.1 in PT, BR and I know where the texts fit, I intend to modify them so that they have a better fit and visualization.
Another thing is that the program is not linking to the original translation of the game and the items and appear in English. I send a capture photo in the zip file.
[TAVaultAE_3.7.1 - Screenshot.zip](https://github.com/EtienneLamoureux/TQVaultAE/files/4889494/TAVaultAE_3.7.1.-.Screenshot.zip)

**Comment by EtienneLamoureux** [comment]
The current translation file is here: https://github.com/EtienneLamoureux/TQVaultAE/blob/master/src/TQVaultAE.Presentation/Resources.pt.resx

For the items' text: that one is on me, I'll fix it.

**Comment by EtienneLamoureux** [comment]
@Klauhs Release 3.7.2 has the fix for the item names/stats. The bug was due to the game using the non-standard `br` code for brazilian portuguese (instead of the ISO `pt-BR` code). 

I created https://github.com/EtienneLamoureux/TQVaultAE/issues/350 for the "Level" issue.

**Comment by Klauhs** [comment]
Hello
I finished the 2nd correction and I am sending the file with short summaries and a problem. Thank you
[Resource + Feedback.zip](https://github.com/EtienneLamoureux/TQVaultAE/files/4902000/Resource.%2B.Feedback.zip)

**Comment by Klauhs** [comment]
Hello again
Please use this latest version of "Resources.pt .resx". The latter, at least for Atlantis, I hope.
[Resources.pt .resx (Latest Version).zip](https://github.com/EtienneLamoureux/TQVaultAE/files/4904179/Resources.pt.resx.Latest.Version.zip)
