### ISSUE TITLE
Fix issue with certain modded items

### ISSUE THREAD

**Issue by williamNadeauGervais** [EtienneLamoureux/TQVaultAE#347]
I had reported an issue a while ago about a modded character that would make Vault crash because it used a skill that started with "Temp"; a keyword in programmation, I believe.

I've found something similar : loading a character that has (in its inventory or storage area) a modded item that starts with "For"; another keyword in programmation (which makes me believe that's the issue.)

The resulting error message goes like this.
![Capture](https://user-images.githubusercontent.com/60615001/85951152-43c7f200-b92f-11ea-8e80-b3b779095f22.PNG)

When ignored, the container will be unusable or very buggy. It displays wide boxes with a red X inside that cover the affected area.

**Comment by ejfudd** [comment]
The previous issue was related to the skill name starting with the same text as one of the item tags.
This looks a bit different in that it's complaining about parenthesis in the expression parser during the calculation of the dynamic requirements.
It would be helpful for you to specify which particular mod you are using and to upload the character file which is causing the issue.

**Comment by williamNadeauGervais** [comment]
The mod used is Shadow Champions on its latest version. https://steamcommunity.com/sharedfiles/filedetails/?id=1949340853

The character : https://mega.nz/file/0Is1HThZ#lSnH85w5InuaM42PczvYiogxLXz8D_aTJEPLjOFs0Cc 
The item in cause is the leg armor called "Forgotten Boots". It's in the first additional bag of its inventory.

**Comment by hguy** [comment]
This mod have "warning and notices" very well done.
They know already that it may have problems with TQVault.
![image](https://user-images.githubusercontent.com/31834707/92302528-639e1680-ef6d-11ea-8bc9-160c6284d602.png)

**Comment by hguy** [comment]
The math expression is coming from de mod database so this is not a TQVault issue but a mod issue.

![image](https://user-images.githubusercontent.com/31834707/92304548-4d995180-ef7f-11ea-9a7e-c416916e14ce.png)

**Comment by williamNadeauGervais** [comment]
Oh, I would've never figured it out! Thank you for your help :)
