### ISSUE TITLE
Fix missing czech language from "Language selection"

### ISSUE THREAD

**Issue by Sir-Mac** [EtienneLamoureux/TQVaultAE#349]
Hi, EtienneLamoureux, 

thank you for the newest installment of "TQ Vault AE", but in the version 3.7.0, I can't pick "Czech" (language) from the dropdown selection menu, when I configure the program... 

The czech language was dropped out of the program or what happened? As a native Czech, I am quite used to the localization of your program in Czech.

Thanks in advance for fixing ... 
Sir-Mac
![Czech is missing](https://user-images.githubusercontent.com/50591247/86749640-b2970080-c03d-11ea-9003-53e740861bff.png)

**Comment by EtienneLamoureux** [comment]
Thanks for the report. The [new release (3.7.1)](https://github.com/EtienneLamoureux/TQVaultAE/releases/tag/3.7.1), is fixed.
