### ISSUE TITLE
OneDrive Integration+(non)multilingual TQVault=failing to locate savedata

### ISSUE THREAD

**Issue by cure-neet** [EtienneLamoureux/TQVaultAE#35]
Hi. I'm Japanese and i guess other multibyte language players are encountering this problem,

Summary:
latest Windows 10 integrated OneDrive and create "documents" directory same as our "mother tongue"... like "dokyumento (japanese, katakana. or maybe korean, chinese, and so on)"
and, present TQVaultAE doesn't have any i18n function... or at least character savedata directory.

Result:
failed writing character savedata. writing to Vaults themselves is okay. (of course Vaults' path is ASCII)

error message:
https://i.imgur.com/3MNEzje.png

temporal solution:
disabling OneDrive (I'm stupid.)

btw i don't have Ragnarok.
I hope Etienne fix it someday.
thanks

**Comment by epinter** [comment]
See https://github.com/EtienneLamoureux/TQVaultAE/issues/32.
