### ISSUE TITLE
How to fix "The Stash file cannot be found."

### ISSUE THREAD

**Issue by Klauhs** [EtienneLamoureux/TQVaultAE#351]
TQVault no longer recognizes the characters in the game. I visited the caravan guide in the game but it doesn't help. I created a new epersonage and nothing.

**Comment by EtienneLamoureux** [comment]
Can you provide a screenshot of the error? Is not, could you
1. Click the title of the error dialog
2. Press <kbd>Ctrl</kbd>+<kbd>C</kbd>
3. Open a new comment on this issue
4. Press <kbd>Ctrl</kbd>+<kbd>V</kbd>

**Comment by Klauhs** [comment]
Yes, there they are.
---------------------------
Cannot find Stash file.
---------------------------
The Stash file cannot be found.

Please visit the Caravan Trader in game to create the file.

The Storage Area tab will be unavailable for this character.

Character : Artemis, Dreamkiller - Level : 19
---------------------------
OK   
---------------------------
[Cannot find Stash file.zip](https://github.com/EtienneLamoureux/TQVaultAE/files/4912552/Cannot.find.Stash.file.zip)

**Comment by Klauhs** [comment]
See too
https://github.com/EtienneLamoureux/TQVaultAE/issues/346

**Comment by Klauhs** [comment]
Yes, there they are.
______________________________________________________________________
Cannot find Stash file.

The Stash file cannot be found.
Please visit the Caravan Trader in game to create the file.

The Storage Area tab will be unavailable for this character.
Character : Artemis, Dreamkiller - Level : 19

OK
___________________________________________________________________
[Cannot find Stash file.zip](https://github.com/EtienneLamoureux/TQVaultAE/files/4912704/Cannot.find.Stash.file.zip)

See too https://github.com/EtienneLamoureux/TQVaultAE/issues/346

**Comment by Klauhs** [comment]
-->(HELPE ME)<--

Cannot find Stash file.       

The Stash file cannot be found.
Please visit the Caravan Trader in game to create the file.
The Storage Area tab will be unavailable for this character.

Character : Artemis, Dreamkiller - Level : 19
![Screenshot_a](https://user-images.githubusercontent.com/67174762/87361450-a1b92400-c542-11ea-8bdb-4131d01681ee.jpg)

**Comment by hguy** [comment]
Try to go in your TQ save directory `C:\Users\{YourNameHere}\Documents\my games\Titan Quest - Immortal Throne\SaveData\Main\_Artemis`.

Tell us if you see only the two `winsys.dx?` files ?

It should look like this.
![image](https://user-images.githubusercontent.com/31834707/91905140-5ac7ef00-eca6-11ea-8af0-05c22ceb5e70.png)

**Comment by Klauhs** [comment]
I had deleted these files, "I don't remember why", but the game always created others. But this time it did not create and had not been backed up. I uninstalled the game, reset Steam, among others, but I only managed to solve the problem by formatting the PC. I will close this matter.
Thank you for your help.
