### ISSUE TITLE
How to fix "The element <value> may appear once in a given section."

### ISSUE THREAD

**Issue by Panfri3d** [EtienneLamoureux/TQVaultAE#353]
Same issue as #91 and #226. After following the guide for FAQ, the tqvaultAE does not open at all. 
Inserted is the log file.
[TQVaultAE_2020.07.21.txt](https://github.com/EtienneLamoureux/TQVaultAE/files/4951298/TQVaultAE_2020.07.21.txt)
Please explain to me like I'm an idiot as i have 0 coding experience

**Comment by EtienneLamoureux** [comment]
Could you attach your configuration file? It seems there might be an issue with it.

**Comment by Panfri3d** [comment]
[TQVaultAE.Config.dll.zip](https://github.com/EtienneLamoureux/TQVaultAE/files/4974603/TQVaultAE.Config.dll.zip)
Here it is. Thanks

**Comment by EtienneLamoureux** [comment]
Alright, a few questions:
- Does the tool open and work if you get the [latest version](https://github.com/EtienneLamoureux/TQVaultAE/releases/tag/3.7.3) and not change anything?
- Do you have the game through Steam?
- What did you change in the config file originally?

**Comment by Panfri3d** [comment]
1) No it does not. It mentions that there is a path error
2) Yep
3) For the config file, I only followed the instructions for error loading resources

**Comment by hguy** [comment]
logs are pretty clear.
![image](https://user-images.githubusercontent.com/31834707/91903645-dc6a4d80-eca3-11ea-8daf-17988b457eee.png)

@Panfri3d the config file you provide is not the right one.
It's your `D:\SteamLibrary\steamapps\common\Titan Quest Anniversary Edition\TQVaultAE.exe.Config` that have a problem.

**Comment by EtienneLamoureux** [comment]
See [this answer](https://github.com/EtienneLamoureux/TQVaultAE/issues/355#issuecomment-686520220) and tell us if that helps.
