### ISSUE TITLE
Correctly load last character when opening the tool, regardless of the valu of the "Pre-Load All Vault and Character Files" option

### ISSUE THREAD

**Issue by icefreeze88** [EtienneLamoureux/TQVaultAE#354]
The issue as the tittle showed. I noticed this is as issue because it doesn't happen with v3.1.1 (i still using it because this issue).
If i tick "Pre-load All Vault and Character Files", time to start TQVault is alot longer than untick it on v3.7.3
I'm using the .zip tqvault download file.

**Comment by EtienneLamoureux** [comment]
Which character does it load? Nothing, or the first of the list?

@hguy You touched the loading code not too long ago. Could it have possibly caused the issue described in the title?

**Comment by icefreeze88** [comment]
It shows nothing, like fresh new use.

**Comment by hguy** [comment]
> 
> @hguy You touched the loading code not too long ago. Could it have possibly caused the issue described in the title?

I confirm a problem on the LastCharacterLoad since refacto.
There's a PR for that in waiting.
