### ISSUE TITLE
Fix character from not appearing in menus after resetting masteries

### ISSUE THREAD

**Issue by Xirious** [EtienneLamoureux/TQVaultAE#357]
Hi there,

So I'd like to reset my masteries (not so happy with Nature). However, the character disappears when I try using TQVault to reset masteries. Here is a copy of the character and setting I'm running:

[Titan Quest - Immortal Throne_backup_2020.zip](https://github.com/EtienneLamoureux/TQVaultAE/files/5211285/Titan.Quest.-.Immortal.Throne_backup_2020.zip)

Please advise what can be done? I am almost sure this is a bug.

I can add images but I don't think it's necessary. 
I make sure I exit TQVault long before I start the game up. 

I have to copy this backup back before the character is seen again by TQ but I can still see it in TQVault (with the Masteries reset).

**Comment by hguy** [comment]
Thanks to notice !
I just provide a fix for this.

**Comment by colinschwegmann** [comment]
Thanks for the fix @hguy!

Any chance of a release build soon?

**Comment by EtienneLamoureux** [comment]
@colinschwegmann How about now? :)
https://github.com/EtienneLamoureux/TQVaultAE/releases/tag/3.7.4

**Comment by Xirious** [comment]
@EtienneLamoureux Thank you so much! That fixed worked and thanks for the release (forgot to switch my account on my work PC to reply).
