### ISSUE TITLE
If i using both v3.7.4 and v3.1.1 can be cause characters that open with v3.7.4 disable Epic and Legendary difficulties.

### ISSUE THREAD

**Issue by icefreeze88** [EtienneLamoureux/TQVaultAE#359]
As the tittle said, i still keep TQVaultAE v3.1.1 (because it's the most stable version for me) on the desktop, and when i using v3.7.4, i created its shortcut on Desktop near v3.1.1's shortcut. So as the habit, i start v3.1.1 when i intent to start with v3.7.4. After that, i quit v3.1.1 then run v3.7.4. The character that load the last of 2 TQVault version is different. And when start game, character that i load last time with v3.7.4 be disable Epic and Legendary difficulty mode at character selection window; character that load with v3.1.1 last time still ok.

**Comment by EtienneLamoureux** [comment]
Thank you for the bug report.
We're not keeping versions backwards-compatible at this time. The data files may allow it of course, but it is not an officially supported feature.
If you let us know of the instabilities you're experiencing in the latest release, we can track and work on them.
