### ISSUE TITLE
Allow saving without closing the tool (with a "Save" button)

### ISSUE THREAD

**Issue by Klauhs** [EtienneLamoureux/TQVaultAE#360]
Just a suggestion
Place a Save button in TQVault to avoid losing work when improper closure occurs.
Example: PC or program error or power failure. Because the only way to save is to close TQVault.
In the older ones there was a save button. Thank you.

**Comment by hguy** [comment]
related to #283

**Comment by EtienneLamoureux** [comment]
@Klauhs Thanks for the suggestion! We'll reference it in #283 and close this one.
