### ISSUE TITLE
How to fix the "Bad Language Path" error?

### ISSUE THREAD

**Issue by slacker-king** [EtienneLamoureux/TQVaultAE#361]
I can't seem to get past the Bad Language Path issue on startup. I looked at the FAQ and manually set the config file settings, as described. See screenshot.

How can I get TQVaultAE working?

![image](https://user-images.githubusercontent.com/23318158/95472940-96af3d80-0951-11eb-932c-c6ca2064e3a9.png)

**Comment by hguy** [comment]
Hello
can you share the config file and the content of the Logging sub directory ?

**Comment by slacker-king** [comment]
I've attached both files. The config file had to be renamed .TXT to upload.

Btw, here are my paths:

**TQ IT** - C:\Users\Slacker\Documents\My Games\Titan Quest - Immortal Throne
**TQ AE** - C:\Users\Slacker\Documents\My Games\SteamLibrary\steamapps\common\Titan Quest Anniversary Edition

Let me know if you need anything else. Thanks.

[TQVaultAE.exe.config.txt](https://github.com/EtienneLamoureux/TQVaultAE/files/5396366/TQVaultAE.exe.config.txt)
[TQVaultAE_2020.10.17.txt](https://github.com/EtienneLamoureux/TQVaultAE/files/5396367/TQVaultAE_2020.10.17.txt)
