### ISSUE TITLE
Fix right-click on Ba'als hand

### ISSUE THREAD

**Issue by LIyahLIweth** [EtienneLamoureux/TQVaultAE#364]
Ba'als Heart works normally but Ba'als Hands doesn't let me right click it. I want to make a copy/duplicate of it. 

Ba'als heart and Hand are in C.Sets TAB 2  

[C.Sets.zip](https://github.com/EtienneLamoureux/TQVaultAE/files/5810018/C.Sets.zip)

Photo
![TitanQuest](https://user-images.githubusercontent.com/77404131/104483734-34488780-55a7-11eb-9782-ae0bf804f4c1.jpg)

**Comment by EtienneLamoureux** [comment]
Related to https://github.com/EtienneLamoureux/TQVaultAE/issues/227
