### ISSUE TITLE
How to freely add attributes?

### ISSUE THREAD

**Issue by Zack583** [EtienneLamoureux/TQVaultAE#366]
Version 3.7.4.0, I need to add skill points to my character to a test but it seems not possible without increasing the level of the character

**Comment by EtienneLamoureux** [comment]
The character editing features restrict you to making "legal" characters. This means you cannot freely add attribute points without either levelling or reducing other attributes. [Other projects](https://github.com/epinter/tqrespec) seem to have similar restrictions.

**Comment by Zack583** [comment]
Well, adding a skill point without increasing the level would save my character in this case, I lost a skill point by testing a script

**Comment by EtienneLamoureux** [comment]
You might be able to restore your affected character from a backup, which are created automatically during the tool's use. The location of those backups is described at the bottom of the [features section](https://github.com/EtienneLamoureux/TQVaultAE#features) of the documentation.

Unfortunately, that feature as described is outside the scope of the project, which aims to be an inventory management tool. The addition of character editing features was a contentious one and there are no plans at present to develop them further. We do not aim to re-implement the old TQ Defiler project.

Of course, you're free to download the source and adjust the project to your needs.

**Comment by Zack583** [comment]
Before I thought that TQ Defiler would not work due to outdated, but this worked to this case, thanks
