### ISSUE TITLE
How to fix "ConfigurationErrorsException"?

### ISSUE THREAD

**Issue by StragaSevera** [EtienneLamoureux/TQVaultAE#367]
I'm trying to make TQ Vault run under Wine, and it always throws this error after I select the directory of the game:
https://i.imgur.com/5QcuTA8.png

Even when I manually set the installation directory in config like FAQ says, it still asks me for a directory and crashes after I select it.

I understand that you may not support the Wine, but still, if you would help me, I would be very happy =-)

**Comment by EtienneLamoureux** [comment]
Correct, Wine is not officially supported. 

That being aid, I think I may help. It looks like, while editing the XML configuration file, you might have broken the structure. Make sure there's only 1 section defined as "userSettings" and that the file is uses a correct XML syntax (make sure it passes [this online validator](https://www.xmlvalidation.com/)).
