### ISSUE TITLE
Where are the backups for the vault files?

### ISSUE THREAD

**Issue by Kubox120** [EtienneLamoureux/TQVaultAE#368]
While using the newest version of TQ vault I cleared my inventory to this vault and took a recipe to craft and after restarting the game it did not remove that items I cleared in TQ Vault and also didn't give me the recipe (even after restarting the game). I opened TQ Vault again and it somehow managed to clone the items I sooner cleared there and instead took my recipe. So now i have two times my things to sell but i do not have recipe anywhere. It just got deleted... Great...

**Comment by Kubox120** [comment]
Now it even gave me the same items third time. I literally have cloned my inventory of almost useless things to sell 3 times, but lost my recipe D:

**Comment by EtienneLamoureux** [comment]
1. You can restore vault files from the backups, located by default at `My documents -> My Games\Titan Quest\TQVaultData\Backups`
2. You can delete objects from a vault forever by selecting the "Delete" option of the right-click menu

As a general rule of thumb, it is safer to use the tool exclusively while outside the game. For example: close Titan quest completely, use TQVaultAE, close the tool completely, re-open Titan Quest.
