### ISSUE TITLE
Why is Microsoft SmartScreen flagging TQVaultAE as potentially dangerous?

### ISSUE THREAD

**Issue by chalahala** [EtienneLamoureux/TQVaultAE#369]
Microsoft:
https://feedback.smartscreen.microsoft.com/feedback.aspx

I reported it to Microsoft that I believe it is safe, because Steam seemed to trust it in its TQ Vault forum: 
https://steamcommunity.com/sharedfiles/filedetails/?id=1136716167

Microsoft's Defender Smart Screen blocked it apparently.
https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-smartscreen/microsoft-defender-smartscreen-overview

Second page as well:
https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-smartscreen/microsoft-defender-smartscreen-overview

I ended up downloading TQVaultAE somehow successfully. I don't know.

**Comment by EtienneLamoureux** [comment]
I'll check out why these results appear as such. If you are worried, you can check the source code directly: https://github.com/EtienneLamoureux/TQVaultAE/tree/master/src

I can assure you we didn't put anything bad in the tool willingly.
