### ISSUE TITLE
Fix display name for the relic "Aegis of Athena"

### ISSUE THREAD

**Issue by bloodbook-w** [EtienneLamoureux/TQVaultAE#370]
Like this:
![relics](https://user-images.githubusercontent.com/78729684/107207849-b38b7880-69f8-11eb-8489-cf1de53fce58.png)
[relics.zip](https://github.com/EtienneLamoureux/TQVaultAE/files/5943009/relics.zip)
what can i do to solve it?

**Comment by hguy** [comment]
@EtienneLamoureux Not buged anymore.
![image](https://user-images.githubusercontent.com/31834707/161820624-2443abc6-db8c-4048-8575-e00b416db945.png)
