### ISSUE TITLE
How to fix FileLoadException?

### ISSUE THREAD

**Issue by vasile233** [EtienneLamoureux/TQVaultAE#371]
I keep getting a message The Vault path was not set. Using the default setting.Please verify the path with the configuration dialog.After that I get this error  https://i.imgur.com/K3JU6D3.png

**Comment by EtienneLamoureux** [comment]
Try the steps under `Q. Error Loading Resources. This may be caused by a bad language or game path setting.` [here](https://github.com/EtienneLamoureux/TQVaultAE#troubleshooting-and-faq)
