### ISSUE TITLE
How to fix System.ArgumentNullException?

### ISSUE THREAD

**Issue by Jagerbear** [EtienneLamoureux/TQVaultAE#372]
I get this error everytime I try and launch tqvault. I have changed the paths in the config file to point to my tq install, any ideas?
![16149673689352210153889656947143](https://user-images.githubusercontent.com/80122661/110155084-029cb180-7ddd-11eb-9382-ef273f0a82bf.jpg)

**Comment by EtienneLamoureux** [comment]
It looks like the tool cannot find your list of characters. Do you have the game through a platform (Steam, etc.) or standalone?

**Comment by andrewfera** [comment]
Yeah, i have this problem, too. 
![image](https://user-images.githubusercontent.com/47458028/111071806-e12c7b80-84e8-11eb-9c2f-4578a8fcd4e6.png)

**Comment by Jagerbear** [comment]
Exactly right! I hadn't put my saves in the correct place - I was working between my saves on the android version and the pc version and got it muddled up. All working now - thanks!
