### ISSUE TITLE
How to resize the window?

### ISSUE THREAD

**Issue by andrewfera** [EtienneLamoureux/TQVaultAE#373]
Fixed all the errors that I got. However, the main one appeared, which I do not know how to solve.
![image](https://user-images.githubusercontent.com/47458028/111074061-6bc5a880-84f2-11eb-88cb-f00348bfb8e9.png)
The picture has moved out and it is not possible to use the application correctly. However, there is enough control for my little pranks.

**Comment by EtienneLamoureux** [comment]
Which resolution are you running the tool with?

**Comment by andrewfera** [comment]
Where are the settings? Inside the application itself, they are not, at startup, too.

**Comment by EtienneLamoureux** [comment]
Unfortunately there is no resolution setting in the configuration menu. You can adjust the size of the window by dragging the bottom-right corner of the application, like so: 

![image](https://user-images.githubusercontent.com/3357406/111197240-9ff1a580-8594-11eb-9b54-80ea979b3d39.png)

Please note that the minimum supported resolution is 600x400.
