### ISSUE TITLE
Fix stats for individual items

### ISSUE THREAD

**Issue by TeaDrivenDev** [EtienneLamoureux/TQVaultAE#376]
Different instances of the same "named" item (say two different "Storm Eye" rings) usually have slightly different attributes. However, TQVault shows the same stats for all instances of an epic item, even if they are different in game.

I have tried to find out where/how this happens, and the responsible part of the code seems to be somewhere in `ItemProvider`, but so far I only have a vague suspicion that there might be relevant information in the save game data that TQVault currently does not read.

Edit: I looked at some more items, and this seems to apply to all items. Here is the same green item in game and in TQVault:

![image](https://user-images.githubusercontent.com/2247219/115149208-57317e80-a063-11eb-877e-1306fa370fa7.png) ![2021-04-18 16_26_32-TQVaultAE 3 7 4 0](https://user-images.githubusercontent.com/2247219/115149229-6a444e80-a063-11eb-9600-0d4145d4c90c.png)

My interpretation so far is that what TQVault currently reads from the database are the minimal stats an item of this kind _could_ have, but the actual values for each specific instance are stored in a different place that TQVault doesn't use at this time.

#222 might have a similar cause.

**Comment by TeaDrivenDev** [comment]
Okay, I just found the part of the documentation that talks about this. That makes sense, although sadly it means TQVault can not be used to meaningfully compare items of the same kind. I wonder if the game's seed handling could be reverse engineered with numerical methods and/or "machine learning" (and A LOT of effort)....

**Comment by EtienneLamoureux** [comment]
It most likely could, with *a lot* of effort! Without an understanding of how the key is used in-game, it's hard to get started on something like this.
