### ISSUE TITLE
Add Linux compatibility

### ISSUE THREAD

**Issue by markotuna** [EtienneLamoureux/TQVaultAE#377]
Basically what title already says. TQ Vault wont run on Linux and I'm not sure why, but if you could make it run that'd be awesome!

**Comment by hguy** [comment]
What is the use case ? Titan Quest run exclusively on Windows and consoles ?
If you use Wine to run it on linux, i guess you can do the same with TQVault. Aren't you ?

**Comment by EtienneLamoureux** [comment]
You can skim through https://github.com/EtienneLamoureux/TQVaultAE/issues/90 and its related ticket for a possible solution to your problem.

**Comment by craniumbasher** [comment]
I'm trying to run TQVault from Linux (using Wine), in the log there is an error :

ERROR TQVaultAE.GUI.Program [(null)] - Value cannot be null
I've changed the path using the FAQ.

[TQVaultAE_2021.09.24.txt](https://github.com/EtienneLamoureux/TQVaultAE/files/7225858/TQVaultAE_2021.09.24.txt)

**Comment by hguy** [comment]
Do you have at least one character on your wine setup ?

**Comment by craniumbasher** [comment]
yes I have many characters. I'm still trying to find what's wrong but I didn't manage to find how to fix that.

**Comment by hguy** [comment]
I'm not familiar with Wine. Is it because program installation inside Wine are sandboxed and a program "A" (TQVault) can't see the file system of a program "B" (Titan Quest) ? (file system isolation)

The error log tells us that TQVaultAE can't see any save file in the file system which is resolved as follow.
```
C:\Users\{yourname}\Documents\my games\Titan Quest - Immortal Throne\SaveData\Main
C:\Users\{yourname}\Documents\my games\Titan Quest - Immortal Throne\SaveData\User (mod save file)
C:\Users\{yourname}\Documents\my games\Titan Quest\SaveData\Main
```

**Comment by craniumbasher** [comment]
OK but what I don't understand is that I've changed the exe.config in order to force the new path.
For information the D disk is corresponding to the path /home/craniumbasher/.local/share/Steam/steamapps/common under Wine.
Maybe I made a mistake in the .config but I don't know where.

**Comment by EtienneLamoureux** [comment]
> 
> 
> OK but what I don't understand is that I've changed the exe.config in order to force the new path.
> For information the D disk is corresponding to the path /home/craniumbasher/.local/share/Steam/steamapps/common under Wine.
> Maybe I made a mistake in the .config but I don't know where.

Can you share your config file and the path where the installation resides?

**Comment by craniumbasher** [comment]
many thanks for the support. Here is the exe.config and the last log.
The F: disk is a shortlink and is corresponding to the path :
/home/craniumbasher/.local/share/Steam/steamapps/compatdata/475150/pfx/drive_c/users/steamuser/Documents/My Games/


[TQVaultAE_2021.09.26.txt](https://github.com/EtienneLamoureux/TQVaultAE/files/7232209/TQVaultAE_2021.09.26.txt)
[TQVaultAE.exe.zip](https://github.com/EtienneLamoureux/TQVaultAE/files/7232211/TQVaultAE.exe.zip)

**Comment by hguy** [comment]
## How to port TQVault to Linux
Some projects a not relevant and only 2 are windows bound. The rest can be compiled immediately with .NET on Linux.

![image](https://user-images.githubusercontent.com/31834707/186141325-14f71a08-8390-4cc5-88e4-61de10863524.png)

2. These 2 windows project must be rewriten or replaced to accomodate Linux
- `TQVaultAE.GUI` : Winform Graphical interface
- `TQVaultAE.Services.Win32` : Services that does things like Interop, Registry, Sound System. Yes it's already abstracted.

## What can be used for this port (non exhaustive)
  - For a Desktop UI App port
    - [avaloniaui](http://avaloniaui.net/)
    - [platform.uno](https://platform.uno/docs/articles/what-is-uno.html)
    - [GtkSharp](https://github.com/GtkSharp/GtkSharp)
    - [qmlnet](https://github.com/qmlnet/qmlnet)
    - [.NET MAUI](https://devblogs.microsoft.com/dotnet/introducing-net-multi-platform-app-ui/)
    - ___Note___ : Mono should be able to display Winform app (rendered thru Cairo) on X11 (but that's not a port). But `TQVaultAE.Services.Win32` should probably be rewritten.
  - For an "in the browser" web app port (probably the easiest)
    - .NET Blazor
    - ASP.NET Core

## Question the motivations
- Q : Who is using TQ on linux
- A : Almost no one
- Q : How are they doing it
- A : Virtualization like everybody that wanna play Windows games on Linux (essentialy Wine, Steam OS, Proton)
- Q : Why do they want a native port
- A : They fail to __virtualize a .NET Winform App__ (TQVault) in the __same virtual sandbox as the game__ and quit trying after 10 min.

## Solutions
- Simplest : No code, the linux gamer already know much about virtualizing windows app on linux.
Writing a "How to" guide on a wiki for success is the best option.
- Simplest port : The Mono port (if it deliver at displaying Winform app) then a web port
- Hardest port : All other solutions

## From a developper standpoint
Unless you want the chalenge of this task for fun or training purpose (which is rewarding at many levels), it's not worth it.
Better find a way to make it work through try and error (and some reading in the internet) in the same virtual sandbox than the game (a lot less work time).

**Comment by hguy** [comment]
A linux TQ player recently produce a "how to" play TQAE + TQVault on linux.
Maybe it can help this issue.

[TQTQV_on_linux.txt](https://github.com/EtienneLamoureux/TQVaultAE/files/9542829/TQTQV_on_linux.txt)
