### ISSUE TITLE
Charakter...Hilfe

### ISSUE THREAD

**Issue by Traunig** [EtienneLamoureux/TQVaultAE#378]
erstellte Charakter scheinen im Spiel nicht auf wie kann ich diese löschen...Danke

**Comment by Traunig** [comment]
in TQVault scheinen diese auf

**Comment by EtienneLamoureux** [comment]
Duplicate of https://github.com/EtienneLamoureux/TQVaultAE/issues/378

**Comment by Traunig** [comment]
Ich  habe die Lösung gefunden danke hatte seinerzeit den Pfad auf one Drive\User\Meine Dokumente\My Games gesetzt
da war Peter und Peter 5 in Ordner  Titan Quest -  Immortal Throne\Save Data\ Main noch vorhanden habe dort gelöschtund dann den TQ_Vault Data Ordner geändert  geändert auf Wechselplatte Y:\TQVault\TQVaultData Danke

**Comment by Traunig** [comment]
da sind die beiden chars peter und peter 5 nicht mehr vorhanden

**Comment by EtienneLamoureux** [comment]
Excellent!
