### ISSUE TITLE
Prevent excessive logging

### ISSUE THREAD

**Issue by AbrahamChutilian** [EtienneLamoureux/TQVaultAE#386]
Is it normal that the app generated 15 gb txt file in Logging folder? And I am sure that file would be even bigger, if my hdd wouldn't run out of space.

**Comment by hguy** [comment]
Could you share one of these log files?

**Comment by AbrahamChutilian** [comment]
[TQVaultAE_2021.08.23.txt](https://github.com/EtienneLamoureux/TQVaultAE/files/7035626/TQVaultAE_2021.08.23.txt)

The 15 gb one I've deleted, but here's another one that it has generated.

**Comment by hguy** [comment]
> [TQVaultAE_2021.08.23.txt](https://github.com/EtienneLamoureux/TQVaultAE/files/7035626/TQVaultAE_2021.08.23.txt)
> 
> The 15 gb one I've deleted, but here's another one that it has generated.

There's no error in this file. Log files tend to increase in size because the program produce a lot of errors.
Looks like it's over.

**Comment by hguy** [comment]
@EtienneLamoureux I donc think this can be reproduce. Must have be something else.
The log appender allows only for (10 * 10MB) of log.
![image](https://user-images.githubusercontent.com/31834707/161818802-4fe4e57e-3693-4f3e-b2bf-e461c994a45b.png)
