### ISSUE TITLE
Support custom databases from "hard" mods

### ISSUE THREAD

**Issue by sulez745** [EtienneLamoureux/TQVaultAE#387]
I'm using this mod in "hard mod", meaning that I replace vanilla files.
When I try to run TQVault with equipped soul (new kind of item, ring slot), this error occurs:
![547568768976987](https://user-images.githubusercontent.com/58529438/131849400-b74f9872-fb1e-48ad-9d18-cfc9baef62cb.png)
When I ignore this error, program loads, but my character equipment looks like this:
![43345252235](https://user-images.githubusercontent.com/58529438/131849774-348c7473-6d38-46fb-9978-890df32f205e.png)
I can't see equipped items.
Is there any way to fix this?

**Comment by hguy** [comment]
TQVaultAE is meant to be used with standard base files (not customized one) and is compatible with official mod integration (Legacy mod & Steam Workshop).
I don't think it can handle "Hard Mode" replacing official game files.

**Comment by hguy** [comment]
I mean that TQVaultAE does not provide any guaranty about mod support.

Looking at the error message, i'd say that it looks like there is an irregular expression when computing propertie values. It comes from the custom database you installed.
