### ISSUE TITLE
Deleted Characters from game but can't delete from TQVaultAE, Help!

### ISSUE THREAD

**Issue by Pax1sw** [EtienneLamoureux/TQVaultAE#389]
TQVaultAE was a godsend for me, I was using nearly 20 characters just to hold extra equipment, etc. Of course the characters were still in my game after installling and running TQVaultAE for the first time because I needed to unload their items into Vault before I deleted the otherwise non-playing characters. However, after I deleted all those characters TQVaultAE didn't update with my new leaner player list, so every time I load TQVaultAE I go through all the error screens of characters not found. Is there ANY way to delete a no longer existing character from TQVaultAE? NOTE: Just began playing TQAE again, so still using verion 3.0.0 of TQVAE. Just downloaded TQVAE 3.8.0, but it didn't update my player list, so still have those phantom characters.

**Comment by hguy** [comment]
As far as i can tell, that mean you still have character save directories in one of the following directories.
```
C:\Users\{yourname}\Documents\my games\Titan Quest - Immortal Throne\SaveData\Main
C:\Users\{yourname}\Documents\my games\Titan Quest - Immortal Throne\SaveData\User
C:\Users\{yourname}\Documents\my games\Titan Quest\SaveData\Main
```
Move those "dead" character directories elsewhere and restart TQVaultAE.
Delete them when you're satisfied.

**Comment by Pax1sw** [comment]
Thank you! I'll look there. Using a TQVAE error message, I found two lists, one in a folder named just "Titan Quest" (though I was playing version TQIT when I began my Holder characters) and a folder inside that folder named "Backups". I moved the deleted characters from those folders to two new folders, but still in the Titan Quest folder. Should I move them out of the Titan Quest folder? I haven't checked either of the folders you listed.

On one of those Holder characters I found what seems to be the Yellow, Green and Special Jewelry that's missing from TQVAE. It was there in TQVAE in three separate folders when I stopped playing in 2019 but, a few days ago when I started TQVAE (V3.0.0 I was using when I stopped playing in 2019), all three of those vaults were empty. The only Jewelry vault that wasn't empty was the Newbie Jewelry (Lvl 3). (It would be the Newbie Jewelry that survived. LOL)

Oddly, TQVAE's drop-down doesn't have the character I found who's shown as still holding Jewelry, even though it lists all the others. Of course, she's deleted from my game now, too, so I can't load her and get to the stuff she's shown as carrying in that character file I found in the Titan Quest folder. I moved everything she was carrying to the properly named vaults, so I don't know why she's listed as still carrying anything. Steam shows I've played almost 3,200 hours of TQIT and, since I collect it, that's a LOT of Jewelry. If it's gone, I'll live with it and just collect more, but would really like to have it back. Kind of afraid to put any more Jewelry in those vaults, but afraid to delete the vaults just in case the Jewelry's really there but just not showing.

**Comment by Pax1sw** [comment]
An addendum re my lost jewelry, it wasn't lost! TQVaultAE glitched and threw it all back onto my characters who were holding it originally after I'd transferred it to vaults. Luckily, back in 2019 I'd moved all the jewelry to 3 main characters and deleted the Holder characters when we got our new huge storage areas, before I transferred any items to TQVAE, unfortunately, I forgot I'd done that. How do I know? Just spent a couple of hours transferring Relics, Scrolls, Formulas, etc from all my characters... that's when I found my missing jewelry!

However, after my work was almost done, TQVAE "blinked" and when I went to a vault to transfer some items to a character, the vault was empty! Checking back over the multiple characters I'd transferred all those Relics and Formulas from, I discovered most of it was back on the characters who'd been holding it, including the Special Jewelry (Blue/Purple). At least TQVAE didn't eat any of it, that's a relief. I'll just have to transfer it again, but maybe just a couple of characters at a time and let TQVAE adjust to the new load before I pile in more. Think that "blink" was TQVAE throwing up from input overload. LOL

**Comment by Pax1sw** [comment]
Might as well close this, since your solution to my original question worked temporarily. However, the game keeps re-adding those deleted characters back to the files you instructed I delete them from, so I'm out of options there, deleted them from three different TQAE folders and they keep coming back. Anyway, it's not TQVaultAE holding defunct characters in its original config for my use, so you guys can't do anything further. Thanks for your replies. Bye :)
