### ISSUE TITLE
The vault path was not set.

### ISSUE THREAD

**Issue by Borislav-Milev** [EtienneLamoureux/TQVaultAE#395]
![Untitled](https://user-images.githubusercontent.com/18377049/136856429-a8e808ee-056e-4913-8198-3f10089eaa51.png)
![err](https://user-images.githubusercontent.com/18377049/136856552-1753b5bd-e338-4d04-9c6f-ea5eb84b847f.png)

**Comment by Borislav-Milev** [comment]
I tried with the new vault and this error showed. With my older version of the vault witch I was using and it was working fine before I reinstalled my windows also couldn't work. I tried setting the vault path and game path manually by creating in Titan Quest folder (my games) a folder named TQVaultData and set the path to there, but still it didn't work. All the changes I tried making were in the TQVaultAE.Config.dll file and also in TQVaultAE.exe file. If someone can help out it would be greatly appreciated since I rely a lot on the vault and all my items are in there.
Thanks in advance!

**Comment by hguy** [comment]
Installing & Running the game produce all related file structure in the system. Why trying to use TQVaultAE in a system without the game ?
Reinstalling windows may have deleted all your Titan Quest data.

**Comment by Borislav-Milev** [comment]
Ok, give me a few minutes

**Comment by hguy** [comment]
Main
