### ISSUE TITLE
Item - Sapros The Corrupter - Wrong Statistics

### ISSUE THREAD

**Issue by TheWagi** [EtienneLamoureux/TQVaultAE#397]
Hello o/

The following are wrong:
- 180 Reduced Resistances over 3.0 Seconds
- 180 Reduced Armor over 3.0 Seconds

They should be both
- 60 Reduced ... over 3.0 Seconds

TQVault
[https://cdn.discordapp.com/attachments/347282491192639489/900775994670063686/unknown.png](url)

ArtManager
[https://cdn.discordapp.com/attachments/672458358673899541/900778031969349712/unknown.png](url)
[https://cdn.discordapp.com/attachments/672458358673899541/900778084519776346/unknown.png](url)

Wagi

**Comment by ejfudd** [comment]
This is the same as #222
