### ISSUE TITLE
Cannot find stash file

### ISSUE THREAD

**Issue by TranceFetish** [EtienneLamoureux/TQVaultAE#398]
When opening TQVault AE (latest version), I get this error for both the stash file and relic file. When the vault loads, both those tabs are missing. I am playing the mod Soulvizier and have enabled the custom mods and selected the correct mod.

My path names are all correct as it shows my character and items except those from the stash and relic storage. There also seems to be the issue that the items do not fit inside the storage boxes, what is causing this issue?

[https://ibb.co/1K26BFq](url)

**Comment by TranceFetish** [comment]
Here is the error again. Also other errors I get when hovering over certain items.
![Error](https://user-images.githubusercontent.com/93061363/139517030-7b2211a9-abad-42df-8619-f6b14da2f0ad.jpg)
![Error3](https://user-images.githubusercontent.com/93061363/139517215-fbec2d23-8abb-4b34-933f-0270c74de9ed.jpg)
![Error4](https://user-images.githubusercontent.com/93061363/139517220-a41552bf-9db2-42e8-85dd-325349cfe6f1.jpg)

Note the items being outside the boxes and being cut off also.

**Comment by enders-blade** [comment]
> Here is the error again. Also other errors I get when hovering over certain items. ![Error](https://user-images.githubusercontent.com/93061363/139517030-7b2211a9-abad-42df-8619-f6b14da2f0ad.jpg) ![Error3](https://user-images.githubusercontent.com/93061363/139517215-fbec2d23-8abb-4b34-933f-0270c74de9ed.jpg) ![Error4](https://user-images.githubusercontent.com/93061363/139517220-a41552bf-9db2-42e8-85dd-325349cfe6f1.jpg)
> 
> Note the items being outside the boxes and being cut off also.

I'm experiencing the same issue.  Downloaded the EE Test3 version.  Running a mod in the /custommaps folder.  Equipment and Storage Area work, Transfer and Relic disabled.  Yes, I have items stored in both tabs.

**Comment by ejfudd** [comment]
This looks like a relic of the original release of the game.  The on release TQ Save data structure in your saved games folder is like this (dashes [-] denote folder levels):
```
CustomMaps
  - Mod Folders = Each one contains the mod data for each mod you have installed.
SaveData
  - Main = Contains player character saves for the main story quest.
  - Sys
    - miscsys.dxb = Relic vault for main story
    - miscsys.dxg = Also Relic Vault for main story
    - winsys.dxb  = Transfer stash for main story
    - winsys.dxg  = Also Transfer stash for main story
    - Folders with names matching the folders in the CustomMaps folder.
      - miscsys.dxb = Relic vault for the specific mod that it resides in.
      - miscsys.dxg = Also Relic Vault for the specific mod that it resides in.
      - winsys.dxb  = Transfer stash for the specific mod that it resides in.
      - winsys.dxg  = Also Transfer stash for the specific mod that it resides in.     - 
  - User = Contains player character saves for modded games
```

TQVault assumes this structure when creating the path to locate the transfer stash and relic vault for the mod.  If the folder structure is different, the lookup will fail.

It looks like the custom map code for this does not work even if the folder structure is correct.  For example the code to locate the transfer stash file:
```
public string TransferStashFile
		{
			get
			{
				if (IsCustom)
					return Path.Combine(MapName, "SaveData", "Sys", Path.GetFileName(MapName), "winsys.dxb");

				return Path.Combine(ImmortalThroneSaveFolder, "SaveData", "Sys", "winsys.dxb");
			}
		}
```

For a custom map named MyMod in the custom maps folder the path would resolve to:
...\Saved Games\Titan Quest - Immortal Throne\CustomMaps\MyMod\SaveData\Sys\MyMod\winsys.dxb
This path should not contain the transfer stash.

Are the transfer stash and relic vault working at all with mods in TQVault?

**Comment by TranceFetish** [comment]
No they don't work with any mods I've used. Must be some way to activate them?

**Comment by ejfudd** [comment]
As I suspected.  It looks like the code to construct the path to the Transfer stash and Relic vault file locations is broken for mods.  Odd that no one complained before.  It's a fairly simple to fix, but it would require a fix in the code.

As a workaround, you could copy your Transfer Stash and Relic vault files to the path that TQVault is looking.  Keep in mind this will make 2 copies of the files and they would need to be copied back to the original location for the game to recognize the changes.

**Comment by TranceFetish** [comment]
All good I will wait for the update, thanks for looking into it!

**Comment by eccodolf** [comment]
Same issue on android saves: it splits stash into 3 files: 
0winsys.dxb
0winsys.dxg
1winsys.dxb
1winsys.dxg
2winsys.dxb
2winsys.dxg

TQVault can load only character with equipement but not stash.

**Comment by ejfudd** [comment]
@eccodolf This is mentioned in #380 and basically the mobile version has a different file format for the stashes.
On top of that, it also has a different naming convention for the files and possibly an internal system of keeping backup copies of the stash files.
