### ISSUE TITLE
Support Eternal Embers

### ISSUE THREAD

**Issue by RedFireTiger86** [EtienneLamoureux/TQVaultAE#401]
Could you possibly update TQ Vault for this most special occasion, good sir?

**Comment by Ninakoru** [comment]
I've updated for it already: https://github.com/Ninakoru/TQVaultAE/releases/tag/3.8.0-TEST
Also called for a merge with these changes.

**Comment by mmmilord** [comment]
> I've updated for it already: https://github.com/Ninakoru/TQVaultAE/releases/tag/3.8.0-TEST2 Also called for a merge with these changes.
> 
> EDIT: Updated the link, this version also properly supports Nidan class.

If you forked it, you should probably have an issues tracker.

**Comment by RedFireTiger86** [comment]
> I've updated for it already: https://github.com/Ninakoru/TQVaultAE/releases/tag/3.8.0-TEST2 Also called for a merge with these changes.
>
> EDIT: Updated the link, this version also properly supports Nidan class.

Big props to you!

**Comment by EtienneLamoureux** [comment]
Sorry I missed that! Will release in the coming days :)
