### ISSUE TITLE
Fix missing access to difficulties after resetting attributes

### ISSUE THREAD

**Issue by icefreeze88** [EtienneLamoureux/TQVaultAE#405]
Hello guy!
     When my character at Legendary difficulty using attribute respect (+ or -) feature, Epic and Legendary difficulties be disabled (I don't check reset attribute and reset mastery feature yet, you may want to check it out too).
     Thanks for your supporting during longtime along with Titan Quest!

**Comment by vsolovev** [comment]
Reseting masteries does not restore skillpoints

**Comment by icefreeze88** [comment]
> Additional: Reseting masteries does not restore skillpoints. Btw as a workaround for legend: it's possible to restore epic and legendary levels (using the selector in player edit info)

Yes, ticked Enabled Leveling in Character Edit tab "re-enabled" Epic and Legendary diffuclties.
But this issue should be fixed.
Thanks!
