### ISSUE TITLE
Fix the image for "The Primrose"

### ISSUE THREAD

**Issue by Fa310tx** [EtienneLamoureux/TQVaultAE#408]
![ThePrimrose](https://user-images.githubusercontent.com/2768056/147837163-379926f8-0e9b-4aab-9c47-aabdae8a9687.png)

**Comment by hguy** [comment]
Looks like fixed to me
![image](https://user-images.githubusercontent.com/31834707/161817210-8f4f9c0a-5da6-4ded-803d-cebca39d283e.png)

**Comment by Fa310tx** [comment]
It is working, now.
I updated to 4.0.0 and it still didn't show up.
What I realized, though, is that it autodetected my GOG version (which doesn't have Ragnarok).
I switched to my Steam path and it showed up.
I wonder if the older version was doing the same thing?
JJ

**Comment by hguy** [comment]
> It is working, now. I updated to 4.0.0 and it still didn't show up. What I realized, though, is that it autodetected my GOG version (which doesn't have Ragnarok). I switched to my Steam path and it showed up. I wonder if the older version was doing the same thing? JJ

You must own the DLC on your Titan Quest installation directory to see the picture

**Comment by hguy** [comment]
@EtienneLamoureux this is not a bug.
The tool just can't find the picture of an item in a DLC you don't own (ARC files are not available).
