### ISSUE TITLE
Vault isn't working properly

### ISSUE THREAD

**Issue by Kingerino** [EtienneLamoureux/TQVaultAE#411]
Hello, I transferred almost all my items to the vault, I closed the vault, I opened it again and now it is gone, I have backup for my items from the vault but I don't know how get it back. Its always error with no vault path and I changed it in config file, nothing happens, vault isn't opening either so please help me get my stuff back
![Zrzut ekranu (3)](https://user-images.githubusercontent.com/97290893/148543005-4989b6ca-dc89-4410-878d-437ed90235dd.png)

**Comment by ejfudd** [comment]
This is the same issue as #287 
Basically, TQVault needs to have access to the game files.  See the comments in #287 for suggestions on what to do.

**Comment by Kingerino** [comment]
Thanks, I'm new on this site but now it's working, I didn't get back all of my stuff, just like 50% but Vault is now working, appreciate man!

**Comment by ejfudd** [comment]
TQVault creates backups for all of the changes that it makes so you might still have access to those items.
Check the backup folder at:
My Documents\My Games\Titan Quest\TQVaultData\Backup

**Comment by Kingerino** [comment]
I know there is a backup but I don't know how to gain access to these items :/

**Comment by ejfudd** [comment]
This might be helpful to others as well, so this is how the backups work and how to restore them.

Before TQVault makes any changes to your files which includes vaults, characters and stashes, it will create a backup of the affected files.
The backups are stored in a subfolder named Backups in the TQVaultData folder.
The backup filename itself will contain the name of the original file along with some additional numbers to make them unique.
The different types of determined by the filename extension as follows:
Characters - CHR
Stashes - DXB and DXG
Vaults - VAULT

To restore Vaults:

1. Copy the backup file into the TQVaultData folder.
2. You may want to rename it and shorten the filename so the name is not so long in the dropdown list.
3. When you start TQVault, you should see the backup in the dropdown list of available vaults.

To restore Characters:

1. You need to find the character save folder. It is normally in <Saved Games>\<Titan Quest Game Edition>\SaveData\Main. If you play a mod, replace Main with the Mod name.
2. Each character will have a subfolder with the character name in this folder.  
3. Make a backup copy of the character folder along with its contents. 
4. Inside your character's subfolder, you will find a file named player.chr which you should rename. Adding a .bak extension should be sufficient. 
5. Copy your backup character file from TQVaultData\Backups into the character save folder. 
6. Rename your backup file to player.chr. 
7. When you open TQVault, the character will be available in the dropdown list.

To restore Player stashes:
Player stashes are pretty much the same as character files, but with different naming.
The backups will have the DXB and DXG extensions, but the filename will start with the character name.  These files come in pairs so you will need to restore BOTH the DXB and DXG backup files. You can tell which files are paired as they will have the same date & time stamp. 

1. Locate your character save folder just as if you were going to restore a character backup.
2. Make a backup copy of the folder and its contents. 
3. Inside the folder you will find two files winsys.dxb and winsys.dxg.  Rename and add a .bak extension to both of them.
4. Copy your backup dxb and dxg files into your character folder.
5. Rename the backup files to winsys.dxb and winsys.dxg.
6. The restored character stash will now be available the next time you start TQVault.
 
To restore the Relic Vault and Transfer stash:
Relic Vault - miscsys.dxb and miscsys.dxg
Transfer Stash - winsys.dxb and winsys.dxg
The backup filename will start with either Transfer Stash or Relic Vault to denote which one it is. These files also come in pairs so you will need to restore BOTH the DXB and DXG backup files. You can tell which files are paired as they will have the same date & time stamp. 

1. Common save files folder. It is normally in <Saved Games>\<Titan Quest Game Edition>\SaveData\Sys. If you play a mod, you will see a subfolder with the mod name.
2. Make a backup copy of this folder and its contents.
3. Rename the original Transfer Stash or Relic Vault files by adding a .bak to both files.
4. Copy your backup file pair into the common save file folder (SaveData\Sys or SaveData\Sys\<Modname>).
5. Rename your backup file pair to the appropriate filename depending on the type of file restored.

You may need to do this several times to find the exact backup that you are looking for.
Also, once you are done it is high recommended to restore the original files especially the game save related files.

**Comment by Kingerino** [comment]
Jesus man, you're the best! I'll check it next day, so happy to be part of the Titan Quest community.
