### ISSUE TITLE
Rising an error System.IO.FileLoadException

### ISSUE THREAD

**Issue by FirstTry11** [EtienneLamoureux/TQVaultAE#415]
Hello! 
I've tried to use the latest version of TQVault and all time got the error with launch it. Can somebody explain how to fix that? I wrote the way in the game's directory, switched autodetection Game Path and nothing helped.
![Error TQVault 1](https://user-images.githubusercontent.com/65363662/151718229-b9796efe-47d5-4ce9-8b56-e2f0ed173922.jpg)
![Error TQVault 2](https://user-images.githubusercontent.com/65363662/151718231-c4578473-6bef-4f1e-bfb5-eab738f690c0.jpg)
![Error TQVault](https://user-images.githubusercontent.com/65363662/151718029-7506b577-2c44-4212-9ded-666dda38e904.png)

**Comment by EtienneLamoureux** [comment]
Try setting autodetect to `false` if you are providing the paths directly.

**Comment by FirstTry11** [comment]
> Попробуйте настроить автоопределение, `false`если вы указываете пути напрямую.

I've already thied. Failed

**Comment by ejfudd** [comment]
To start up, TQVault needs to find the game database and the text database within the game's install folder.
The game database is a bunch of arc files in the Resources subfolder of your game installation.
The text database is in the Text subfolder, and you should have an arc file which corresponds to your game language.

Your specific error is coming from loading the text database.
Have you tried setting the language to English to see if that works?
Also, you have many config files open in your screen shot with a .bak specifically highlighted.  Are you sure you modified the correct one?

**Comment by FirstTry11** [comment]
Hello. Yes, I'm sure that I run right file. I thied to change language and it's no result. There is all needed lang... files and, I suppose, all Resources files.

![Error TQVault 3](https://user-images.githubusercontent.com/65363662/152052833-a9af7f46-182e-482c-84cd-38cc863882c0.jpg)
![Error TQVault 4](https://user-images.githubusercontent.com/65363662/152052839-d1089d0a-62f1-4d62-863f-b566988821f1.jpg)
.

**Comment by ejfudd** [comment]
Try enabling debugging and setting the database debug level to 3 in the config file and then re-creating the error.
The debug log should have a clue on what is not being found.

**Comment by hguy** [comment]
@EtienneLamoureux @ejfudd this should be closed.
1. It's irrelevant with the new `UserConfig.xml` file.
2. The error is related to a config file defect.
![image](https://user-images.githubusercontent.com/31834707/185713900-3123cfb0-45bd-41d7-ae01-dacc4c48a914.png)
