### ISSUE TITLE
Add a new, more restrictive mode to the Forge

### ISSUE THREAD

**Issue by mmmilord** [EtienneLamoureux/TQVaultAE#452]
Hi, first and foremost I want to say thank you for not only maintaining the project but working on new features for TQVault, the new search bar and TQforge were pleasant surprises for me, that I have been internally complaining there lack for since the original tool's conception.

I have a few suggestions that would benefit the user experience:

1) Add magical, rare, epic and legendary to the list of field boxes in the "Highlight Items having" filter. So far it has everythign else, item types but no rarity.

2) For the TQforge, add a "MI mode", what this will do will only allow the item being forged to accept prefix/sufix from the same Monster Infrequent item.

Reason for this? Even with Strict mode, users can unknowningly grant them items that cannot exist in the game. The "strict" mode parameters only govern item type as the only rule on what can be allowed. 

for example, you can give a Ice scale helm 'Of the tinkerer', even though this is an impossible item combination to obtain in the game. Act 4 items cannot drop with Of the Tinkerer that is exclusive to Act 5. Another example, a INT helmet with 'Of the magus' can be given to a STR helmet, but this is also impossible by game rules since that suffix only appears on INT head armor. 

There are many impossible combinations, even for people that want to use it "legitimately", an MI mode would mean items that drop from ingame would be used to build desired items people want to farm for.

3) Add an **opt-in** choice, when using an item for it's Prefix/Suffix to upgrade an item, it gets sacrificed (deleted). (imo to not prevent user error would have this somewhere in configure, it could also give a prompt warning like deleting regular items from vault before doing so just for safe measure)

I'm sorry for ranting. Just want to help improve the feature for accessibility to as many people. also want to apologize on behalf of any immature players that demand you remove the feature because they cannot control their own urges to use the system in a justified manner, or not use it at all.

**Comment by hguy** [comment]
@EtienneLamoureux i think you can close this one.
@mmmilord your ideas are in the 4.2 release
