### ISSUE TITLE
Question: TQVault doesn't show real item stats?

### ISSUE THREAD

**Issue by ezloj** [EtienneLamoureux/TQVaultAE#454]
It only shows default modifier without account for item seed. I recall the (very) old one (from like 5 or more years ago) showed real item stats with randomised modifiers based on seed. How do I get it do that?

**Comment by hguy** [comment]
Hi @ezloj 
Current version can't do that, but if you can give us a hint on where is the source code of that old version we can look at it.

**Comment by ejfudd** [comment]
The original TQVault never had the ability to decode the item stats.  Maybe you are thinking of something different or maybe someone forked the original.  If there is a version that can decode the stats, that would be awesome since that is kind of the white whale for this project.

**Comment by ezloj** [comment]
Could it be that that was patched in by TQDefiler?
I searched on the internet and dug deep into my memory and I can't recall if I made this up now... I recall I was duplicating items to get the best seed possible but can't remember if I logged into the game to check the stats or if I checked them in TQVault... I'll try dropping an e-mail to digital arrow and see if maybe someone can give the info about decoding..

**Comment by EtienneLamoureux** [comment]
It's unfortunate, but has and most likely will always be the case. See the F.A.Q.: https://github.com/EtienneLamoureux/TQVaultAE#troubleshooting-and-faq

**Comment by ezloj** [comment]
ok, thank you for the explanation. I dropped an e-mail to digital arrow but no response (so far) and I'm not optimistic.
