### ISSUE TITLE
Fix an issue with the public Beta 5 patch

### ISSUE THREAD

**Issue by DinosaurGamer** [EtienneLamoureux/TQVaultAE#459]
Hey HGUY,

Thanks for all the work you've put into this.

Just wanted to let you know that the latest patch for Eternal Embers broke The Forge.  Prefixes and suffixes can no longer be imbued into a new item.

Thanks again!

**Comment by hguy** [comment]
Hi @DinosaurGamer
Do you mean "public beta 5" ?

**Comment by hguy** [comment]
@DinosaurGamer on PB5 i still can wear a crazy custom legendary.

![image](https://user-images.githubusercontent.com/31834707/181190433-c1314a8b-4f87-4c51-814c-45d0f9dc813e.png)

**Comment by hguy** [comment]
They have changed something in the TQ database. It's not the forge but the whole TQVault that crash.
![image](https://user-images.githubusercontent.com/31834707/181211755-4dac5f8c-63bc-4f36-967b-e9876401374d.png)

**Comment by DinosaurGamer** [comment]
Yeah, I think the latest patch July 8 patch was quite significant:

     https://steamdb.info/patchnotes/8825698/

The patch made a lot of changes to the game.

The rumor is that these TQ game content additions are to keep interest in TQ going for TQ2's release.

**Comment by hguy** [comment]
no July 8 patch is OK. It's public beta 5 that crash tqvault.

**Comment by DinosaurGamer** [comment]
My TQ version is Steam 2.10.21036.

**Comment by DinosaurGamer** [comment]
Every item I try to forge is turning it into a white item with no special attributes, unfortunately.

Thanks for looking into this!

**Comment by DinosaurGamer** [comment]
Okay, I think I found the problem.

When I try to forge the following:

     prefix item = green torso armor with "Socrates" prefix
     base item = white torso armor

Using God Mode, it does not work.  The Socrates prefix doesn't get added to the white torso armor.

But when I use Relax Mode, it works.  The Socrates prefix is added to the white torso armor.

**Comment by hguy** [comment]
> Using God Mode, it does not work. The Socrates prefix doesn't get added to the white torso armor.
> 
> But when I use Relax Mode, it works. The Socrates prefix is added to the white torso armor.

Don't forget that Gad mode force you to choose the property group of Prefix/Suffix items. Default is "Base".
If your affixes items have a "base" with no properties then you inherit nothing. It can result to a weaker item then.

![image](https://user-images.githubusercontent.com/31834707/181448863-a0a1445a-b1ed-4c6d-b45b-0260fad7a7a9.png)

"Of the tinkerer" gives none except it's two socket capability.

Here affixes items have empty bases and result into an empty item (Loop Silver Beads Beads)
![image](https://user-images.githubusercontent.com/31834707/181451233-26e4399a-466b-4942-a50c-3890c480ecc8.png)

Same items with affixes cherry pick
![image](https://user-images.githubusercontent.com/31834707/181451681-bef2af5c-4fc7-4ad4-87fc-a0ab7c858879.png)

**Comment by DinosaurGamer** [comment]
Hey HGUY,

You are absolutely right!

Completely my bad.

My old eyes did not catch the drop down menu when clicking God Mode.

As I said again and again, a huge thanks to you and Etienne and everyone else who's keeping TQ going!

This TQ fan really appreciates it!

**Comment by hguy** [comment]
@EtienneLamoureux patch beta 6 is out and the problem disapeared. This issue can be closed.
