### ISSUE TITLE
Is the tool compatible with Eternal Embers patch 4?

### ISSUE THREAD

**Issue by Nyio** [EtienneLamoureux/TQVaultAE#460]
Hello, i used to use TQvault before, starting to replay the game, changed pc, to i had to reinstall TQ vault, before i remember i had to do like a "fix" to make it work with Eternal Embers, i just wanted to ask if you still needed to do something with the vault or does it just works with the latest version? 

Once again, sorry for asking there.

-Nyio

**Comment by hguy** [comment]
Hi
now it's fully compatible with Eternal Embers patch 4.

**Comment by Nyio** [comment]
> Hi now it's fully compatible with Eternal Embers patch 4.

Thanks a lot for your answer hguy ! Have a great day.
