### ISSUE TITLE
Can't get TQVaultAE working...

### ISSUE THREAD

**Issue by chris-tietgen** [EtienneLamoureux/TQVaultAE#464]
Why is this app so hard to get working?

I am stuck in a loop with the following error. I've tried manually setting the paths by editing the config file, manually setting the TQLanguage value to English, but it's just a loop between these 2 dialogs.

![image](https://user-images.githubusercontent.com/23318158/184542929-b50a9996-a581-47ca-a107-fe85f178c6cc.png)

![image](https://user-images.githubusercontent.com/23318158/184542883-1f7e9032-42f2-4569-a1fe-8e744f551555.png)

Here are the paths and settings I have set...

![image](https://user-images.githubusercontent.com/23318158/184543324-760a3b0d-b5f6-44b2-a9f9-6d3dd425db91.png)

**Comment by hguy** [comment]
Hi @chris-tietgen, 
Delete all sub directories you find inside  "%USERPROFILE%\AppData\Local\titanquest.net_community" and restart the tool.

**Comment by chris-tietgen** [comment]
That didn't help. I still get stuck in the dialog loop I mentioned above.

**Comment by hguy** [comment]
can you share your config file and your Last log file ? Directory `./Logging` ?

**Comment by chris-tietgen** [comment]
I had to rename the config file to upload it, but both are attached, thanks.

[TQVaultAE_2022.08.15.txt](https://github.com/EtienneLamoureux/TQVaultAE/files/9339072/TQVaultAE_2022.08.15.txt)
[Config.txt](https://github.com/EtienneLamoureux/TQVaultAE/files/9339078/Config.txt)

**Comment by hguy** [comment]
There's a little bug when you don't have any vault file in the your vault directory.
You can fix it by droping an empty vault in your `C:\Users\Slacker\Documents\My Games\Titan Quest\TQVaultData`

Here's one.
[Empty.vault.zip](https://github.com/EtienneLamoureux/TQVaultAE/files/9350814/Empty.vault.zip)

**Comment by chris-tietgen** [comment]
That seemed to have fixed the issue, thanks. Not sure if anyone else runs into this issue, but if this fixes it, you might want to create that empty vault file when installing.

I'll perform some testing over the next few days to make sure the app is working correctly. Again, thanks.

**Comment by hguy** [comment]
> That seemed to have fixed the issue, thanks. Not sure if anyone else runs into this issue, but if this fixes it, you might want to create that empty vault file when installing.

No need for any of that. I simply fixed the code directly. It's part of this PR #462.

**Comment by hguy** [comment]
@EtienneLamoureux this Issue and #279 are the same.
