### ISSUE TITLE
can't open TQVault V4.3.0 , System.IO.FileLoadException

### ISSUE THREAD

**Issue by danielplw2** [EtienneLamoureux/TQVaultAE#466]
it say Vault path not set, using default setting, and an error say  System.IO.FileLoadException
![image](https://user-images.githubusercontent.com/16812766/185376208-549c51a7-33b3-4ba7-be12-0ea8178d6998.png)
![image](https://user-images.githubusercontent.com/16812766/185376231-43b17b49-cc3e-49a1-bc20-2e8e4a649d97.png)
![image](https://user-images.githubusercontent.com/16812766/185376337-89f1c595-ce4c-4d13-9e6d-0a5d36e269ad.png)
could't find the game path setting in exe.config

**Comment by hguy** [comment]
Hi @danielplw2 
> could't find the game path setting in exe.config

It's because user settings are in a new file called `UserConfig.xml` now. The path is there.

**Comment by danielplw2** [comment]
![image](https://user-images.githubusercontent.com/16812766/185619587-93fcbb97-e4c4-4745-881d-bb4d6f6d4f64.png)
still the same problem after I set the path

**Comment by danielplw2** [comment]
![image](https://user-images.githubusercontent.com/16812766/185638613-1560c04a-6895-4b6b-8180-411491f18c31.png)
I have try different game path but still pop out the same error

**Comment by danielplw2** [comment]
is working now
