### ISSUE TITLE
Copy function missing in vault

### ISSUE THREAD

**Issue by RBradleyM** [EtienneLamoureux/TQVaultAE#468]
The copy item function is missing in the current vault

**Comment by hguy** [comment]
I'm using it every day.
Enable it in the settings ("Configure" button)
![image](https://user-images.githubusercontent.com/31834707/187081670-4e184e68-fed3-4b37-862d-687ba5a1e811.png)

**Comment by RBradleyM** [comment]
The config menu was not there I reinstalled and it works now
