### ISSUE TITLE
Error reading file at position 13446.  Expecting 'stackCount'.  Got 'end_block'

### ISSUE THREAD

**Issue by creyo321** [EtienneLamoureux/TQVaultAE#47]
This is happening in 2.51 and 2.52. (did not test earlier builds)

When running TQVaultAE.exe AND when selecting a specific character I get the following error:

**Error Reading player file 
C:\Users\...\SaveData\Main\CharacterName\winsys.dxb
Error Reading file at position 13446. Expecting 'stackCount'.
Got 'end_block'**

tqdebux.txt says: **Error reading file at position 13446.  Expecting 'stackCount'.  Got 'end_block'

![tqvault](https://user-images.githubusercontent.com/34841346/34342383-a8245412-e9ae-11e7-81f1-57193471f658.png)
**

[tqdebug.txt](https://github.com/EtienneLamoureux/TQVaultAE/files/1586087/tqdebug.txt)

It doesn't appear to have any effect on actual usage of TQVault.

**Comment by NorthFury** [comment]
Can you please attach winsys.dxb and winsys.dxg from that location?

**Comment by creyo321** [comment]
Here is the full save with winsys.dxb and winsys.dxg.

[_Dandelion.zip](https://github.com/EtienneLamoureux/TQVaultAE/files/1586091/_Dandelion.zip)

**Comment by NorthFury** [comment]
Thank you. This will definitely help fix the issue.

**Comment by NorthFury** [comment]
@creyo321 it seems that after I visit the caravan driver in game and then exit the game the problem goes away. Did you edit that characters stash outside of the game and didn't visit the caravan driver before opening TQVault again? I'm asking because I'm trying to figure out if the game created the corrupted file or TQVault did.

**Comment by creyo321** [comment]
So, I did some tests. Tested with exactly the same save I provided. 

The error seems to disappear when transferring ingame any item currently equipped into storage area and save the game and quit.

Tested with almost all the items currently equipped and the results are the same.

After that, running TQVAult gives no error. (even when equipping that item again and saving the game)

I remembered that I got this same error a while back on the same character and I think that I got it on another one quite some time ago.

Hope it helps.

**Comment by creyo321** [comment]
Oh sorry, didn't see your last post before I posted mine.

If you mean by editing the game stash with TQVault in any way, I think I didn't. At least not intentionally.
I always put items in storage area, quit the game, and then duplicate over to TQVault stash.

**Comment by NorthFury** [comment]
Thank you for the details.

**Comment by epinter** [comment]
Looking at the winsys.dxb provided, I can see it is corrupted. There is a end_block after another, there's no stackCount or other information needed to make it a valid block.

**Comment by NorthFury** [comment]
I also encountered a scenario where TQVault created an invalid transfers stash file for me (I had a relic out of bounds).
