### ISSUE TITLE
Can't run v4.3.0 with both installer and extractor setup!

### ISSUE THREAD

**Issue by icefreeze88** [EtienneLamoureux/TQVaultAE#470]
Hello guys!
Thanks for supporting Titan Quest for long time till now!

I just installed TQVaultAE v4.3.0 and it just doesn't works, both installer and extractor setup method. The error message i got when run TQvaultAE 4.3.0 showed "The Vault patch was not set....."
With previous TQVaultAE version, i can just edit the config file, but v4.3.0 config file is different compared to what i was familiar as it doesn't showed any game path or vault path as before.
What should i do?

**Comment by hguy** [comment]
Hi @icefreeze88 ,

If you reused the same directory as an older version, delete everything inside "%USERPROFILE%\AppData\Local\titanquest.net_community" and restart.

The FAQ have been adjusted, but you can also look at that.
https://github.com/EtienneLamoureux/TQVaultAE/issues/467#issuecomment-1221505563

**Comment by icefreeze88** [comment]
I deleted all thing in the path you mention to, but the tool still doesn't run and give the same error message :(
I put the TQVaultAE folder into the game folder, the same with every previous TQVaultAE versions i use (it always works since v2.x.x till 4.2.0).

**Comment by hguy** [comment]
can you share the `UserConfig.xml` ?

**Comment by hguy** [comment]
That message show's up the first time you run the tool then it should not popup again.
![image](https://user-images.githubusercontent.com/31834707/188170679-0aef35c6-358d-4355-b88f-9ecda7b2716e.png)

It simply says that the default directory for vault storage will be used and that you can change it later from the settings window.

**Comment by hguy** [comment]
> With previous TQVaultAE version, i can just edit the config file, but v4.3.0 config file is different compared to what i was familiar as it doesn't showed any game path or vault path as before.

You can still do it, it's just explained in the FAQ, and the user settings are in the `UserConfig.xml` now.

**Comment by icefreeze88** [comment]
> > With previous TQVaultAE version, i can just edit the config file, but v4.3.0 config file is different compared to what i was familiar as it doesn't showed any game path or vault path as before.
> 
> You can still do it, it's just explained in the FAQ, and the user settings are in the `UserConfig.xml` now.

Thanks!  After change "AutoDetectGamepath" to 0, and set the path of TQ and TQIT, the tool works now.
