### ISSUE TITLE
Old TQVaultAE versions don't work after edited Userconfig.xml file for v4.3.0 work

### ISSUE THREAD

**Issue by icefreeze88** [EtienneLamoureux/TQVaultAE#472]
Heyllo guys! 
After i edited userconfig.xml file for v4.3.0 of the tool to works, all previous TQVaultAE version just don't work anymore. Any time try to start the old version tool, it showed error message "The vault path was not set...".
How can i do to make all versions works together? 
I noticed that there are many items in the vaults that the tool v4.3.0 don't showed, like it just disappeared. So i want to using the old one to get those items back and thing happened as i said above.
Thanks!

**Comment by icefreeze88** [comment]
After compressed v4.3.0 folder to .rar file and deleted the the this folder + edit the config.dll file of old previous TQVaultAE version, old previous tool can works now and i can see the old items that "disappeared" i mentioned in original post above (that is if using v3.9.0 or older version). But this is just too annoying to deal with. I think i will stick with old TQVault version so it can works the best to me.

**Comment by hguy** [comment]
what do you mean by "don't see" ?
The only way TQ doesn't see something, is because you try to use the "search" form without enabling "Preload All" in the settings.

**Comment by hguy** [comment]
you should not use both version together (there is no good reason for it) because , v4+ "convert" the old vault file the first time you request it then it **stop looking at it** and focus only on the new format.
So if you use both versions, you will make changes in old vault files that will not be seen by the new version. That's you problem. You misuse the tool.
If you want to reset the "vision" of the v4+ to the latest v3.9-, just remove all json files from you vault directory and v4+ will try to convert again old vault files up to date.

**Comment by hguy** [comment]
The only safe way to use both version, is as follow.

1. Enable "Hot reload" on both versions
2. Display the vault+shared stash in both versions
3. 1st tool, move the items from vault to shared stash and click save, it will popup in the shared stash of the other tool.
4. 2nd tool, move the item from the shared stash to your vault and click save, it will disapeared from shared stash in the 1st tool.

Basicaly, you use the game shared stash to tranfer items between tools, but as i said "it's not a life you want".
Voila!

And if you want to have both tools up and running, they must be installed in their own directory, not the same.

**Comment by hguy** [comment]
And the TQVault v3.9 ask you again about path because i asked you to delete everything in the "%USERPROFILE%\AppData\Local\titanquest.net_community" in a previous ticket because you wanted to reuse the same directory.

It's no big deal.

1. Edit your path in the `TQVaultAE.exe.config`
2. Delete everything in the "%USERPROFILE%\AppData\Local\titanquest.net_community"
3. Restart v3.9

That should be good

**Comment by icefreeze88** [comment]
I use the old one because as i said at previous post. There are items that showed in the vault with v3.9.0 or lower versions, but don't showed in the vault of v4.3.0.
And to be honest, i feel so much easier to searching things with v3.1.0 or so. This' the reason i don't using later version till some relic/charm game devs added to game don't showed in v3.1.0.

**Comment by hguy** [comment]
I want an example of such invisible items! So i can fix the later versions.
Could you post here a zip with the vault file containing that item ?

**Comment by icefreeze88** [comment]
I move item from vault to character by v3.9.0 then move it to vault of v4.3.0.
It seems v4.3.0 vault doesn't update items after installed, it keep using the vault database that imported 1st time with v4.0.0 before :(.

**Comment by hguy** [comment]
It's explained here.
https://github.com/EtienneLamoureux/TQVaultAE/issues/472#issuecomment-1236613754
And the "how to" reset all v4+ vaults to 3.9 vision in one action.

**Comment by icefreeze88** [comment]
> It's explained here. [#472 (comment)](https://github.com/EtienneLamoureux/TQVaultAE/issues/472#issuecomment-1236613754) And the "how to" reset all v4+ vaults to 3.9 vision in one action.

Thanks! 
I was deleted all .json file after compressed it for backup, and run v4.3.0 and it "update" all items too.

OT: Is there any way to set the delay time so the vault detail box appeared more 2 or 3, or even longer later when i move the mouse cursor to vault tab? Everytime i hover mouse cursor to the vault tab, the the detail box appear to showed list of items in the vault is very annoying.

**Comment by hguy** [comment]
You can disable tooltip if you are annoyed.
![image](https://user-images.githubusercontent.com/31834707/188807978-5b66342a-535c-4a5e-bc48-df1c677d028b.png)

**Comment by icefreeze88** [comment]
Thanks!
