### ISSUE TITLE
Dream affixes are unavailable

### ISSUE THREAD

**Issue by ConchordCourier** [EtienneLamoureux/TQVaultAE#473]
The dream mastery affixes are unable to be found:
Dreamweaver
Augur

The affixes are seen in the screenshot when explaining the feature

**Comment by hguy** [comment]
all items does not have all affixes. How do you know your item should have such affix ?

**Comment by hguy** [comment]
ultimately, you can use the forge to apply any affix to any items.

**Comment by ConchordCourier** [comment]
> all items does not have all affixes. How do you know your item should have such affix ?

I specifically tried weapons that have had the dream affixes before in my previous playthroughs, so I'm quite sure there is an issue with the vault and not the weapons I am using.

**Comment by ConchordCourier** [comment]
> ultimately, you can use the forge to apply any affix to any items.

I know, I'm just raising the issue that there are affixes missing, it doesn't personally bother me.
