### ISSUE TITLE
TQVaultAE asks for a vault path and then exits with an error

### ISSUE THREAD

**Issue by gongalov71** [EtienneLamoureux/TQVaultAE#474]
Hello
I'm using Windows 11 and Steam version of TQAE. After installing TQVault AE it asked me for a vault path but there was no way to set it up. Then TQVaultAE said it will use the default path and after I pressed OK it gives me this error:

![TQVaultAE_error](https://user-images.githubusercontent.com/115870458/195979234-580c839d-072e-49fc-a129-2058e126fd58.png)

Can anyone help me resolve this issue?
Thank you

**Comment by hguy** [comment]
Hi!

There's a [FAQ](https://github.com/EtienneLamoureux/TQVaultAE#troubleshooting-and-faq) on the main page explaining how to set these path manually.

This [thread](https://github.com/EtienneLamoureux/TQVaultAE/issues/467#issuecomment-1221505563) also talk about it.

**Comment by gongalov71** [comment]
I fixed it, thank you
