### ISSUE TITLE
Forge does not work

### ISSUE THREAD

**Issue by Serimert90** [EtienneLamoureux/TQVaultAE#476]
I cant choose any base item. There is no button/combobox/text area
![image](https://user-images.githubusercontent.com/16742552/202561433-75db8088-bb0b-40c3-b075-130e624d5113.png)

**Comment by hguy** [comment]
Drag & Drop items from left Vault to right Forge

**Comment by Serimert90** [comment]
Where do you create that base items? I do not have any. I lost my progression so i wanna build some relics and items.

**Comment by hguy** [comment]
It alter the base item in it's original place

**Comment by Serimert90** [comment]
Ok thanks, so any way to generate items from scratch?

**Comment by hguy** [comment]
nope! you need few items. The Forge is juste a way of combining existing items.
