### ISSUE TITLE
God Mode Forge - No bonus from 1st/2nd relic when using item base

### ISSUE THREAD

**Issue by PalasX** [EtienneLamoureux/TQVaultAE#477]
When using the forge in "god mode", you can use the base item attributes from non-relic items in place of the 1st and 2nd relic.

In game, these don't seem to be added to the item or character sheet in any way. Often time the game seems to just "drop" the 2nd relic slot entirely, but you'd only know by saving and quitting and then opening TQVaultAE again to see if the 2nd relic still exists.

Is this a known issue or the way TQ handles relic bonuses?

![image](https://user-images.githubusercontent.com/37154966/207486999-3d3aec9d-8f38-48ae-87d1-e88d0d5fb617.png)

**Comment by hguy** [comment]
Hello
Yes! Ultimately, the game may ignore some combination.
The forge won't warn/restrict you.
