### ISSUE TITLE
What does this percentage value represent after item seed?

### ISSUE THREAD

**Issue by ezloj** [EtienneLamoureux/TQVaultAE#479]
![image](https://user-images.githubusercontent.com/16278882/208883924-cfb65b20-0f76-4baf-b451-d075339a2cc5.png)

**Comment by ejfudd** [comment]
The item seed has a range of 0-32767 (0x7FFF) and it's the percentage of your item seed against the maximum value.
Take 23444 / 32767 and you get 71.545%.
In the big picture, it really does not mean much since it's not known how that value affects the actual stats on the item.

**Comment by ezloj** [comment]
Thank you for the explanation
