### ISSUE TITLE
Error Loading Resources

### ISSUE THREAD

**Issue by Slexom** [EtienneLamoureux/TQVaultAE#48]
![immagine](https://user-images.githubusercontent.com/9221469/34343019-1e93b8f4-e9c3-11e7-86cc-28b2e577ff85.png)
_In red the translation from italian_
Downloaded latest version, the error in the screenshot cannot let me start the program.
This is the content of GamePath.txt
```
# The line bellow should contain the path where you have Titan Quest installed.
D:\Titan Quest Anniversary Edition Ragnarok
```
Where D:\Titan Quest Anniversary Edition Ragnarok is where i have the game installed. Any solution to this issue?

**Comment by NorthFury** [comment]
Can you check if the exe files are in that location? They should be there. `D:\Titan Quest Anniversary Edition Ragnarok\Database\database.arz` should exist.

I think the error is there because of the extra empty line. I should have ignored empty lines too. Please remove the empty line and try again.

**Comment by Slexom** [comment]
TQ exe is in that location, `D:\Titan Quest Anniversary Edition Ragnarok\Database\database.arz` exist, same issue removing the empty line

**Comment by NorthFury** [comment]
I can't figure out why it fails. A wild guess is an error while reading the game data files but I'm not sure about it. I would debug this but I can't reproduce it.

**Comment by epinter** [comment]
Can you try this test-version ? This version don't use the .txt file, after first run, you will see a .ini that have an option called ForceGamePath where you can put the game directory IF THE AUTODETECTION FAILS.
[TQVaultAE.zip](https://github.com/EtienneLamoureux/TQVaultAE/files/1586396/TQVaultAE.zip)

**Comment by Slexom** [comment]
The test build work fine.

**Comment by epinter** [comment]
Nice, now we know how to solve the issue on next version. Thank you.
