### ISSUE TITLE
How to run the tool in Wine?

### ISSUE THREAD

**Issue by MichalkapDeveloper** [EtienneLamoureux/TQVaultAE#483]
[TQVaultAE_2023.02.11.txt](https://github.com/EtienneLamoureux/TQVaultAE/files/10714659/TQVaultAE_2023.02.11.txt)

**Comment by hguy** [comment]
You should read that comment https://github.com/EtienneLamoureux/TQVaultAE/issues/377#issuecomment-1242982483
