### ISSUE TITLE
Using ARZ Explorer 2.0

### ISSUE THREAD

**Issue by rsholokh** [EtienneLamoureux/TQVaultAE#486]
How can I use ARZ Explorer 2.0, which was updated on February 1, 2023, since it is part of TQVault, whose last release 4.3.0 was August 17, 2022. Can I independently build ARZ Explorer 2.0 for my own use or something like that?

**Comment by ejfudd** [comment]
ARZ Explorer has dependencies on some TQVaultAE files, so it is not entirely standalone.  The simplest thing would be to build the current master of TQVaultAE and use ARZ Explorer from there.

**Comment by rsholokh** [comment]
I've tried it, but I'm not familiar with C# and I get a lot of different errors during the process. Is there any description of build process?

**Comment by ejfudd** [comment]
Here is basically how it's done:
Download the zip file of the source.
Extract to wherever you put source code.  The zip will create a TQVaultAE-master folder and put everything in there.
Launch Visual Studio 2022 and click on open a project or solution.  If you use an older version, you will get errors. Also don't know if VSCode will work either.
Navigate to TQVaultAE.sln which is in the TQVaultAE-master folder.
Once the solution loads, go to Build->Build Solution.

**Comment by rsholokh** [comment]
Thanks man, everything built perfectly in Visual Studio 2022. The only thing I didn't know was to set [nuget.org/api/v2](https://www.nuget.org/api/v2) address in **Debug->Options->NuGet Package Manager->Package Source** because it's not set by default, I have no idea why. I hope this might be useful to someone!
