### ISSUE TITLE
Can't fix my issues

### ISSUE THREAD

**Issue by SimSim82** [EtienneLamoureux/TQVaultAE#488]
Hello, I have this problem where I could not path a way to my files, an error message appears 

![image](https://user-images.githubusercontent.com/128506092/226668069-d4de3468-f531-46d7-9e7d-ca6e2da01aab.png)

I put this code who seems the same as the FAQ, so what's wrong

**Comment by ejfudd** [comment]
Pay close attention to your tags around the paths.  You need to fix your slashes.

See this from the example in the FAQ:
<TQITPath>C:\examplePath\Titan Quest Anniversary Edition</TQITPath>
<TQPath>C:\examplePath\Titan Quest Anniversary Edition</TQPath>
