### ISSUE TITLE
Could Not Load Text DB

### ISSUE THREAD

**Issue by Giant2005** [EtienneLamoureux/TQVaultAE#49]
I have had this issue in the past. However thanks to some advice from North, my issue was resolved successfully.
That advice being:
You will most likely need to edit the config file by hand. Go to c:\Users\<user>\AppData\Local\titanquest.net_community\ Then drill down until you find user.config . Edit this file and add the content of this file there: https://pastebin.com/iHPEdBvi . Then all you need to do is put the right paths in there. Last but no least, once the applicatin starts, don't forget to go to the configuration and edit the settings to match your preferences.

The problem is that since then, I have uninstalled and reinstalled the game. The issue has returned but the fix no longer works (I have also upgraded from TQVaultAE_2.5.1.2 to TQVaultAE_2.5.2 but even after reverting back to 2.5.1.2 I still get the same error).

The exact error reads as follows:
Could Not Load Text DB.
This may be caused by a bad language or game path setting.
Would you like to restart TQVault?

Restarting is of no help as the error returns each time.

There is no GamePath.txt file to edit.

The contents of my C:\Users\A\AppData\Local\TQVault\TQVault.exe_Url_0lwizdaof0v0bjzojaxyshghhew1qnly\2.3.1.4\user.config
file are the following; all of the directories are correct (and rechecked more than a couple of dozen times):

<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <userSettings>
        <TQVaultAE.GUI.Properties.Settings>
            <setting name="SkipTitle" serializeAs="String">
                <value>True</value>
            </setting>
            <setting name="LoadLastVault" serializeAs="String">
                <value>True</value>
            </setting>
            <setting name="LoadLastCharacter" serializeAs="String">
                <value>True</value>
            </setting>
            <setting name="LastVaultName" serializeAs="String">
                <value>Main Vault</value>
            </setting>
            <setting name="LastCharacterName" serializeAs="String">
                <value />
            </setting>
            <setting name="AutoDetectLanguage" serializeAs="String">
                <value>True</value>
            </setting>
            <setting name="AutoDetectGamePath" serializeAs="String">
                <value>False</value>
            </setting>
            <setting name="TQLanguage" serializeAs="String">
                <value />
            </setting>
            <setting name="VaultPath" serializeAs="String">
                <value>C:\Users\A\Documents\My Games\Titan Quest\TQVaultData</value>
            </setting>
            <setting name="LoadAllFiles" serializeAs="String">
                <value>True</value>
            </setting>
            <setting name="SuppressWarnings" serializeAs="String">
                <value>False</value>
            </setting>
            <setting name="AllowItemCopy" serializeAs="String">
                <value>False</value>
            </setting>
            <setting name="AllowItemEdit" serializeAs="String">
                <value>False</value>
            </setting>
            <setting name="TQITPath" serializeAs="String">
                <value>C:\Games\Titan Quest Anniversary Edition Ragnarok</value>
            </setting>
            <setting name="TQPath" serializeAs="String">
                <value>C:\Games\Titan Quest Anniversary Edition Ragnarok</value>
            </setting>
            <setting name="ModEnabled" serializeAs="String">
                <value>False</value>
            </setting>
            <setting name="CustomMap" serializeAs="String">
                <value />
            </setting>
            <setting name="LoadAllFilesCompleted" serializeAs="String">
                <value>True</value>
            </setting>
            <setting name="PlayerReadonly" serializeAs="String">
                <value>True</value>
            </setting>
        </TQVaultAE.GUI.Properties.Settings>
    </userSettings>
</configuration>

**Comment by Giant2005** [comment]
That config copy/paste dump obviously didn't work. Here is a second attempt:

`<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <userSettings>
        <TQVaultAE.GUI.Properties.Settings>
            <setting name="SkipTitle" serializeAs="String">
                <value>True</value>
            </setting>
            <setting name="LoadLastVault" serializeAs="String">
                <value>True</value>
            </setting>
            <setting name="LoadLastCharacter" serializeAs="String">
                <value>True</value>
            </setting>
            <setting name="LastVaultName" serializeAs="String">
                <value>Main Vault</value>
            </setting>
            <setting name="LastCharacterName" serializeAs="String">
                <value />
            </setting>
            <setting name="AutoDetectLanguage" serializeAs="String">
                <value>True</value>
            </setting>
            <setting name="AutoDetectGamePath" serializeAs="String">
                <value>False</value>
            </setting>
            <setting name="TQLanguage" serializeAs="String">
                <value />
            </setting>
            <setting name="VaultPath" serializeAs="String">
                <value>C:\Users\A\Documents\My Games\Titan Quest\TQVaultData</value>
            </setting>
            <setting name="LoadAllFiles" serializeAs="String">
                <value>True</value>
            </setting>
            <setting name="SuppressWarnings" serializeAs="String">
                <value>False</value>
            </setting>
            <setting name="AllowItemCopy" serializeAs="String">
                <value>False</value>
            </setting>
            <setting name="AllowItemEdit" serializeAs="String">
                <value>False</value>
            </setting>
            <setting name="TQITPath" serializeAs="String">
                <value>C:\Games\Titan Quest Anniversary Edition Ragnarok</value>
            </setting>
            <setting name="TQPath" serializeAs="String">
                <value>C:\Games\Titan Quest Anniversary Edition Ragnarok</value>
            </setting>
            <setting name="ModEnabled" serializeAs="String">
                <value>False</value>
            </setting>
            <setting name="CustomMap" serializeAs="String">
                <value />
            </setting>
            <setting name="LoadAllFilesCompleted" serializeAs="String">
                <value>True</value>
            </setting>
            <setting name="PlayerReadonly" serializeAs="String">
                <value>True</value>
            </setting>
        </TQVaultAE.GUI.Properties.Settings>
    </userSettings>
</configuration>`

**Comment by epinter** [comment]
Can you try the test-build I posted in the issue https://github.com/EtienneLamoureux/TQVaultAE/issues/48 ?

**Comment by Giant2005** [comment]
Unless I am doing something wrong, that test build gets the same error. This is what I have in the TQVaultAE.config file:

`# Created by TQVaultAE
# Use Y and N for booleans
# Don't use any kind of quotes 
[Main]
ShowEditingCopyFeatures=Y
ForceGamePath=C:\Games\Titan Quest Anniversary Edition Ragnarok
Mod=
`

**Comment by epinter** [comment]
I don't see anything wrong ... Try to delete the directory "AppData\Local\TQVault" and all contents of TQVault directory (where it is installed).

**Comment by epinter** [comment]
As a test, try to change the game language to English.

**Comment by Giant2005** [comment]
I am using English.
I deleted both both the AppData folder and the directory where it is installed and it changed nothing either.
I finally decided that the stupid GOG version of the game was at fault, so I went and installed the Steam version. Surprisingly, the Steam version is suffering from the same issue.
Although while uninstalling the GOG version I did notice something that may be the culprit - there was a registry entry for an old version of the game. I am going to get CCleaner to remove that erroneous registry entry to see if that helps.

**Comment by Giant2005** [comment]
Well the erroneous registry entry had nothing to do with it but I did fix the problem.
I was editing the wrong config file.
The one I was editing was within AppData/Local/TQVault; while the one I was supposed to be editing was located within AppData/Local/titanquest.net_community

It was a simple case of me not following instructions.

**Comment by NorthFury** [comment]
This is the old installation key that you would need to remove to clean the old installation registry keys (regedit.exe can be used to do this): `SOFTWARE/Iron Lore/Titan Quest/Install Location`
