### ISSUE TITLE
ADM DELETE THIS POST (SOLVED)

### ISSUE THREAD

**Issue by ghost** [EtienneLamoureux/TQVaultAE#490]
Hello.
I've been playing TQ along with TQ Vault for quite a long time now. I know the basics of how to use it, both with the game closed or running on background. Thing is I think I screwed up my entire game.

I was playing with my character today and noticed that all the relics have disappeared from my Relic Vault. Also, the Relic Vault has only 1/3 of its size. Same thing happened to my Storage area. It has 1/3 of its size, despite I already bought all the upgrades.
If I click on the auto sort button, the game crashes. This has happened to every character (I think I have +30 characters).

![image](https://user-images.githubusercontent.com/130387422/230942841-34769d38-e450-409e-a452-da5bda08d909.png)

Same thing happens in the TQ Vault application. All my relics are gone and I can't even open the Relic Vault or Storage tabs 'cause the program freezes.

![image](https://user-images.githubusercontent.com/130387422/230943563-b2623b5a-5ac4-4eaf-a462-5b172e3ef7c5.png)

I tried validating files through Steam properties, but didn't change anything. I've also reinstalled the game and the problem persists.
I dunno what I did wrong. I did everything I normally do. I never move itens from the Storage area when I'm playing with that character. I never move itens from the Transfer area if I'm interacting with the caravan driver in game.
But I have a suspicious: I might have been careless and transferred a spell piece from my character's Storage area to the Transfer area through TQ Vault. I dunno if this is a forbidden action, since that's a quest item. That's the only thing I think I could've done wrong.

If anyone could help me to fix the game. 
Is there a way to fix it without losing my characters? I don't use Steam Cloud. I have a backup of my characters files.
Also, is there a way to fix it without losing my items collection? I also have a backup of these files.

I would appreciate any help.
Thanks in advance.

**Comment by renangflores** [comment]
I tried moving all my characters save files to another folder and starting the game with a fresh character. Same results.
