### ISSUE TITLE
Item properties are displayed incorrectly

### ISSUE THREAD

**Issue by nierewa** [EtienneLamoureux/TQVaultAE#491]
Hi,

thanks for this great program 👍 

The properties of blue and purple items are displayed incorrectly.
The Items had always the same properties, but they are not correct.

For example:

The item in the inventory:
![stash](https://user-images.githubusercontent.com/68892656/234375466-f849fe26-8207-4393-95e4-ad834b3fdc35.png)

The item in the inventory how its been displayed in TQVaultAE:
![vault](https://user-images.githubusercontent.com/68892656/234375472-5e8be3a0-6fe1-4fa3-aff2-060274bd5842.png)

**Comment by joris-s-k** [comment]
Items have variations in their stats based on their seed. TQVault can only display the base values of an item.

**Comment by nierewa** [comment]
I see.
That's very pitty. So you can't compare the items in the vault.

Will this function be available at some point?

**Comment by hguy** [comment]
> Will this function be available at some point?

Probably not! Unless someone succeed at reverse engineer the algorithm.

**Comment by nierewa** [comment]
Why does it work with Monstersets?

![monsterset](https://user-images.githubusercontent.com/68892656/235896101-cca1acdf-868c-4041-b696-7fc034b44d46.png)

**Comment by EtienneLamoureux** [comment]
All items will show their base values, unmodified by their seed. Rarity does not play a role unfortunately.
