### ISSUE TITLE
The Stash file cannot be found - Converting Android save to PC

### ISSUE THREAD

**Issue by Dropboy** [EtienneLamoureux/TQVaultAE#492]
Hi,

Please let me know if you need me to provide more. I've converted some characters through TQRespec from android to PC, I get this error when loading into TQVault. I was wondering if there is anyway to convert the android stash files to PC as well? Or is my best bet to move everything through my inventory bags? Thanks for your hard work!

![image](https://user-images.githubusercontent.com/12470562/234526912-43c84417-9b5c-4b7b-9680-4ee5d25bbef1.png)

**Comment by hguy** [comment]
It's not an error message but more of a warning.
Considering TQRespect choose to ignore caravane file conversion, i bet it's because the logic is not cracked yet.
That being said, you could provide here your android stash with few basic items inside for study.
