### ISSUE TITLE
Fake displayed item stats

### ISSUE THREAD

**Issue by WeaponsPrime** [EtienneLamoureux/TQVaultAE#50]
Some of the items' displayed stats in TQVault seem to differ from in-game stats. Moreover, items' displayed stats seem to be inconsistent between successive TQVault runs: stat values may be switched between items of the same type.
This problem reproduces on the rings from the following vault: all of the rings there offer lightning resistance of maximum 36%, and TQVault consistently displays values in 45-56% range for some of them. Displayed resistances on every ring seem to depend only on its position in the vault.
[Test.zip](https://github.com/EtienneLamoureux/TQVaultAE/files/1594727/Test.zip)

**Comment by EtienneLamoureux** [comment]
The fact that stats differ from what is seen in-game is expected and explained in the [F.A.Q.](https://github.com/EtienneLamoureux/TQVaultAE#troubleshooting-and-faq), but the changing stats are definitely worth looking into.
