### ISSUE TITLE
Would it be okay to use ARZExplorer and re-publish it on github?

### ISSUE THREAD

**Issue by ezloj** [EtienneLamoureux/TQVaultAE#507]
Hello.

I am writing a tool for TQAE to merge mods (with an interface to simplify merging) that would also automatically build them, produce and manage the database.arz and automatically unpack resources. The tool is being built here: https://github.com/ezloj/TQModdingAdvanced

I need a way to unpack the game's .arz files. Would it be fine to re-use your ARZExplorer tool?
I'd need to bundle the executable along with my tool though as I'm using python. I would give the credit for the tool to the author and reference this repository as the source.

**Comment by hguy** [comment]
Hi @ezloj.
Nice tool your mod merger.
I don't see any problem bundling ARZExplorer.
As you said, just reference this repo with the exec.
@EtienneLamoureux any requierement ?

**Comment by EtienneLamoureux** [comment]
Yes, that falls under the terms of the https://github.com/EtienneLamoureux/TQVaultAE/blob/master/LICENSE :)

**Comment by ezloj** [comment]
Thanks guys :)
