### ISSUE TITLE
TQVault doesn´t start cause of System.NullReferenceException

### ISSUE THREAD

**Issue by JoesenJoe** [EtienneLamoureux/TQVaultAE#508]
When i try to start TQVaultAE.exe, the following info shows up: (I am using TQVaultAE_4.4.0 and desperately need some formula)

![F1](https://github.com/EtienneLamoureux/TQVaultAE/assets/145790480/7ab16665-4d51-4296-b01e-6bb39ff5b2d9)

I have installed the following version of TQ (according to homescreen ingame):
vTQ Anniversary v2.10.19520 (the game itself works fine)

I have no idea what to do. Looking at the posts, you seem to have solutions for everything. Can someone please give feedback here?

**Comment by hguy** [comment]
Looks like you need to setup the manually the game path.
Look at the detailed explanation in the FAQ at https://github.com/EtienneLamoureux/TQVaultAE
