### ISSUE TITLE
Can't use the search function

### ISSUE THREAD

**Issue by NOTLK34** [EtienneLamoureux/TQVaultAE#51]
I started using the latest version of TQVaultAE, 2.5.2.0, a couple of days ago (I haven't used any previous versions) and whenever I try to search for something I get the following error message.

![image](https://user-images.githubusercontent.com/32428488/34464627-d2835658-ee55-11e7-8b6f-09767e80b282.png)

**Comment by NorthFury** [comment]
Could you please add an archive with your vault files and save games here? This would help us reproduce the bug.

**Comment by NOTLK34** [comment]
The save files were to big to upload here.

[TQVaultData.zip](https://github.com/EtienneLamoureux/TQVaultAE/files/1598523/TQVaultData.zip)
[SaveData-Main.zip](https://mega.nz/#!dw1QlbgI!LqIh4HU18TECaCgYv5Xha2tB_5CNAVd8mEZjrczh51o)

**Comment by NorthFury** [comment]
A new version with the fix applied has been released. Thank you for creating the issue and providing the save files.
