### ISSUE TITLE
Not adding the "Complete Relic Bonus" in player stats

### ISSUE THREAD

**Issue by kadoon** [EtienneLamoureux/TQVaultAE#511]
Hi,

Apparently, TQVault is not adding the "Complete Relic Bonus". Below are prints with and without items.

Another thing I noticed is the wrong relic value compared to TQVault and the game.

Versions:
TQVault: 4.4
Titan Quest Anniversary Edition (steam): 2.10.21415 (Eternal Ember)

![tq_1](https://github.com/EtienneLamoureux/TQVaultAE/assets/1138137/11168cc5-74ba-43eb-bcdb-f4e12a5c5b89)
![tq_2](https://github.com/EtienneLamoureux/TQVaultAE/assets/1138137/a510efc4-d708-4f2d-90e7-b8f4eff90027)

**Comment by EtienneLamoureux** [comment]
Hello!
Anything that has to do with the random number generator will only show base stats in the tool, as we haven't cracked how the seeds impact the RNG. See the first question under https://github.com/EtienneLamoureux/TQVaultAE?tab=readme-ov-file#troubleshooting-and-faq for details.
