### ISSUE TITLE
when i open tq i get a couple errors ive no idea what they are 

### ISSUE THREAD

**Issue by neverdoom7** [EtienneLamoureux/TQVaultAE#513]
![image_2024-03-08_183452722](https://github.com/EtienneLamoureux/TQVaultAE/assets/162761401/bbee5797-7bc2-4f2c-8dde-db0ef01adc9e)
![image_2024-03-08_183515902](https://github.com/EtienneLamoureux/TQVaultAE/assets/162761401/b1626be4-ef36-469c-b0d7-10e704a04920)

ive no idea what they are or mean and ive no idea what to do

**Comment by hguy** [comment]
Somehow the program fail to read Json vault files.
Maybe one of them is corrupted or a sector of your harddrive is corrupted.
Move all of the vault files outside it's directory and reintroduce them progressively, checking at each step by running the program.
Directory : `%USERPROFILE%\Documents\my games\Titan Quest\TQVaultData`

**Comment by neverdoom7** [comment]
Thx I fixed it by deleting my old data from when I used it before
