### ISSUE TITLE
当我想打开 TQVaultAE 时会弹出这个窗口，我不知道该怎么办了

### ISSUE THREAD

**Issue by ririye** [EtienneLamoureux/TQVaultAE#518]
![VXM 76{%8 4DR@4)_%6FM`Y](https://github.com/user-attachments/assets/8d487d96-c8f5-45e7-b652-7e5b3493daf5)

**Comment by ririye** [comment]
What's wrong?

**Comment by hguy** [comment]
It looks like the tool is unable to find Titan Quest install directory.
Follow the instructions in the [FAQ](https://github.com/EtienneLamoureux/TQVaultAE?tab=readme-ov-file#troubleshooting-and-faq) for manual setup.
