### ISSUE TITLE
The best seed for all item is 0xFFFFFFFE

### ISSUE THREAD

**Issue by wzzb521** [EtienneLamoureux/TQVaultAE#522]
0xFFFFFFFE or -2 (signed int32) 
I saw this in a CE table. It works for all item.

**Comment by CristianLK** [comment]
But you can't assign that seed with TQVault, how are you supposed to do it?

**Comment by ejfudd** [comment]
Unless the expansions changed the item generation code, internally the seed is limited to 15 bits (0x7fff) and TQVault followed that limitation.
