### ISSUE TITLE
UI Bug

### ISSUE THREAD

**Issue by Rannix1** [EtienneLamoureux/TQVaultAE#61]
Restart no help. 1280x1024

![2018-02-09_024930](https://user-images.githubusercontent.com/36284678/36006168-04f5afb6-0d44-11e8-9481-30f16993ab7c.png)

**Comment by epinter** [comment]
Go to %LOCALAPPDATA% and delete all subdirectories inside the directory "titanquest.net_community", if this doesnt help probably your issue is this: https://github.com/EtienneLamoureux/TQVaultAE/issues/21

**Comment by Rannix1** [comment]
Ok, wait update. Nothing helped
