### ISSUE TITLE
Combo box flickering

### ISSUE THREAD

**Issue by NorthFury** [EtienneLamoureux/TQVaultAE#75]
The combo box is flickering on slow mouse over.

**Comment by epinter** [comment]
I don't have any flickering here... What exactly is flickering ? The control or the list when is open ?

Can you try to remove the method below ?

		protected override void WndProc(ref Message m)
		{
			base.WndProc(ref m);

			Graphics g = Graphics.FromHwnd(Handle);

			if (m.Msg == WM_PAINT)
			{
				Rectangle bounds = new Rectangle(0, 0, Width, Height);
				ControlPaint.DrawBorder(g, bounds, Color.FromArgb(223, 188, 97), ButtonBorderStyle.Solid);
			}
		}

**Comment by epinter** [comment]
Another test... Can you try to add this method to ScalingComboBox.cs while keeping everything else the way it is now ?

protected override CreateParams CreateParams {
  get {
    CreateParams cp = base.CreateParams;
    cp.ExStyle |= 0x02000000;  // Turn on WS_EX_COMPOSITED
    return cp;
  }
} 


Sorry for all these requests, but I don't have how to test this bug, tried two different PC.

**Comment by NorthFury** [comment]
I tested all combinations for the first suggestion. The suggestion in the second comment results in a run time error.

**Comment by NorthFury** [comment]
It is happening on mouse over the border only.

**Comment by epinter** [comment]
Nothing solved the problem ?
