### ISSUE TITLE
Error loading resources

### ISSUE THREAD

**Issue by Willow321Go** [EtienneLamoureux/TQVaultAE#80]
Hello, When I open TQVaultAE and I happen to have any other steam game installed I get an error that aborts TQVaultAE the error following: "Could not find a part of the path '(Drive letter)\Program files x86\Steam\SteamApps\libraryfolders.vdf' This may be caused by a bad language or game path setting." any help resolving this error would be greatly appreciated?

**Comment by AmineFellous** [comment]
Same issue here (it try to load a file, the same mentioned above, bur from another steam game directory)

**Comment by EtienneLamoureux** [comment]
Try turning off `AutoDetectGamePath`. See "**Q. I have this game as a stand-alone (i.e. not through Steam or GOG). How can I make TQVaultAE work?**" under the [F.A.Q.](https://github.com/EtienneLamoureux/TQVaultAE#troubleshooting-and-faq)

**Comment by VictorJozwicki** [comment]
Seems to have been resolved ? Maybe close it ?
