### ISSUE TITLE
Startup error

### ISSUE THREAD

**Issue by NorthFury** [EtienneLamoureux/TQVaultAE#81]
Issue reported on the steam guide page: I assume it happened on the first run.
![screenshot](https://i.gyazo.com/25d370b7c2471b2096fd152f7b4b0182.png)

**Comment by epinter** [comment]
Why open this kind of issue ? It's not a software bug.

**Comment by NorthFury** [comment]
I guess I should have googled the error first. Closing because it's a host system issue.
