### ISSUE TITLE
Error to load status of some excluvise Ragnarok set items.

### ISSUE THREAD

**Issue by EvandroPimpo** [EtienneLamoureux/TQVaultAE#82]
"Brennus' Pride", "The Shade" and "Guise of the Horned God"'s items do not shows it status, causing an error.

**Comment by KenAlin** [comment]
Hi,
I generated these items by tweaking TQ Vault, but the only problem I found is a missing tag on Brennus' Striped Pants. 
[Issue-82 (vault file).zip](https://github.com/EtienneLamoureux/TQVaultAE/files/2571549/Issue-82.zip)

**Comment by EtienneLamoureux** [comment]
Fixed by https://github.com/EtienneLamoureux/TQVaultAE/pull/98
