### ISSUE TITLE
TQVaultAE.exe doesn't work any longer

### ISSUE THREAD

**Issue by Topfen** [EtienneLamoureux/TQVaultAE#85]
Hi,I posted this on the steam forums already, so I'll just c&p my issue:

> hi, since the old Vault isn't working with Ragnarok i just decided to give the AEversion a shot (https://github.com/EtienneLamoureux/TQVaultAE)
> so i got the zip (tried both 2.5.6 and the former), extracted it to a new folder and tried to run the exe. immediately the message popped up, that the exe is no longer working. i'm using win10 so i tried different settings (start as admin, compatibility mode with all kinds of windows) but nothing changed.
> neither the FAQ nor the config offers clarification. help would be appreciated

**Comment by EtienneLamoureux** [comment]
@Topfen Do you have a screenshot or transcript of that error message?

**Comment by EtienneLamoureux** [comment]
@Topfen Is the error you're getting "Error Loading Resources. This may be caused by a bad language or game path setting."? If so, we've updated the [F.A.Q.](https://github.com/EtienneLamoureux/TQVaultAE#troubleshooting-and-faq)

**Comment by EffigySkyfire** [comment]
> @Topfen Is the error you're getting "Error Loading Resources. This may be caused by a bad language or game path setting."? If so, we've updated the [F.A.Q.](https://github.com/EtienneLamoureux/TQVaultAE#troubleshooting-and-faq)

Hi, I'm getting the same error. 

I'm trying to use "TQVaultAE_2.5.7-alpha", but the program simply stopped the very moment I double-clicked and started it.

**The error is not indicated by TQVault program itself.**Actually I cannnot see the TQVault window before it stops. 

There is only a message from windows system saying simply that "TQVault AE has stopped working, please wait while windows sending report to microsoft”. There seems to be no "tqdebug.txt" generated, as in some bug case.


I've been using the old TQVault 2.18 and it works normally on the same computer. I have met the game path setting error before and managed to find how to solve it  so I don't think this is the cause of the current problem being described.

Thanks for your help and your great effort in developing this great tool！

**Comment by EtienneLamoureux** [comment]
@EffigySkyfire Thanks for the reply. It will be hard to debug without any error log of any kind. We'll try to find a solution or at least try to improve the reporting in case of errors. By any chance, is your error in the [legacy help file](https://github.com/EtienneLamoureux/TQVaultAE/blob/master/documentation/TQVault%20common%20issues.pdf)?

**Comment by hlllovefmy** [comment]
It may caused by incompatible VXPLib.dll between 2.18 and TQVaultAE. Try to unreginster VXPLib.dll of old version by execute "regsvr32 /u VXPLib.dll" in cmd with admin privilege and then run TQVaultAE again.

**Comment by EtienneLamoureux** [comment]
Thanks a lot @hlllovefmy !
