### ISSUE TITLE
Make "held" item drop in a predictable spot when closing the tool

### ISSUE THREAD

**Issue by Zyphruss** [EtienneLamoureux/TQVaultAE#86]
When completing a relic in the vault with some extra shards left over, you basically have to put the extra shards down in the vault pocket and restart TQVaultAE. Otherwise there is no telling where they will actually be when you restart TQVault.

**Comment by hguy** [comment]
@EtienneLamoureux the tool is already handling this case by forcing the user to place the leftover somewhere when you try to close.
So the user knows where the leftover is.
This can be closed.
![image](https://user-images.githubusercontent.com/31834707/185716907-d8972c21-16f0-4da8-9afe-62eb1bd01b88.png)
