### ISSUE TITLE
Copy item (feature request)

### ISSUE THREAD

**Issue by Zyphruss** [EtienneLamoureux/TQVaultAE#88]
With the old TQVault I kept all my found uniques in the vault and equipped the heroes with copies of those, so I didn't lose track of where they are. Would be nice to have a function that copies items in the right click menu in TQVaultAE.

**Comment by EtienneLamoureux** [comment]
We have that function! Check out the [configuration](https://github.com/EtienneLamoureux/TQVaultAE#configuration)
