### ISSUE TITLE
Add a "no cheat" mode

### ISSUE THREAD

**Issue by EtienneLamoureux** [EtienneLamoureux/TQVaultAE#9]
- Allow the user to run a "no cheat" mode through a launch parameter
  - Disable item copying
  - Disable item editing features
- Disable "configure menu" options for cheating when the program's been launched in "no cheat" mode

**Comment by epinter** [comment]
Can be closed if https://github.com/EtienneLamoureux/TQVaultAE/pull/45 is merged
