### ISSUE TITLE
[Suggestion] Support for Enhanced Gameplay's Expanded Inventory

### ISSUE THREAD

**Issue by drakray** [EtienneLamoureux/TQVaultAE#95]
As seen at https://steamcommunity.com/sharedfiles/filedetails/?id=1389634981, EG change player/caravan inventory size/shape, it would be awesome if your Vault could have an option/config to support it, instead of having to move thing in-game before vaulting.

Thanks :D

**Comment by EtienneLamoureux** [comment]
That's an interesting mod, but has it is not the vanilla game, I'll focus on polishing the experience for that first.
Nonetheless, I'll keep it on the list!

**Comment by drakray** [comment]
I understand.
Maybe even just a config for inventory display size could work though, because as of now even "out of grid" item can be shown by emptying visible grid and using the SORT button, so Vault still get them, they aren't voided in any way, so that's a plus.
But you're absolutely right, polishing and debugging must always come first(thing my bosses sometime don't understand :/ lol)

**Comment by EtienneLamoureux** [comment]
Since there's some assets that would need to be created explicitly for this, I'll decide that we'll only support the unmodded inventory.
