### ISSUE TITLE
TQVaultAE_2.5.7-alpha stopped working

### ISSUE THREAD

**Issue by EismarParedes** [EtienneLamoureux/TQVaultAE#99]
Hi, I have a problem with the TQVault, days ago It stopped working, My game is TQ Anniversary Edition with Ragnarok Expasion installed of Steam, and the version of the TQVault that I use is TQVaultAE_2.5.7-alpha, I tried to edit the config file, changing auto-detect, AppData user.config and some paths with no results, using other version of the TQVault (2.5.6) creates a file called "tqdebug.txt" I'll attach the file below and I attach to my user.config (I rename it to txt to upload) and TQVaultAE.exe.config (I rename it to txt to upload).

[TQVaultAE.exe.config.txt](https://github.com/EtienneLamoureux/TQVaultAE/files/2617853/TQVaultAE.exe.config.txt)

[user.config.txt]
(https://github.com/EtienneLamoureux/TQVaultAE/files/2617857/user.config.txt)

[tqdebug.txt]
(https://github.com/EtienneLamoureux/TQVaultAE/files/2617859/tqdebug.txt)

I'll hope that someone can help me with my problem, thanks!
Edit: I play the game in Spanish version, but I want to set it in English, I don't know it that info helps.

**Comment by EtienneLamoureux** [comment]
Thanks for providing the debug report. Looks related to the locale (language). Will take a look.

**Comment by EtienneLamoureux** [comment]
Try to set the language manually in the AppData `user.config` file:
```
<setting name="AutoDetectLanguage" serializeAs="String">
   <value>False</value>
</setting>
...
<setting name="TQLanguage" serializeAs="String">
   <value>English</value>
</setting>
```

**Comment by EismarParedes** [comment]
Hi, Thanks for the reply, I tried but with no results, the stop working problem continues and the debug file says the same that I attached before.

**Comment by EtienneLamoureux** [comment]
Alright thanks for trying. Since it can't be fixed by the configuration, I'll look into fixing it on our end then.
